import { ThemePreset } from "../types";

export const colorfulPresets: ThemePreset[] = [
  // 🌸 Girly Pink - Soft pastels and romantic pinks
  {
    id: "girly-pink",
    name: "🌸 Girly Pink",
    description: "Soft pastels and romantic pink vibes",
    category: "colorful",
    preview: "",
    theme: {
      name: "Girly Pink",
      version: "1.0.0",
      author: "VibeStudio",
      description: "Soft pastels and romantic pink vibes",
      created: new Date().toISOString(),
      modified: new Date().toISOString(),

      font: {
        family: "Comic Code Ligatures, monospace",
        size: 14,
        weight: "normal",
        ligatures: true,
        lineHeight: 1.3,
      },

      cursor: {
        style: "line",
        blinking: true,
        color: "#e91e63",
      },

      colors: {
        background: "#fce4ec",
        foreground: "#880e4f",
        selection: "#f06292",
        selectionBackground: "#f06292",

        ansiBlack: "#880e4f",
        ansiRed: "#e91e63",
        ansiGreen: "#4caf50",
        ansiYellow: "#ff9800",
        ansiBlue: "#2196f3",
        ansiMagenta: "#9c27b0",
        ansiCyan: "#00bcd4",
        ansiWhite: "#fce4ec",
        ansiBrightBlack: "#ad1457",
        ansiBrightRed: "#f8bbd9",
        ansiBrightGreen: "#81c784",
        ansiBrightYellow: "#ffb74d",
        ansiBrightBlue: "#64b5f6",
        ansiBrightMagenta: "#ba68c8",
        ansiBrightCyan: "#4dd0e1",
        ansiBrightWhite: "#ffffff",

        border: "#f48fb1",
        tab: {
          activeForeground: "#880e4f",
          activeBackground: "#f8bbd9",
          inactiveForeground: "#ad1457",
          inactiveBackground: "#fce4ec",
          border: "#f48fb1",
        },
      },

      integration: {
        applyToEditor: true,
        applyToTerminal: true,
        applyToWorkbench: true,
      },

      editorTheme: {
        editor: {
          background: "#fff0f3",
          foreground: "#880e4f",
          selectionBackground: "#f06292",
          selectionForeground: "#ffffff",
          lineHighlightBackground: "#fce4ec",
          cursorColor: "#e91e63",
          indentGuideBackground: "#f48fb1",
          indentGuideActiveBackground: "#e91e63",
        },
        activityBar: {
          background: "#f8bbd9",
          foreground: "#880e4f",
          inactiveForeground: "#ad1457",
          border: "#f48fb1",
          activeBorder: "#e91e63",
          activeBackground: "#f48fb1",
        },
        sideBar: {
          background: "#fce4ec",
          foreground: "#880e4f",
          border: "#f48fb1",
        },
        sideBarSectionHeader: {
          background: "#f48fb1",
          foreground: "#ffffff",
          border: "#e91e63",
        },
        statusBar: {
          background: "#e91e63",
          foreground: "#ffffff",
          border: "#e91e63",
          debuggingBackground: "#9c27b0",
          debuggingForeground: "#ffffff",
          noFolderBackground: "#673ab7",
          noFolderForeground: "#ffffff",
        },
        titleBar: {
          activeBackground: "#f8bbd9",
          activeForeground: "#880e4f",
          inactiveBackground: "#fce4ec",
          inactiveForeground: "#ad1457",
          border: "#f48fb1",
        },
        panel: {
          background: "#fff0f3",
          border: "#f48fb1",
          dropBorder: "#e91e63",
        },
        tab: {
          background: "#fce4ec",
          activeBackground: "#fff0f3",
          activeForeground: "#880e4f",
          activeBorder: "#e91e63",
          activeBorderTop: "#e91e63",
          inactiveBackground: "#fce4ec",
          inactiveForeground: "#ad1457",
          inactiveModifiedBorder: "#9c27b0",
          unfocusedActiveBackground: "#fce4ec",
          unfocusedActiveForeground: "#ad1457",
          unfocusedInactiveBackground: "#f8bbd9",
          unfocusedInactiveForeground: "#c2185b",
          border: "#f48fb1",
        },
        input: {
          background: "#ffffff",
          foreground: "#880e4f",
          border: "#f48fb1",
          placeholderForeground: "#ad1457",
        },
        button: {
          background: "#e91e63",
          foreground: "#ffffff",
          hoverBackground: "#c2185b",
          secondaryBackground: "#f48fb1",
          secondaryForeground: "#880e4f",
          secondaryHoverBackground: "#f06292",
        },
        checkbox: {
          background: "#ffffff",
          foreground: "#880e4f",
          border: "#f48fb1",
        },
        badge: {
          background: "#e91e63",
          foreground: "#ffffff",
        },
        progressBar: {
          background: "#e91e63",
        },
        dropdown: {
          background: "#ffffff",
          foreground: "#880e4f",
          border: "#f48fb1",
        },
        list: {
          activeSelectionBackground: "#f06292",
          activeSelectionForeground: "#ffffff",
          inactiveSelectionBackground: "#f8bbd9",
          inactiveSelectionForeground: "#880e4f",
          hoverBackground: "#fce4ec",
          hoverForeground: "#880e4f",
          focusBackground: "#f06292",
          focusForeground: "#ffffff",
        },
        scrollbar: {
          shadow: "#f48fb1",
        },
        syntax: {
          comment: "#ad1457",
          keyword: "#e91e63",
          string: "#4caf50",
          number: "#9c27b0",
          function: "#673ab7",
          variable: "#880e4f",
          type: "#2196f3",
          class: "#e91e63",
          interface: "#9c27b0",
          namespace: "#673ab7",
          operator: "#e91e63",
          punctuation: "#880e4f",
          constant: "#9c27b0",
          property: "#880e4f",
          tag: "#e91e63",
          attribute: "#9c27b0",
        },
      },

      effects: {
        transparency: 5,
        blur: 2,
        animations: true,
        particleEffects: true,
        glowEffect: true,
        scanlines: false,
        crtEffect: false,
      },
    },
  },

  // 🌸 Girly Pink Dark - Dark mode with romantic pink vibes
  {
    id: "girly-pink-dark",
    name: "🌸 Girly Pink Dark",
    description: "Dark mode with romantic pink vibes and soft pastels",
    category: "colorful",
    preview: "",
    theme: {
      name: "Girly Pink Dark",
      version: "1.0.0",
      author: "VibeStudio",
      description: "Dark mode with romantic pink vibes and soft pastels",
      created: new Date().toISOString(),
      modified: new Date().toISOString(),

      font: {
        family: "Comic Code Ligatures, monospace",
        size: 14,
        weight: "normal",
        ligatures: true,
        lineHeight: 1.3,
      },

      cursor: {
        style: "line",
        blinking: true,
        color: "#f8bbd9",
      },

      colors: {
        background: "#1a0d14",
        foreground: "#f8bbd9",
        selection: "#e91e63",
        selectionBackground: "#e91e63",

        ansiBlack: "#1a0d14",
        ansiRed: "#f8bbd9",
        ansiGreen: "#81c784",
        ansiYellow: "#ffb74d",
        ansiBlue: "#64b5f6",
        ansiMagenta: "#e91e63",
        ansiCyan: "#4dd0e1",
        ansiWhite: "#f8bbd9",
        ansiBrightBlack: "#4a1e2e",
        ansiBrightRed: "#e91e63",
        ansiBrightGreen: "#4caf50",
        ansiBrightYellow: "#ff9800",
        ansiBrightBlue: "#2196f3",
        ansiBrightMagenta: "#ba68c8",
        ansiBrightCyan: "#00bcd4",
        ansiBrightWhite: "#ffffff",

        border: "#4a1e2e",
        tab: {
          activeForeground: "#f8bbd9",
          activeBackground: "#2d1017",
          inactiveForeground: "#ad6b85",
          inactiveBackground: "#1a0d14",
          border: "#4a1e2e",
        },
      },

      integration: {
        applyToEditor: true,
        applyToTerminal: true,
        applyToWorkbench: true,
      },

      editorTheme: {
        editor: {
          background: "#1a0d14",
          foreground: "#f8bbd9",
          selectionBackground: "#e91e63",
          selectionForeground: "#ffffff",
          lineHighlightBackground: "#2d1017",
          cursorColor: "#f8bbd9",
          indentGuideBackground: "#4a1e2e",
          indentGuideActiveBackground: "#e91e63",
        },
        activityBar: {
          background: "#2d1017",
          foreground: "#f8bbd9",
          inactiveForeground: "#ad6b85",
          border: "#4a1e2e",
          activeBorder: "#e91e63",
          activeBackground: "#4a1e2e",
        },
        sideBar: {
          background: "#1a0d14",
          foreground: "#f8bbd9",
          border: "#4a1e2e",
        },
        sideBarSectionHeader: {
          background: "#4a1e2e",
          foreground: "#f8bbd9",
          border: "#e91e63",
        },
        statusBar: {
          background: "#e91e63",
          foreground: "#ffffff",
          border: "#e91e63",
          debuggingBackground: "#9c27b0",
          debuggingForeground: "#ffffff",
          noFolderBackground: "#673ab7",
          noFolderForeground: "#ffffff",
        },
        titleBar: {
          activeBackground: "#2d1017",
          activeForeground: "#f8bbd9",
          inactiveBackground: "#1a0d14",
          inactiveForeground: "#ad6b85",
          border: "#4a1e2e",
        },
        panel: {
          background: "#1a0d14",
          border: "#4a1e2e",
          dropBorder: "#e91e63",
        },
        tab: {
          background: "#0d0a0b",
          activeBackground: "#1a0d14",
          activeForeground: "#f8bbd9",
          activeBorder: "#e91e63",
          activeBorderTop: "#e91e63",
          inactiveBackground: "#2d1017",
          inactiveForeground: "#ad6b85",
          inactiveModifiedBorder: "#9c27b0",
          unfocusedActiveBackground: "#2d1017",
          unfocusedActiveForeground: "#ad6b85",
          unfocusedInactiveBackground: "#1a0d14",
          unfocusedInactiveForeground: "#6b4c57",
          border: "#4a1e2e",
        },
        input: {
          background: "#2d1017",
          foreground: "#f8bbd9",
          border: "#4a1e2e",
          placeholderForeground: "#ad6b85",
        },
        button: {
          background: "#e91e63",
          foreground: "#ffffff",
          hoverBackground: "#c2185b",
          secondaryBackground: "#4a1e2e",
          secondaryForeground: "#f8bbd9",
          secondaryHoverBackground: "#6b2943",
        },
        checkbox: {
          background: "#2d1017",
          foreground: "#f8bbd9",
          border: "#4a1e2e",
        },
        badge: {
          background: "#e91e63",
          foreground: "#ffffff",
        },
        progressBar: {
          background: "#e91e63",
        },
        dropdown: {
          background: "#2d1017",
          foreground: "#f8bbd9",
          border: "#4a1e2e",
        },
        list: {
          activeSelectionBackground: "#e91e63",
          activeSelectionForeground: "#ffffff",
          inactiveSelectionBackground: "#4a1e2e",
          inactiveSelectionForeground: "#f8bbd9",
          hoverBackground: "#2d1017",
          hoverForeground: "#f8bbd9",
          focusBackground: "#e91e63",
          focusForeground: "#ffffff",
        },
        scrollbar: {
          shadow: "#4a1e2e",
        },
        syntax: {
          comment: "#ad6b85",
          keyword: "#e91e63",
          string: "#81c784",
          number: "#ba68c8",
          function: "#9c27b0",
          variable: "#f8bbd9",
          type: "#64b5f6",
          class: "#e91e63",
          interface: "#ba68c8",
          namespace: "#9c27b0",
          operator: "#e91e63",
          punctuation: "#f8bbd9",
          constant: "#ba68c8",
          property: "#f8bbd9",
          tag: "#e91e63",
          attribute: "#ba68c8",
        },
      },

      effects: {
        transparency: 5,
        blur: 2,
        animations: true,
        particleEffects: true,
        glowEffect: true,
        scanlines: false,
        crtEffect: false,
      },
    },
  },

  // 🌈 Anime Vibe - Bright and energetic anime-inspired colors
  {
    id: "anime-vibe",
    name: "🌈 Anime Vibe",
    description: "Bright and energetic anime-inspired colors",
    category: "colorful",
    preview: "",
    theme: {
      name: "Anime Vibe",
      version: "1.0.0",
      author: "VibeStudio",
      description: "Bright and energetic anime-inspired colors",
      created: new Date().toISOString(),
      modified: new Date().toISOString(),

      font: {
        family: "Fira Code, monospace",
        size: 14,
        weight: "normal",
        ligatures: true,
        lineHeight: 1.2,
      },

      cursor: {
        style: "block",
        blinking: true,
        color: "#ff1744",
      },

      colors: {
        background: "#0d1117",
        foreground: "#f0f6fc",
        selection: "#ff1744",
        selectionBackground: "#ff1744",

        ansiBlack: "#0d1117",
        ansiRed: "#ff1744",
        ansiGreen: "#00e676",
        ansiYellow: "#ffc107",
        ansiBlue: "#2196f3",
        ansiMagenta: "#e91e63",
        ansiCyan: "#00bcd4",
        ansiWhite: "#f0f6fc",
        ansiBrightBlack: "#30363d",
        ansiBrightRed: "#ff5722",
        ansiBrightGreen: "#4caf50",
        ansiBrightYellow: "#ffeb3b",
        ansiBrightBlue: "#03a9f4",
        ansiBrightMagenta: "#9c27b0",
        ansiBrightCyan: "#00e5ff",
        ansiBrightWhite: "#ffffff",

        border: "#21262d",
        tab: {
          activeForeground: "#f0f6fc",
          activeBackground: "#161b22",
          inactiveForeground: "#8b949e",
          inactiveBackground: "#0d1117",
          border: "#21262d",
        },
      },

      integration: {
        applyToEditor: true,
        applyToTerminal: true,
        applyToWorkbench: true,
      },

      editorTheme: {
        editor: {
          background: "#0d1117",
          foreground: "#f0f6fc",
          selectionBackground: "#ff1744",
          selectionForeground: "#ffffff",
          lineHighlightBackground: "#161b22",
          cursorColor: "#ff1744",
          indentGuideBackground: "#21262d",
          indentGuideActiveBackground: "#ff1744",
        },
        activityBar: {
          background: "#010409",
          foreground: "#ff1744",
          inactiveForeground: "#8b949e",
          border: "#21262d",
          activeBorder: "#ffc107",
          activeBackground: "#161b22",
        },
        sideBar: {
          background: "#0d1117",
          foreground: "#f0f6fc",
          border: "#21262d",
        },
        sideBarSectionHeader: {
          background: "#161b22",
          foreground: "#ffc107",
          border: "#ff1744",
        },
        statusBar: {
          background: "#ff1744",
          foreground: "#ffffff",
          border: "#ff1744",
          debuggingBackground: "#e91e63",
          debuggingForeground: "#ffffff",
          noFolderBackground: "#9c27b0",
          noFolderForeground: "#ffffff",
        },
        titleBar: {
          activeBackground: "#010409",
          activeForeground: "#f0f6fc",
          inactiveBackground: "#0d1117",
          inactiveForeground: "#8b949e",
          border: "#21262d",
        },
        panel: {
          background: "#0d1117",
          border: "#21262d",
          dropBorder: "#ff1744",
        },
        tab: {
          background: "#010409",
          activeBackground: "#0d1117",
          activeForeground: "#f0f6fc",
          activeBorder: "#ffc107",
          activeBorderTop: "#ffc107",
          inactiveBackground: "#161b22",
          inactiveForeground: "#8b949e",
          inactiveModifiedBorder: "#e91e63",
          unfocusedActiveBackground: "#161b22",
          unfocusedActiveForeground: "#8b949e",
          unfocusedInactiveBackground: "#010409",
          unfocusedInactiveForeground: "#6e7681",
          border: "#21262d",
        },
        input: {
          background: "#21262d",
          foreground: "#f0f6fc",
          border: "#30363d",
          placeholderForeground: "#8b949e",
        },
        button: {
          background: "#ff1744",
          foreground: "#ffffff",
          hoverBackground: "#d50000",
          secondaryBackground: "#21262d",
          secondaryForeground: "#f0f6fc",
          secondaryHoverBackground: "#30363d",
        },
        checkbox: {
          background: "#21262d",
          foreground: "#f0f6fc",
          border: "#30363d",
        },
        badge: {
          background: "#ffc107",
          foreground: "#0d1117",
        },
        progressBar: {
          background: "#ff1744",
        },
        dropdown: {
          background: "#21262d",
          foreground: "#f0f6fc",
          border: "#30363d",
        },
        list: {
          activeSelectionBackground: "#ff1744",
          activeSelectionForeground: "#ffffff",
          inactiveSelectionBackground: "#21262d",
          inactiveSelectionForeground: "#f0f6fc",
          hoverBackground: "#161b22",
          hoverForeground: "#f0f6fc",
          focusBackground: "#ff1744",
          focusForeground: "#ffffff",
        },
        scrollbar: {
          shadow: "#010409",
        },
        syntax: {
          comment: "#8b949e",
          keyword: "#ff1744",
          string: "#00e676",
          number: "#ffc107",
          function: "#2196f3",
          variable: "#f0f6fc",
          type: "#e91e63",
          class: "#00bcd4",
          interface: "#9c27b0",
          namespace: "#ff5722",
          operator: "#ff1744",
          punctuation: "#f0f6fc",
          constant: "#ffc107",
          property: "#f0f6fc",
          tag: "#ff1744",
          attribute: "#00e676",
        },
      },

      effects: {
        transparency: 10,
        blur: 3,
        animations: true,
        particleEffects: true,
        glowEffect: true,
        scanlines: false,
        crtEffect: false,
      },
    },
  },

  // 🌈 Pastel Rainbow - Soft rainbow colors and dreamy vibes
  {
    id: "pastel-rainbow",
    name: "🌈 Pastel Rainbow",
    description: "Soft rainbow colors and dreamy vibes",
    category: "pastel",
    preview: "",
    theme: {
      name: "Pastel Rainbow",
      version: "1.0.0",
      author: "VibeStudio",
      description: "Soft rainbow colors and dreamy vibes",
      created: new Date().toISOString(),
      modified: new Date().toISOString(),

      font: {
        family: "Victor Mono, monospace",
        size: 14,
        weight: "normal",
        ligatures: true,
        lineHeight: 1.3,
      },

      cursor: {
        style: "line",
        blinking: true,
        color: "#ff69b4",
      },

      colors: {
        background: "#fef7ff",
        foreground: "#6d597a",
        selection: "#ff69b4",
        selectionBackground: "#ff69b4",

        ansiBlack: "#8e8e93",
        ansiRed: "#ff9f9b",
        ansiGreen: "#91f5ad",
        ansiYellow: "#ffef5b",
        ansiBlue: "#a8ccf0",
        ansiMagenta: "#ffb3ff",
        ansiCyan: "#a8e6cf",
        ansiWhite: "#fef7ff",
        ansiBrightBlack: "#b0b0b5",
        ansiBrightRed: "#ffbbb8",
        ansiBrightGreen: "#b5f7c8",
        ansiBrightYellow: "#fff485",
        ansiBrightBlue: "#c4d9f4",
        ansiBrightMagenta: "#ffc9ff",
        ansiBrightCyan: "#c4eedc",
        ansiBrightWhite: "#ffffff",

        border: "#e1bee7",
        tab: {
          activeForeground: "#6d597a",
          activeBackground: "#f3e5f5",
          inactiveForeground: "#9c88a6",
          inactiveBackground: "#fef7ff",
          border: "#e1bee7",
        },
      },

      integration: {
        applyToEditor: true,
        applyToTerminal: true,
        applyToWorkbench: true,
      },

      editorTheme: {
        editor: {
          background: "#fef7ff",
          foreground: "#6d597a",
          selectionBackground: "#ff69b4",
          selectionForeground: "#ffffff",
          lineHighlightBackground: "#f3e5f5",
          cursorColor: "#ff69b4",
          indentGuideBackground: "#e1bee7",
          indentGuideActiveBackground: "#ff69b4",
        },
        activityBar: {
          background: "#f8bbd9",
          foreground: "#6d597a",
          inactiveForeground: "#9c88a6",
          border: "#e1bee7",
          activeBorder: "#ffef5b",
          activeBackground: "#f3e5f5",
        },
        sideBar: {
          background: "#fef7ff",
          foreground: "#6d597a",
          border: "#e1bee7",
        },
        sideBarSectionHeader: {
          background: "#f3e5f5",
          foreground: "#ff69b4",
          border: "#ffef5b",
        },
        statusBar: {
          background: "#ff69b4",
          foreground: "#ffffff",
          border: "#ff69b4",
          debuggingBackground: "#ffb3ff",
          debuggingForeground: "#6d597a",
          noFolderBackground: "#a8ccf0",
          noFolderForeground: "#ffffff",
        },
        titleBar: {
          activeBackground: "#f8bbd9",
          activeForeground: "#6d597a",
          inactiveBackground: "#fef7ff",
          inactiveForeground: "#9c88a6",
          border: "#e1bee7",
        },
        panel: {
          background: "#fef7ff",
          border: "#e1bee7",
          dropBorder: "#ff69b4",
        },
        tab: {
          background: "#f8bbd9",
          activeBackground: "#fef7ff",
          activeForeground: "#6d597a",
          activeBorder: "#ffef5b",
          activeBorderTop: "#ffef5b",
          inactiveBackground: "#f3e5f5",
          inactiveForeground: "#9c88a6",
          inactiveModifiedBorder: "#ffb3ff",
          unfocusedActiveBackground: "#f3e5f5",
          unfocusedActiveForeground: "#9c88a6",
          unfocusedInactiveBackground: "#f8bbd9",
          unfocusedInactiveForeground: "#c8aed6",
          border: "#e1bee7",
        },
        input: {
          background: "#ffffff",
          foreground: "#6d597a",
          border: "#e1bee7",
          placeholderForeground: "#9c88a6",
        },
        button: {
          background: "#ff69b4",
          foreground: "#ffffff",
          hoverBackground: "#ff1493",
          secondaryBackground: "#e1bee7",
          secondaryForeground: "#6d597a",
          secondaryHoverBackground: "#ce93d8",
        },
        checkbox: {
          background: "#ffffff",
          foreground: "#6d597a",
          border: "#e1bee7",
        },
        badge: {
          background: "#ffef5b",
          foreground: "#6d597a",
        },
        progressBar: {
          background: "#ff69b4",
        },
        dropdown: {
          background: "#ffffff",
          foreground: "#6d597a",
          border: "#e1bee7",
        },
        list: {
          activeSelectionBackground: "#ff69b4",
          activeSelectionForeground: "#ffffff",
          inactiveSelectionBackground: "#e1bee7",
          inactiveSelectionForeground: "#6d597a",
          hoverBackground: "#f3e5f5",
          hoverForeground: "#6d597a",
          focusBackground: "#ff69b4",
          focusForeground: "#ffffff",
        },
        scrollbar: {
          shadow: "#f8bbd9",
        },
        syntax: {
          comment: "#9c88a6",
          keyword: "#ff69b4",
          string: "#91f5ad",
          number: "#ffef5b",
          function: "#a8ccf0",
          variable: "#6d597a",
          type: "#ffb3ff",
          class: "#ff69b4",
          interface: "#a8ccf0",
          namespace: "#ffb3ff",
          operator: "#ff69b4",
          punctuation: "#6d597a",
          constant: "#ffef5b",
          property: "#6d597a",
          tag: "#ff69b4",
          attribute: "#91f5ad",
        },
      },

      effects: {
        transparency: 10,
        blur: 3,
        animations: true,
        particleEffects: true,
        glowEffect: true,
        scanlines: false,
        crtEffect: false,
      },
    },
  },

  // 🌴 Tropical Paradise - Vibrant tropical theme
  {
    id: "tropical-paradise",
    name: "🌴 Tropical Paradise",
    description: "Vibrant tropical colors with exotic paradise vibes",
    category: "colorful",
    preview: "",
    theme: {
      name: "Tropical Paradise",
      version: "1.0.0",
      author: "VibeStudio",
      description: "Vibrant tropical colors with exotic paradise vibes",
      created: new Date().toISOString(),
      modified: new Date().toISOString(),

      font: {
        family: "Roboto Mono, monospace",
        size: 14,
        weight: "300",
        ligatures: true,
        lineHeight: 1.4,
      },

      cursor: {
        style: "line",
        blinking: true,
        color: "#ff6b35",
      },

      colors: {
        background: "#004643",
        foreground: "#f9bc60",
        selection: "#abd1c6",
        selectionBackground: "#abd1c6",

        ansiBlack: "#001e1d",
        ansiRed: "#e16162",
        ansiGreen: "#0f3433",
        ansiYellow: "#f9bc60",
        ansiBlue: "#abd1c6",
        ansiMagenta: "#ffeedd",
        ansiCyan: "#e16162",
        ansiWhite: "#f9bc60",
        ansiBrightBlack: "#002725",
        ansiBrightRed: "#ff7f80",
        ansiBrightGreen: "#1a5855",
        ansiBrightYellow: "#ffd580",
        ansiBrightBlue: "#c8e6e0",
        ansiBrightMagenta: "#fff8ee",
        ansiBrightCyan: "#ff9999",
        ansiBrightWhite: "#ffcc80",

        border: "#0f3433",
        tab: {
          activeForeground: "#f9bc60",
          activeBackground: "#004643",
          inactiveForeground: "#abd1c6",
          inactiveBackground: "#001e1d",
          border: "#0f3433",
        },
      },

      integration: {
        applyToEditor: true,
        applyToTerminal: true,
        applyToWorkbench: true,
      },

      editorTheme: {
        editor: {
          background: "#004643",
          foreground: "#f9bc60",
          selectionBackground: "#abd1c680",
          selectionForeground: "#004643",
          lineHighlightBackground: "#0f3433",
          cursorColor: "#ff6b35",
          indentGuideBackground: "#0f3433",
          indentGuideActiveBackground: "#abd1c6",
        },
        activityBar: {
          background: "#0f3433",
          foreground: "#f9bc60",
          inactiveForeground: "#abd1c6",
          border: "#0f3433",
          activeBorder: "#ff6b35",
          activeBackground: "#004643",
        },
        sideBar: {
          background: "#004643",
          foreground: "#f9bc60",
          border: "#0f3433",
        },
        sideBarSectionHeader: {
          background: "#0f3433",
          foreground: "#ff6b35",
          border: "#abd1c6",
        },
        statusBar: {
          background: "#ff6b35",
          foreground: "#ffffff",
          border: "#ff6b35",
          debuggingBackground: "#abd1c6",
          debuggingForeground: "#004643",
          noFolderBackground: "#c8e6e0",
          noFolderForeground: "#ffffff",
        },
        titleBar: {
          activeBackground: "#0f3433",
          activeForeground: "#f9bc60",
          inactiveBackground: "#004643",
          inactiveForeground: "#abd1c6",
          border: "#0f3433",
        },
        panel: {
          background: "#004643",
          border: "#0f3433",
          dropBorder: "#ff6b35",
        },
        tab: {
          background: "#001e1d",
          activeBackground: "#004643",
          activeForeground: "#f9bc60",
          activeBorder: "#ff6b35",
          activeBorderTop: "#ff6b35",
          inactiveBackground: "#0f3433",
          inactiveForeground: "#abd1c6",
          inactiveModifiedBorder: "#abd1c6",
          unfocusedActiveBackground: "#0f3433",
          unfocusedActiveForeground: "#abd1c6",
          unfocusedInactiveBackground: "#004643",
          unfocusedInactiveForeground: "#4d908e",
          border: "#0f3433",
        },
        input: {
          background: "#0f3433",
          foreground: "#f9bc60",
          border: "#0f3433",
          placeholderForeground: "#abd1c6",
        },
        button: {
          background: "#ff6b35",
          foreground: "#ffffff",
          hoverBackground: "#e73c0e",
          secondaryBackground: "#0f3433",
          secondaryForeground: "#f9bc60",
          secondaryHoverBackground: "#4d908e",
        },
        checkbox: {
          background: "#0f3433",
          foreground: "#f9bc60",
          border: "#0f3433",
        },
        badge: {
          background: "#ff6b35",
          foreground: "#ffffff",
        },
        progressBar: {
          background: "#ff6b35",
        },
        dropdown: {
          background: "#0f3433",
          foreground: "#f9bc60",
          border: "#0f3433",
        },
        list: {
          activeSelectionBackground: "#abd1c680",
          activeSelectionForeground: "#004643",
          inactiveSelectionBackground: "#0f3433",
          inactiveSelectionForeground: "#f9bc60",
          hoverBackground: "#0f3433",
          hoverForeground: "#f9bc60",
          focusBackground: "#abd1c680",
          focusForeground: "#004643",
        },
        scrollbar: {
          shadow: "#0f3433",
        },
        syntax: {
          comment: "#abd1c6",
          keyword: "#ff6b35",
          string: "#0f3433",
          number: "#abd1c6",
          function: "#004643",
          variable: "#f9bc60",
          type: "#c8e6e0",
          class: "#ff6b35",
          interface: "#abd1c6",
          namespace: "#004643",
          operator: "#ff6b35",
          punctuation: "#0f3433",
          constant: "#abd1c6",
          property: "#0f3433",
          tag: "#ff6b35",
          attribute: "#c8e6e0",
        },
      },

      effects: {
        transparency: 7,
        blur: 2,
        animations: true,
        particleEffects: true,
        glowEffect: false,
        scanlines: false,
        crtEffect: false,
      },
    },
  },

  // 🎨 Artist's Palette - Creative paint splashes
  {
    id: "artist-palette",
    name: "🎨 Artist's Palette",
    description: "Creative paint splashes and artistic vibes with vibrant mixed colors",
    category: "colorful",
    preview: "",
    theme: {
      name: "Artist's Palette",
      version: "1.0.0",
      author: "VibeStudio",
      description: "Creative paint splashes and artistic vibes with vibrant mixed colors",
      created: new Date().toISOString(),
      modified: new Date().toISOString(),

      font: {
        family: "Comfortaa, monospace",
        size: 14,
        weight: "normal",
        ligatures: true,
        lineHeight: 1.4,
      },

      cursor: {
        style: "line",
        blinking: true,
        color: "#ff6b9d",
      },

      colors: {
        background: "#faf8ff",
        foreground: "#2d1b4e",
        selection: "#c7d2fe",
        selectionBackground: "#c7d2fe",

        ansiBlack: "#2d1b4e",
        ansiRed: "#ff6b9d",
        ansiGreen: "#06d6a0",
        ansiYellow: "#ffd23f",
        ansiBlue: "#118ab2",
        ansiMagenta: "#8338ec",
        ansiCyan: "#3a86ff",
        ansiWhite: "#faf8ff",
        ansiBrightBlack: "#5a4b7a",
        ansiBrightRed: "#ff8fab",
        ansiBrightGreen: "#29e2b8",
        ansiBrightYellow: "#ffda57",
        ansiBrightBlue: "#1e9bc7",
        ansiBrightMagenta: "#9c4eff",
        ansiBrightCyan: "#5b9cff",
        ansiBrightWhite: "#ffffff",

        border: "#c7d2fe",
        tab: {
          activeForeground: "#2d1b4e",
          activeBackground: "#faf8ff",
          inactiveForeground: "#5a4b7a",
          inactiveBackground: "#f0f0ff",
          border: "#c7d2fe",
        },
      },

      integration: {
        applyToEditor: true,
        applyToTerminal: true,
        applyToWorkbench: true,
      },

      editorTheme: {
        editor: {
          background: "#faf8ff",
          foreground: "#2d1b4e",
          selectionBackground: "#c7d2fe80",
          selectionForeground: "#2d1b4e",
          lineHighlightBackground: "#f0f0ff",
          cursorColor: "#ff6b9d",
          indentGuideBackground: "#e0e7ff",
          indentGuideActiveBackground: "#ff6b9d",
        },
        activityBar: {
          background: "#f0f0ff",
          foreground: "#2d1b4e",
          inactiveForeground: "#5a4b7a",
          border: "#c7d2fe",
          activeBorder: "#ff6b9d",
          activeBackground: "#faf8ff",
        },
        sideBar: {
          background: "#faf8ff",
          foreground: "#2d1b4e",
          border: "#c7d2fe",
        },
        sideBarSectionHeader: {
          background: "#f0f0ff",
          foreground: "#8338ec",
          border: "#ff6b9d",
        },
        statusBar: {
          background: "#ff6b9d",
          foreground: "#ffffff",
          border: "#ff6b9d",
          debuggingBackground: "#8338ec",
          debuggingForeground: "#ffffff",
          noFolderBackground: "#118ab2",
          noFolderForeground: "#ffffff",
        },
        titleBar: {
          activeBackground: "#f0f0ff",
          activeForeground: "#2d1b4e",
          inactiveBackground: "#faf8ff",
          inactiveForeground: "#5a4b7a",
          border: "#c7d2fe",
        },
        panel: {
          background: "#faf8ff",
          border: "#c7d2fe",
          dropBorder: "#ff6b9d",
        },
        tab: {
          background: "#f0f0ff",
          activeBackground: "#faf8ff",
          activeForeground: "#2d1b4e",
          activeBorder: "#ff6b9d",
          activeBorderTop: "#ff6b9d",
          inactiveBackground: "#f0f0ff",
          inactiveForeground: "#5a4b7a",
          inactiveModifiedBorder: "#06d6a0",
          unfocusedActiveBackground: "#f0f0ff",
          unfocusedActiveForeground: "#5a4b7a",
          unfocusedInactiveBackground: "#faf8ff",
          unfocusedInactiveForeground: "#9ca3af",
          border: "#c7d2fe",
        },
        input: {
          background: "#ffffff",
          foreground: "#2d1b4e",
          border: "#c7d2fe",
          placeholderForeground: "#5a4b7a",
        },
        button: {
          background: "#ff6b9d",
          foreground: "#ffffff",
          hoverBackground: "#ff8fab",
          secondaryBackground: "#c7d2fe",
          secondaryForeground: "#2d1b4e",
          secondaryHoverBackground: "#a5b4fc",
        },
        checkbox: {
          background: "#ffffff",
          foreground: "#2d1b4e",
          border: "#c7d2fe",
        },
        badge: {
          background: "#ff6b9d",
          foreground: "#ffffff",
        },
        progressBar: {
          background: "#ff6b9d",
        },
        dropdown: {
          background: "#ffffff",
          foreground: "#2d1b4e",
          border: "#c7d2fe",
        },
        list: {
          activeSelectionBackground: "#c7d2fe80",
          activeSelectionForeground: "#2d1b4e",
          inactiveSelectionBackground: "#f0f0ff",
          inactiveSelectionForeground: "#2d1b4e",
          hoverBackground: "#f0f0ff",
          hoverForeground: "#2d1b4e",
          focusBackground: "#c7d2fe80",
          focusForeground: "#2d1b4e",
        },
        scrollbar: {
          shadow: "#c7d2fe",
        },
        syntax: {
          comment: "#5a4b7a",
          keyword: "#ff6b9d",
          string: "#06d6a0",
          number: "#ffd23f",
          function: "#118ab2",
          variable: "#2d1b4e",
          type: "#8338ec",
          class: "#ff6b9d",
          interface: "#3a86ff",
          namespace: "#118ab2",
          operator: "#ff6b9d",
          punctuation: "#2d1b4e",
          constant: "#ffd23f",
          property: "#2d1b4e",
          tag: "#ff6b9d",
          attribute: "#8338ec",
        },
      },

      effects: {
        transparency: 5,
        blur: 2,
        animations: true,
        particleEffects: true,
        glowEffect: false,
        scanlines: false,
        crtEffect: false,
      },
    },
  },
];
