import { ThemePreset } from "../types";

export const corePresets: ThemePreset[] = [
  // 🌑 Dark VibeStudio - Complete VS Code dark theme
  {
    id: "dark-vscode",
    name: "🌑 Dark VibeStudio",
    description: "Complete VS Code dark theme",
    category: "dark",
    preview: "",
    theme: {
      name: "Dark VibeStudio",
      version: "1.0.0",
      author: "VibeStudio",
      description: "Complete VS Code dark theme",
      created: new Date().toISOString(),
      modified: new Date().toISOString(),

      font: {
        family: "Consolas, monospace",
        size: 14,
        weight: "normal",
        ligatures: false,
        lineHeight: 1.2,
      },

      cursor: {
        style: "block",
        blinking: false,
        color: "#ffffff",
      },

      colors: {
        background: "#1e1e1e",
        foreground: "#d4d4d4",
        selection: "#264f78",
        selectionBackground: "#264f78",

        ansiBlack: "#000000",
        ansiRed: "#cd3131",
        ansiGreen: "#0dbc79",
        ansiYellow: "#e5e510",
        ansiBlue: "#2472c8",
        ansiMagenta: "#bc3fbc",
        ansiCyan: "#11a8cd",
        ansiWhite: "#e5e5e5",
        ansiBrightBlack: "#666666",
        ansiBrightRed: "#f14c4c",
        ansiBrightGreen: "#23d18b",
        ansiBrightYellow: "#f5f543",
        ansiBrightBlue: "#3b8eea",
        ansiBrightMagenta: "#d670d6",
        ansiBrightCyan: "#29b8db",
        ansiBrightWhite: "#e5e5e5",

        border: "#454545",
        tab: {
          activeForeground: "#ffffff",
          activeBackground: "#2d2d30",
          inactiveForeground: "#cccccc",
          inactiveBackground: "#1e1e1e",
          border: "#454545",
        },
      },

      integration: {
        applyToEditor: true,
        applyToTerminal: true,
        applyToWorkbench: true,
      },

      editorTheme: {
        editor: {
          background: "#1e1e1e",
          foreground: "#d4d4d4",
          selectionBackground: "#264f78",
          selectionForeground: "#ffffff",
          lineHighlightBackground: "#2a2d2e",
          cursorColor: "#ffffff",
          indentGuideBackground: "#404040",
          indentGuideActiveBackground: "#707070",
        },
        activityBar: {
          background: "#333333",
          foreground: "#ffffff",
          inactiveForeground: "#ffffff66",
          border: "#2d2d30",
          activeBorder: "#007acc",
          activeBackground: "#2d2d30",
        },
        sideBar: {
          background: "#252526",
          foreground: "#cccccc",
          border: "#2d2d30",
        },
        sideBarSectionHeader: {
          background: "#1e1e1e",
          foreground: "#ffffff",
          border: "#007acc",
        },
        panelTitle: {
          background: "#252526",
          activeForeground: "#ffffff",
          activeBorder: "#007acc",
          inactiveForeground: "#cccccc80",
        },
        statusBar: {
          background: "#007acc",
          foreground: "#ffffff",
          border: "#007acc",
          debuggingBackground: "#cc6633",
          debuggingForeground: "#ffffff",
          noFolderBackground: "#68217a",
          noFolderForeground: "#ffffff",
        },
        titleBar: {
          activeBackground: "#3c3c3c",
          activeForeground: "#cccccc",
          inactiveBackground: "#3c3c3c",
          inactiveForeground: "#cccccc99",
          border: "#2d2d30",
        },
        panel: {
          background: "#1e1e1e",
          border: "#2d2d30",
          dropBorder: "#007acc",
        },
        tab: {
          background: "#252526",
          activeBackground: "#1e1e1e",
          activeForeground: "#ffffff",
          activeBorder: "#007acc",
          activeBorderTop: "#007acc",
          inactiveBackground: "#2d2d30",
          inactiveForeground: "#cccccc80",
          inactiveModifiedBorder: "#e5e510",
          unfocusedActiveBackground: "#1e1e1e",
          unfocusedActiveForeground: "#cccccc80",
          unfocusedInactiveBackground: "#2d2d30",
          unfocusedInactiveForeground: "#cccccc40",
          border: "#252526",
        },
        input: {
          background: "#3c3c3c",
          foreground: "#cccccc",
          border: "#3c3c3c",
          placeholderForeground: "#cccccc80",
        },
        button: {
          background: "#0e639c",
          foreground: "#ffffff",
          hoverBackground: "#1177bb",
          secondaryBackground: "#5f6a79",
          secondaryForeground: "#ffffff",
          secondaryHoverBackground: "#6b7280",
        },
        checkbox: {
          background: "#3c3c3c",
          foreground: "#ffffff",
          border: "#454545",
        },
        badge: {
          background: "#007acc",
          foreground: "#ffffff",
        },
        progressBar: {
          background: "#007acc",
        },
        dropdown: {
          background: "#3c3c3c",
          foreground: "#cccccc",
          border: "#3c3c3c",
        },
        list: {
          activeSelectionBackground: "#094771",
          activeSelectionForeground: "#ffffff",
          inactiveSelectionBackground: "#37373d",
          inactiveSelectionForeground: "#cccccc",
          hoverBackground: "#2a2d2e",
          hoverForeground: "#ffffff",
          focusBackground: "#094771",
          focusForeground: "#ffffff",
        },
        scrollbar: {
          shadow: "#000000",
          sliderBackground: "#264040",
          sliderHoverBackground: "#456565",
          sliderActiveBackground: "#678a8a",
        },
        breadcrumb: {
          background: "#1e1e1e",
        },
        editorGutter: {
          background: "#1e1e1e",
        },
        minimap: {
          background: "#1e1e1e",
          sliderBackground: "#007acc60",
          sliderHoverBackground: "#007acc80",
          sliderActiveBackground: "#007acca0",
        },
        syntax: {
          comment: "#6a9955",
          keyword: "#569cd6",
          string: "#ce9178",
          number: "#b5cea8",
          function: "#dcdcaa",
          variable: "#9cdcfe",
          type: "#4ec9b0",
          class: "#4ec9b0",
          interface: "#b8d7a3",
          namespace: "#4ec9b0",
          operator: "#d4d4d4",
          punctuation: "#d4d4d4",
          constant: "#4fc1ff",
          property: "#9cdcfe",
          tag: "#569cd6",
          attribute: "#9cdcfe",
        },
      },

      effects: {
        transparency: 0,
        blur: 0,
        animations: false,
        particleEffects: false,
        glowEffect: false,
        scanlines: false,
        crtEffect: false,
      },
    },
  },

  // 🌕 Light VibeStudio - Clean and bright light theme
  {
    id: "light-vscode",
    name: "🌕 Light VibeStudio",
    description: "Clean and bright light VS Code theme",
    category: "light",
    preview: "",
    theme: {
      name: "Light VibeStudio",
      version: "1.0.0",
      author: "VibeStudio",
      description: "Clean and bright light VS Code theme",
      created: new Date().toISOString(),
      modified: new Date().toISOString(),

      font: {
        family: "Segoe UI, monospace",
        size: 14,
        weight: "normal",
        ligatures: false,
        lineHeight: 1.2,
      },

      cursor: {
        style: "line",
        blinking: true,
        color: "#000000",
      },

      colors: {
        background: "#ffffff",
        foreground: "#000000",
        selection: "#add6ff",
        selectionBackground: "#add6ff",

        ansiBlack: "#000000",
        ansiRed: "#cd3131",
        ansiGreen: "#00bc00",
        ansiYellow: "#949800",
        ansiBlue: "#0451a5",
        ansiMagenta: "#bc05bc",
        ansiCyan: "#0598bc",
        ansiWhite: "#555555",
        ansiBrightBlack: "#666666",
        ansiBrightRed: "#cd3131",
        ansiBrightGreen: "#14ce14",
        ansiBrightYellow: "#b5ba00",
        ansiBrightBlue: "#0451a5",
        ansiBrightMagenta: "#bc05bc",
        ansiBrightCyan: "#0598bc",
        ansiBrightWhite: "#a5a5a5",

        border: "#e5e5e5",
        tab: {
          activeForeground: "#333333",
          activeBackground: "#ffffff",
          inactiveForeground: "#333333",
          inactiveBackground: "#ececec",
          border: "#e5e5e5",
        },
      },

      integration: {
        applyToEditor: true,
        applyToTerminal: true,
        applyToWorkbench: true,
      },

      editorTheme: {
        editor: {
          background: "#ffffff",
          foreground: "#000000",
          selectionBackground: "#add6ff",
          selectionForeground: "#000000",
          lineHighlightBackground: "#f5f5f5",
          cursorColor: "#000000",
          indentGuideBackground: "#d3d3d3",
          indentGuideActiveBackground: "#939393",
        },
        activityBar: {
          background: "#2c2c2c",
          foreground: "#ffffff",
          inactiveForeground: "#ffffff66",
          border: "#2c2c2c",
          activeBorder: "#007acc",
          activeBackground: "#2c2c2c",
        },
        sideBar: {
          background: "#f3f3f3",
          foreground: "#000000",
          border: "#e5e5e5",
        },
        sideBarSectionHeader: {
          background: "#e8e8e8",
          foreground: "#333333",
          border: "#007acc",
        },
        panelTitle: {
          background: "#f3f3f3",
          activeForeground: "#333333",
          activeBorder: "#007acc",
          inactiveForeground: "#333333bb",
        },
        statusBar: {
          background: "#007acc",
          foreground: "#ffffff",
          border: "#007acc",
          debuggingBackground: "#cc6633",
          debuggingForeground: "#ffffff",
          noFolderBackground: "#68217a",
          noFolderForeground: "#ffffff",
        },
        titleBar: {
          activeBackground: "#dddddd",
          activeForeground: "#333333",
          inactiveBackground: "#dddddd",
          inactiveForeground: "#333333",
          border: "#e5e5e5",
        },
        panel: {
          background: "#ffffff",
          border: "#e5e5e5",
          dropBorder: "#007acc",
        },
        tab: {
          background: "#ececec",
          activeBackground: "#ffffff",
          activeForeground: "#333333",
          activeBorder: "#007acc",
          activeBorderTop: "#007acc",
          inactiveBackground: "#ececec",
          inactiveForeground: "#333333",
          inactiveModifiedBorder: "#ca5010",
          unfocusedActiveBackground: "#ffffff",
          unfocusedActiveForeground: "#333333",
          unfocusedInactiveBackground: "#ececec",
          unfocusedInactiveForeground: "#717171",
          border: "#e5e5e5",
        },
        input: {
          background: "#ffffff",
          foreground: "#000000",
          border: "#cecece",
          placeholderForeground: "#767676",
        },
        button: {
          background: "#0e639c",
          foreground: "#ffffff",
          hoverBackground: "#1177bb",
          secondaryBackground: "#5f6a79",
          secondaryForeground: "#ffffff",
          secondaryHoverBackground: "#6b7280",
        },
        checkbox: {
          background: "#ffffff",
          foreground: "#000000",
          border: "#cecece",
        },
        badge: {
          background: "#007acc",
          foreground: "#ffffff",
        },
        progressBar: {
          background: "#007acc",
        },
        dropdown: {
          background: "#ffffff",
          foreground: "#000000",
          border: "#cecece",
        },
        list: {
          activeSelectionBackground: "#0060c0",
          activeSelectionForeground: "#ffffff",
          inactiveSelectionBackground: "#e4e6f1",
          inactiveSelectionForeground: "#000000",
          hoverBackground: "#f0f0f0",
          hoverForeground: "#000000",
          focusBackground: "#0060c0",
          focusForeground: "#ffffff",
        },
        scrollbar: {
          shadow: "#e0e0e0",
          sliderBackground: "#0060c0",
          sliderHoverBackground: "#0056b3",
          sliderActiveBackground: "#004a9f",
        },
        breadcrumb: {
          background: "#f8f8f8",
        },
        editorGutter: {
          background: "#ffffff",
        },
        minimap: {
          background: "#f8f8f8",
          sliderBackground: "#007acc60",
          sliderHoverBackground: "#007acc80",
          sliderActiveBackground: "#007acca0",
        },
        syntax: {
          comment: "#008000",
          keyword: "#0000ff",
          string: "#a31515",
          number: "#098658",
          function: "#795e26",
          variable: "#001080",
          type: "#267f99",
          class: "#267f99",
          interface: "#267f99",
          namespace: "#267f99",
          operator: "#000000",
          punctuation: "#000000",
          constant: "#0070c1",
          property: "#001080",
          tag: "#800000",
          attribute: "#ff0000",
        },
      },

      effects: {
        transparency: 0,
        blur: 0,
        animations: false,
        particleEffects: false,
        glowEffect: false,
        scanlines: false,
        crtEffect: false,
      },
    },
  },

  // 💚 Neon Glow - Futuristic cyberpunk theme
  {
    id: "neon-glow",
    name: "💚 Neon Glow",
    description: "Futuristic cyberpunk theme with electric neon vibes",
    category: "cyberpunk",
    preview: "",
    theme: {
      name: "Neon Glow",
      version: "1.0.0",
      author: "VibeStudio",
      description: "Futuristic cyberpunk theme with electric neon vibes",
      created: new Date().toISOString(),
      modified: new Date().toISOString(),

      font: {
        family: "Fira Code, monospace",
        size: 14,
        weight: "normal",
        ligatures: true,
        lineHeight: 1.2,
      },

      cursor: {
        style: "block",
        blinking: true,
        color: "#00ff41",
      },

      colors: {
        background: "#0a0a0a",
        foreground: "#00ff41",
        selection: "#00ff41",
        selectionBackground: "#00ff41",

        ansiBlack: "#0a0a0a",
        ansiRed: "#ff0040",
        ansiGreen: "#00ff41",
        ansiYellow: "#ffff00",
        ansiBlue: "#004cff",
        ansiMagenta: "#ff00ff",
        ansiCyan: "#00ffff",
        ansiWhite: "#ffffff",
        ansiBrightBlack: "#666666",
        ansiBrightRed: "#ff4069",
        ansiBrightGreen: "#00ff41",
        ansiBrightYellow: "#ffff55",
        ansiBrightBlue: "#0066ff",
        ansiBrightMagenta: "#ff55ff",
        ansiBrightCyan: "#55ffff",
        ansiBrightWhite: "#ffffff",

        border: "#003300",
        tab: {
          activeForeground: "#00ff41",
          activeBackground: "#1a1a1a",
          inactiveForeground: "#00cc33",
          inactiveBackground: "#0a0a0a",
          border: "#003300",
        },
      },

      integration: {
        applyToEditor: true,
        applyToTerminal: true,
        applyToWorkbench: true,
      },

      editorTheme: {
        editor: {
          background: "#0a0a0a",
          foreground: "#00ff41",
          selectionBackground: "#00ff41",
          selectionForeground: "#000000",
          lineHighlightBackground: "#1a1a1a",
          cursorColor: "#00ff41",
          indentGuideBackground: "#003300",
          indentGuideActiveBackground: "#00ff41",
        },
        activityBar: {
          background: "#000000",
          foreground: "#00ff41",
          inactiveForeground: "#00cc33",
          border: "#003300",
          activeBorder: "#ffff00",
          activeBackground: "#1a1a1a",
        },
        sideBar: {
          background: "#0a0a0a",
          foreground: "#00ff41",
          border: "#003300",
        },
        sideBarSectionHeader: {
          background: "#003300",
          foreground: "#ffff00",
          border: "#00ff41",
        },
        panelTitle: {
          background: "#000000",
          activeForeground: "#00ff41",
          activeBorder: "#ffff00",
          inactiveForeground: "#00cc33",
        },
        statusBar: {
          background: "#00ff41",
          foreground: "#000000",
          border: "#00ff41",
          debuggingBackground: "#ff0040",
          debuggingForeground: "#ffffff",
          noFolderBackground: "#004cff",
          noFolderForeground: "#ffffff",
        },
        titleBar: {
          activeBackground: "#000000",
          activeForeground: "#00ff41",
          inactiveBackground: "#000000",
          inactiveForeground: "#00cc33",
          border: "#003300",
        },
        panel: {
          background: "#0a0a0a",
          border: "#003300",
          dropBorder: "#00ff41",
        },
        tab: {
          background: "#001100",
          activeBackground: "#0a0a0a",
          activeForeground: "#00ff41",
          activeBorder: "#ffff00",
          activeBorderTop: "#ffff00",
          inactiveBackground: "#1a1a1a",
          inactiveForeground: "#00cc33",
          inactiveModifiedBorder: "#ff00ff",
          unfocusedActiveBackground: "#1a1a1a",
          unfocusedActiveForeground: "#00cc33",
          unfocusedInactiveBackground: "#000000",
          unfocusedInactiveForeground: "#009922",
          border: "#003300",
        },
        input: {
          background: "#1a1a1a",
          foreground: "#00ff41",
          border: "#003300",
          placeholderForeground: "#00cc33",
        },
        button: {
          background: "#00ff41",
          foreground: "#000000",
          hoverBackground: "#00cc33",
          secondaryBackground: "#003300",
          secondaryForeground: "#00ff41",
          secondaryHoverBackground: "#006600",
        },
        checkbox: {
          background: "#1a1a1a",
          foreground: "#00ff41",
          border: "#003300",
        },
        badge: {
          background: "#ffff00",
          foreground: "#000000",
        },
        progressBar: {
          background: "#00ff41",
        },
        dropdown: {
          background: "#1a1a1a",
          foreground: "#00ff41",
          border: "#003300",
        },
        list: {
          activeSelectionBackground: "#00ff41",
          activeSelectionForeground: "#000000",
          inactiveSelectionBackground: "#003300",
          inactiveSelectionForeground: "#00ff41",
          hoverBackground: "#1a1a1a",
          hoverForeground: "#00ff41",
          focusBackground: "#00ff41",
          focusForeground: "#000000",
        },
        scrollbar: {
          shadow: "#000000",
          sliderBackground: "#00ff41",
          sliderHoverBackground: "#00cc33",
          sliderActiveBackground: "#009926",
        },
        breadcrumb: {
          background: "#0a0a0a",
        },
        editorGutter: {
          background: "#0a0a0a",
        },
        minimap: {
          background: "#001100",
          sliderBackground: "#007acc60",
          sliderHoverBackground: "#007acc80",
          sliderActiveBackground: "#007acca0",
        },
        syntax: {
          comment: "#00cc33",
          keyword: "#00ff41",
          string: "#ffff00",
          number: "#ff00ff",
          function: "#00ffff",
          variable: "#00ff41",
          type: "#004cff",
          class: "#00ff41",
          interface: "#00ffff",
          namespace: "#ff00ff",
          operator: "#00ff41",
          punctuation: "#00ff41",
          constant: "#ffff00",
          property: "#00ff41",
          tag: "#00ff41",
          attribute: "#ffff00",
        },
      },

      effects: {
        transparency: 10,
        blur: 5,
        animations: true,
        particleEffects: true,
        glowEffect: true,
        scanlines: true,
        crtEffect: false,
      },
    },
  },

  // 📺 Retro CRT - Vintage terminal aesthetic
  {
    id: "retro-crt",
    name: "📺 Retro CRT",
    description: "Vintage terminal aesthetic with authentic CRT monitor vibes",
    category: "retro",
    preview: "",
    theme: {
      name: "Retro CRT",
      version: "1.0.0",
      author: "VibeStudio",
      description: "Vintage terminal aesthetic with authentic CRT monitor vibes",
      created: new Date().toISOString(),
      modified: new Date().toISOString(),

      font: {
        family: "Courier New, monospace",
        size: 14,
        weight: "normal",
        ligatures: false,
        lineHeight: 1.2,
      },

      cursor: {
        style: "block",
        blinking: true,
        color: "#00ff00",
      },

      colors: {
        background: "#001100",
        foreground: "#00ff00",
        selection: "#003300",
        selectionBackground: "#003300",

        ansiBlack: "#001100",
        ansiRed: "#ff0000",
        ansiGreen: "#00ff00",
        ansiYellow: "#ffff00",
        ansiBlue: "#0000ff",
        ansiMagenta: "#ff00ff",
        ansiCyan: "#00ffff",
        ansiWhite: "#ffffff",
        ansiBrightBlack: "#555555",
        ansiBrightRed: "#ff5555",
        ansiBrightGreen: "#55ff55",
        ansiBrightYellow: "#ffff55",
        ansiBrightBlue: "#5555ff",
        ansiBrightMagenta: "#ff55ff",
        ansiBrightCyan: "#55ffff",
        ansiBrightWhite: "#ffffff",

        border: "#003300",
        tab: {
          activeForeground: "#00ff00",
          activeBackground: "#002200",
          inactiveForeground: "#00cc00",
          inactiveBackground: "#001100",
          border: "#003300",
        },
      },

      integration: {
        applyToEditor: true,
        applyToTerminal: true,
        applyToWorkbench: true,
      },

      editorTheme: {
        editor: {
          background: "#001100",
          foreground: "#00ff00",
          selectionBackground: "#003300",
          selectionForeground: "#00ff00",
          lineHighlightBackground: "#002200",
          cursorColor: "#00ff00",
          indentGuideBackground: "#003300",
          indentGuideActiveBackground: "#00ff00",
        },
        activityBar: {
          background: "#000000",
          foreground: "#00ff00",
          inactiveForeground: "#00cc00",
          border: "#003300",
          activeBorder: "#ffff00",
          activeBackground: "#002200",
        },
        sideBar: {
          background: "#001100",
          foreground: "#00ff00",
          border: "#003300",
        },
        sideBarSectionHeader: {
          background: "#002200",
          foreground: "#ffff00",
          border: "#00ff00",
        },
        panelTitle: {
          background: "#000000",
          activeForeground: "#00ff00",
          activeBorder: "#ffff00",
          inactiveForeground: "#00cc00",
        },
        statusBar: {
          background: "#00ff00",
          foreground: "#000000",
          border: "#00ff00",
          debuggingBackground: "#ffff00",
          debuggingForeground: "#000000",
          noFolderBackground: "#ff0000",
          noFolderForeground: "#ffffff",
        },
        titleBar: {
          activeBackground: "#000000",
          activeForeground: "#00ff00",
          inactiveBackground: "#001100",
          inactiveForeground: "#00cc00",
          border: "#003300",
        },
        panel: {
          background: "#001100",
          border: "#003300",
          dropBorder: "#00ff00",
        },
        tab: {
          background: "#000000",
          activeBackground: "#001100",
          activeForeground: "#00ff00",
          activeBorder: "#ffff00",
          activeBorderTop: "#ffff00",
          inactiveBackground: "#002200",
          inactiveForeground: "#00cc00",
          inactiveModifiedBorder: "#ff0000",
          unfocusedActiveBackground: "#002200",
          unfocusedActiveForeground: "#00cc00",
          unfocusedInactiveBackground: "#000000",
          unfocusedInactiveForeground: "#008800",
          border: "#003300",
        },
        input: {
          background: "#002200",
          foreground: "#00ff00",
          border: "#003300",
          placeholderForeground: "#00cc00",
        },
        button: {
          background: "#00ff00",
          foreground: "#000000",
          hoverBackground: "#00cc00",
          secondaryBackground: "#003300",
          secondaryForeground: "#00ff00",
          secondaryHoverBackground: "#006600",
        },
        checkbox: {
          background: "#002200",
          foreground: "#00ff00",
          border: "#003300",
        },
        badge: {
          background: "#ffff00",
          foreground: "#000000",
        },
        progressBar: {
          background: "#00ff00",
        },
        dropdown: {
          background: "#002200",
          foreground: "#00ff00",
          border: "#003300",
        },
        list: {
          activeSelectionBackground: "#00ff00",
          activeSelectionForeground: "#000000",
          inactiveSelectionBackground: "#003300",
          inactiveSelectionForeground: "#00ff00",
          hoverBackground: "#002200",
          hoverForeground: "#00ff00",
          focusBackground: "#00ff00",
          focusForeground: "#000000",
        },
        scrollbar: {
          shadow: "#000000",
          sliderBackground: "#00ff00",
          sliderHoverBackground: "#00cc00",
          sliderActiveBackground: "#009900",
        },
        breadcrumb: {
          background: "#001100",
        },
        editorGutter: {
          background: "#001100",
        },
        minimap: {
          background: "#000000",
          sliderBackground: "#007acc60",
          sliderHoverBackground: "#007acc80",
          sliderActiveBackground: "#007acca0",
        },
        syntax: {
          comment: "#00cc00",
          keyword: "#00ff00",
          string: "#ffff00",
          number: "#ff00ff",
          function: "#00ffff",
          variable: "#00ff00",
          type: "#0000ff",
          class: "#00ff00",
          interface: "#00ffff",
          namespace: "#ff00ff",
          operator: "#00ff00",
          punctuation: "#00ff00",
          constant: "#ffff00",
          property: "#00ff00",
          tag: "#00ff00",
          attribute: "#ffff00",
        },
      },

      effects: {
        transparency: 0,
        blur: 0,
        animations: true,
        particleEffects: false,
        glowEffect: true,
        scanlines: true,
        crtEffect: true,
      },
    },
  },

  // 🌊 Ocean Breeze - GitHub-inspired blue theme
  {
    id: "ocean-breeze",
    name: "🌊 Ocean Breeze",
    description: "Cool arctic blues with icy white accents",
    category: "modern",
    preview: "",
    theme: {
      name: "Ocean Breeze",
      version: "1.0.0",
      author: "VibeStudio",
      description: "Cool arctic blues with icy white accents",
      created: new Date().toISOString(),
      modified: new Date().toISOString(),

      font: {
        family: "IBM Plex Mono, monospace",
        size: 14,
        weight: "normal",
        ligatures: true,
        lineHeight: 1.2,
      },

      cursor: {
        style: "line",
        blinking: true,
        color: "#0969da",
      },

      colors: {
        background: "#f6f8fa",
        foreground: "#24292f",
        selection: "#0969da40",
        selectionBackground: "#0969da40",

        ansiBlack: "#24292f",
        ansiRed: "#cf222e",
        ansiGreen: "#116329",
        ansiYellow: "#4d2d00",
        ansiBlue: "#0969da",
        ansiMagenta: "#8250df",
        ansiCyan: "#1b7c83",
        ansiWhite: "#f6f8fa",
        ansiBrightBlack: "#656d76",
        ansiBrightRed: "#a40e26",
        ansiBrightGreen: "#1a7f37",
        ansiBrightYellow: "#633c01",
        ansiBrightBlue: "#218bff",
        ansiBrightMagenta: "#a475f9",
        ansiBrightCyan: "#3192aa",
        ansiBrightWhite: "#ffffff",

        border: "#d0d7de",
        tab: {
          activeForeground: "#24292f",
          activeBackground: "#f6f8fa",
          inactiveForeground: "#656d76",
          inactiveBackground: "#ffffff",
          border: "#d0d7de",
        },
      },

      integration: {
        applyToEditor: true,
        applyToTerminal: true,
        applyToWorkbench: true,
      },

      editorTheme: {
        editor: {
          background: "#f6f8fa",
          foreground: "#24292f",
          selectionBackground: "#0969da40",
          selectionForeground: "#24292f",
          lineHighlightBackground: "#f3f4f6",
          cursorColor: "#0969da",
          indentGuideBackground: "#d0d7de",
          indentGuideActiveBackground: "#0969da80",
        },
        activityBar: {
          background: "#ffffff",
          foreground: "#0969da",
          inactiveForeground: "#656d76",
          border: "#d0d7de",
          activeBorder: "#fd7e14",
          activeBackground: "#f6f8fa",
        },
        sideBar: {
          background: "#ffffff",
          foreground: "#24292f",
          border: "#d0d7de",
        },
        sideBarSectionHeader: {
          background: "#f6f8fa",
          foreground: "#0969da",
          border: "#0969da",
        },
        panelTitle: {
          background: "#f6f8fa",
          activeForeground: "#24292f",
          activeBorder: "#fd7e14",
          inactiveForeground: "#656d76",
        },
        statusBar: {
          background: "#0969da",
          foreground: "#ffffff",
          border: "#0969da",
          debuggingBackground: "#cf222e",
          debuggingForeground: "#ffffff",
          noFolderBackground: "#8250df",
          noFolderForeground: "#ffffff",
        },
        titleBar: {
          activeBackground: "#ffffff",
          activeForeground: "#24292f",
          inactiveBackground: "#f6f8fa",
          inactiveForeground: "#656d76",
          border: "#d0d7de",
        },
        panel: {
          background: "#f6f8fa",
          border: "#d0d7de",
          dropBorder: "#0969da",
        },
        tab: {
          background: "#f6f8fa",
          activeBackground: "#f6f8fa",
          activeForeground: "#24292f",
          activeBorder: "#fd7e14",
          activeBorderTop: "#fd7e14",
          inactiveBackground: "#ffffff",
          inactiveForeground: "#656d76",
          inactiveModifiedBorder: "#8250df",
          unfocusedActiveBackground: "#f6f8fa",
          unfocusedActiveForeground: "#656d76",
          unfocusedInactiveBackground: "#ffffff",
          unfocusedInactiveForeground: "#8c959f",
          border: "#d0d7de",
        },
        input: {
          background: "#ffffff",
          foreground: "#24292f",
          border: "#d0d7de",
          placeholderForeground: "#656d76",
        },
        button: {
          background: "#1f883d",
          foreground: "#ffffff",
          hoverBackground: "#1a7f37",
          secondaryBackground: "#f3f4f6",
          secondaryForeground: "#24292f",
          secondaryHoverBackground: "#f9fafb",
        },
        checkbox: {
          background: "#ffffff",
          foreground: "#24292f",
          border: "#d0d7de",
        },
        badge: {
          background: "#0969da",
          foreground: "#ffffff",
        },
        progressBar: {
          background: "#0969da",
        },
        dropdown: {
          background: "#ffffff",
          foreground: "#24292f",
          border: "#d0d7de",
        },
        list: {
          activeSelectionBackground: "#0969da40",
          activeSelectionForeground: "#24292f",
          inactiveSelectionBackground: "#f3f4f620",
          inactiveSelectionForeground: "#24292f",
          hoverBackground: "#f3f4f6",
          hoverForeground: "#24292f",
          focusBackground: "#0969da40",
          focusForeground: "#24292f",
        },
        scrollbar: {
          shadow: "#6e777840",
          sliderBackground: "#0969da",
          sliderHoverBackground: "#0550c7",
          sliderActiveBackground: "#043d9e",
        },
        breadcrumb: {
          background: "#f6f8fa",
        },
        editorGutter: {
          background: "#f6f8fa",
        },
        minimap: {
          background: "#ffffff",
          sliderBackground: "#007acc60",
          sliderHoverBackground: "#007acc80",
          sliderActiveBackground: "#007acca0",
        },
        syntax: {
          comment: "#656d76",
          keyword: "#cf222e",
          string: "#0a3069",
          number: "#0550ae",
          function: "#8250df",
          variable: "#24292f",
          type: "#953800",
          class: "#116329",
          interface: "#1b7c83",
          namespace: "#953800",
          operator: "#cf222e",
          punctuation: "#24292f",
          constant: "#0550ae",
          property: "#24292f",
          tag: "#116329",
          attribute: "#0550ae",
        },
      },

      effects: {
        transparency: 0,
        blur: 0,
        animations: false,
        particleEffects: false,
        glowEffect: false,
        scanlines: false,
        crtEffect: false,
      },
    },
  },
];
