import { ThemePreset } from "../types";

export const cyberpunkPresets: ThemePreset[] = [
  // 🔒 Lock In - Intense late-night grinding theme for focus and danger
  {
    id: "lock-in",
    name: "🔒 Lock In",
    description: "Intense late-night grinding theme for dangerous focus sessions",
    category: "cyberpunk",
    preview: "",
    theme: {
      name: "Lock In",
      version: "1.0.0",
      author: "VibeStudio",
      description: "Intense late-night grinding theme for dangerous focus sessions",
      created: new Date().toISOString(),
      modified: new Date().toISOString(),

      font: {
        family: "JetBrains Mono, Cascadia Code, monospace",
        size: 14,
        weight: "500",
        ligatures: true,
        lineHeight: 1.1,
      },

      cursor: {
        style: "block",
        blinking: true,
        color: "#ff3333",
      },

      colors: {
        background: "#0a0000",
        foreground: "#ff4444",
        selection: "#ff333380",
        selectionBackground: "#ff333380",

        ansiBlack: "#111111",
        ansiRed: "#ff3333",
        ansiGreen: "#33ff33",
        ansiYellow: "#ffaa00",
        ansiBlue: "#3366ff",
        ansiMagenta: "#ff3399",
        ansiCyan: "#33ccff",
        ansiWhite: "#ffffff",
        ansiBrightBlack: "#444444",
        ansiBrightRed: "#ff6666",
        ansiBrightGreen: "#66ff66",
        ansiBrightYellow: "#ffcc33",
        ansiBrightBlue: "#6699ff",
        ansiBrightMagenta: "#ff66cc",
        ansiBrightCyan: "#66ddff",
        ansiBrightWhite: "#ffffff",

        border: "#ff3333",
        tab: {
          activeForeground: "#ff4444",
          activeBackground: "#1a0000",
          inactiveForeground: "#cc3333",
          inactiveBackground: "#0a0000",
          border: "#ff3333",
        },
      },

      integration: {
        applyToEditor: true,
        applyToTerminal: true,
        applyToWorkbench: true,
      },

      editorTheme: {
        editor: {
          background: "#0a0000",
          foreground: "#ff4444",
          selectionBackground: "#ff333340",
          selectionForeground: "#ffffff",
          lineHighlightBackground: "#1a0000",
          cursorColor: "#ff3333",
          indentGuideBackground: "#330000",
          indentGuideActiveBackground: "#ff3333",
        },
        activityBar: {
          background: "#000000",
          foreground: "#ff4444",
          inactiveForeground: "#aa2222",
          border: "#ff3333",
          activeBorder: "#ffaa00",
          activeBackground: "#1a0000",
        },
        sideBar: {
          background: "#050000",
          foreground: "#ff4444",
          border: "#ff3333",
        },
        sideBarSectionHeader: {
          background: "#1a0000",
          foreground: "#ffaa00",
          border: "#ff3333",
        },
        panelTitle: {
          background: "#050000",
          activeForeground: "#ff4444",
          activeBorder: "#ffaa00",
          inactiveForeground: "#aa2222",
        },
        statusBar: {
          background: "#ff3333",
          foreground: "#000000",
          border: "#ff3333",
          debuggingBackground: "#ff6600",
          debuggingForeground: "#000000",
          noFolderBackground: "#cc0000",
          noFolderForeground: "#ffffff",
        },
        titleBar: {
          activeBackground: "#000000",
          activeForeground: "#ff4444",
          inactiveBackground: "#000000",
          inactiveForeground: "#aa2222",
          border: "#ff3333",
        },
        panel: {
          background: "#0a0000",
          border: "#ff3333",
          dropBorder: "#ffaa00",
        },
        tab: {
          background: "#000000",
          activeBackground: "#0a0000",
          activeForeground: "#ff4444",
          activeBorder: "#ffaa00",
          activeBorderTop: "#ffaa00",
          inactiveBackground: "#1a0000",
          inactiveForeground: "#cc3333",
          inactiveModifiedBorder: "#ff6600",
          unfocusedActiveBackground: "#1a0000",
          unfocusedActiveForeground: "#aa2222",
          unfocusedInactiveBackground: "#000000",
          unfocusedInactiveForeground: "#662222",
          border: "#ff3333",
        },
        input: {
          background: "#1a0000",
          foreground: "#ff4444",
          border: "#ff3333",
          placeholderForeground: "#aa2222",
        },
        button: {
          background: "#ff3333",
          foreground: "#000000",
          hoverBackground: "#ff6666",
          secondaryBackground: "#330000",
          secondaryForeground: "#ff4444",
          secondaryHoverBackground: "#660000",
        },
        checkbox: {
          background: "#1a0000",
          foreground: "#ff4444",
          border: "#ff3333",
        },
        badge: {
          background: "#ffaa00",
          foreground: "#000000",
        },
        progressBar: {
          background: "#ff3333",
        },
        dropdown: {
          background: "#1a0000",
          foreground: "#ff4444",
          border: "#ff3333",
        },
        list: {
          activeSelectionBackground: "#ff333360",
          activeSelectionForeground: "#ffffff",
          inactiveSelectionBackground: "#330000",
          inactiveSelectionForeground: "#ff4444",
          hoverBackground: "#1a0000",
          hoverForeground: "#ff4444",
          focusBackground: "#ff333360",
          focusForeground: "#ffffff",
        },
        scrollbar: {
          shadow: "#000000",
        },
        syntax: {
          comment: "#aa2222",
          keyword: "#ff3333",
          string: "#ffaa00",
          number: "#ff6600",
          function: "#ff9999",
          variable: "#ff4444",
          type: "#ff6666",
          class: "#ff3333",
          interface: "#ffaa00",
          namespace: "#ff6600",
          operator: "#ff3333",
          punctuation: "#ff4444",
          constant: "#ffaa00",
          property: "#ff4444",
          tag: "#ff3333",
          attribute: "#ff6666",
        },
      },

      effects: {
        transparency: 5,
        blur: 0,
        animations: true,
        particleEffects: false,
        glowEffect: true,
        scanlines: false,
        crtEffect: false,
      },
    },
  },
  // 💜 Cyberpunk Purple - Neon purples and electric cyberpunk vibes
  {
    id: "cyberpunk-purple",
    name: "💜 Cyberpunk Purple",
    description: "Neon purples and electric cyberpunk vibes",
    category: "cyberpunk",
    preview: "",
    theme: {
      name: "Cyberpunk Purple",
      version: "1.0.0",
      author: "VibeStudio",
      description: "Neon purples and electric cyberpunk vibes",
      created: new Date().toISOString(),
      modified: new Date().toISOString(),

      font: {
        family: "JetBrains Mono, monospace",
        size: 14,
        weight: "normal",
        ligatures: true,
        lineHeight: 1.2,
      },

      cursor: {
        style: "block",
        blinking: true,
        color: "#e100ff",
      },

      colors: {
        background: "#0f0f23",
        foreground: "#e100ff",
        selection: "#e100ff",
        selectionBackground: "#e100ff",

        ansiBlack: "#0f0f23",
        ansiRed: "#ff0040",
        ansiGreen: "#00ff41",
        ansiYellow: "#ffff00",
        ansiBlue: "#004cff",
        ansiMagenta: "#e100ff",
        ansiCyan: "#00ffff",
        ansiWhite: "#ffffff",
        ansiBrightBlack: "#666666",
        ansiBrightRed: "#ff4069",
        ansiBrightGreen: "#00ff41",
        ansiBrightYellow: "#ffff55",
        ansiBrightBlue: "#0066ff",
        ansiBrightMagenta: "#ff55ff",
        ansiBrightCyan: "#55ffff",
        ansiBrightWhite: "#ffffff",

        border: "#3a0ca3",
        tab: {
          activeForeground: "#e100ff",
          activeBackground: "#1a1a3a",
          inactiveForeground: "#9d4edd",
          inactiveBackground: "#0f0f23",
          border: "#3a0ca3",
        },
      },

      integration: {
        applyToEditor: true,
        applyToTerminal: true,
        applyToWorkbench: true,
      },

      editorTheme: {
        editor: {
          background: "#0f0f23",
          foreground: "#e100ff",
          selectionBackground: "#e100ff",
          selectionForeground: "#000000",
          lineHighlightBackground: "#1a1a3a",
          cursorColor: "#e100ff",
          indentGuideBackground: "#3a0ca3",
          indentGuideActiveBackground: "#e100ff",
        },
        activityBar: {
          background: "#000000",
          foreground: "#e100ff",
          inactiveForeground: "#9d4edd",
          border: "#3a0ca3",
          activeBorder: "#ffff00",
          activeBackground: "#1a1a3a",
        },
        sideBar: {
          background: "#0f0f23",
          foreground: "#e100ff",
          border: "#3a0ca3",
        },
        sideBarSectionHeader: {
          background: "#3a0ca3",
          foreground: "#ffff00",
          border: "#e100ff",
        },
        panelTitle: {
          background: "#0f0f23",
          activeForeground: "#e100ff",
          activeBorder: "#ffff00",
          inactiveForeground: "#9d4edd",
        },
        statusBar: {
          background: "#e100ff",
          foreground: "#000000",
          border: "#e100ff",
          debuggingBackground: "#ff0040",
          debuggingForeground: "#ffffff",
          noFolderBackground: "#004cff",
          noFolderForeground: "#ffffff",
        },
        titleBar: {
          activeBackground: "#000000",
          activeForeground: "#e100ff",
          inactiveBackground: "#000000",
          inactiveForeground: "#9d4edd",
          border: "#3a0ca3",
        },
        panel: {
          background: "#0f0f23",
          border: "#3a0ca3",
          dropBorder: "#e100ff",
        },
        tab: {
          background: "#0a0a1a",
          activeBackground: "#0f0f23",
          activeForeground: "#e100ff",
          activeBorder: "#ffff00",
          activeBorderTop: "#ffff00",
          inactiveBackground: "#1a1a3a",
          inactiveForeground: "#9d4edd",
          inactiveModifiedBorder: "#ff00ff",
          unfocusedActiveBackground: "#1a1a3a",
          unfocusedActiveForeground: "#9d4edd",
          unfocusedInactiveBackground: "#000000",
          unfocusedInactiveForeground: "#7209b7",
          border: "#3a0ca3",
        },
        input: {
          background: "#1a1a3a",
          foreground: "#e100ff",
          border: "#3a0ca3",
          placeholderForeground: "#9d4edd",
        },
        button: {
          background: "#e100ff",
          foreground: "#000000",
          hoverBackground: "#c77dff",
          secondaryBackground: "#3a0ca3",
          secondaryForeground: "#e100ff",
          secondaryHoverBackground: "#7209b7",
        },
        checkbox: {
          background: "#1a1a3a",
          foreground: "#e100ff",
          border: "#3a0ca3",
        },
        badge: {
          background: "#ffff00",
          foreground: "#000000",
        },
        progressBar: {
          background: "#e100ff",
        },
        dropdown: {
          background: "#1a1a3a",
          foreground: "#e100ff",
          border: "#3a0ca3",
        },
        list: {
          activeSelectionBackground: "#e100ff",
          activeSelectionForeground: "#000000",
          inactiveSelectionBackground: "#3a0ca3",
          inactiveSelectionForeground: "#e100ff",
          hoverBackground: "#1a1a3a",
          hoverForeground: "#e100ff",
          focusBackground: "#e100ff",
          focusForeground: "#000000",
        },
        scrollbar: {
          shadow: "#000000",
        },
        syntax: {
          comment: "#9d4edd",
          keyword: "#e100ff",
          string: "#ffff00",
          number: "#ff00ff",
          function: "#00ffff",
          variable: "#e100ff",
          type: "#004cff",
          class: "#e100ff",
          interface: "#00ffff",
          namespace: "#ff00ff",
          operator: "#e100ff",
          punctuation: "#e100ff",
          constant: "#ffff00",
          property: "#e100ff",
          tag: "#e100ff",
          attribute: "#ffff00",
        },
      },

      effects: {
        transparency: 15,
        blur: 5,
        animations: true,
        particleEffects: true,
        glowEffect: true,
        scanlines: true,
        crtEffect: false,
      },
    },
  },

  // 🌴 Miami Vice - 80s neon pink and cyan vibes
  {
    id: "miami-vice",
    name: "🌴 Miami Vice",
    description: "80s neon pink and cyan Miami vibes",
    category: "neon",
    preview: "",
    theme: {
      name: "Miami Vice",
      version: "1.0.0",
      author: "VibeStudio",
      description: "80s neon pink and cyan Miami vibes",
      created: new Date().toISOString(),
      modified: new Date().toISOString(),

      font: {
        family: "Orbitron, monospace",
        size: 14,
        weight: "normal",
        ligatures: false,
        lineHeight: 1.2,
      },

      cursor: {
        style: "block",
        blinking: true,
        color: "#ff0080",
      },

      colors: {
        background: "#000814",
        foreground: "#ff0080",
        selection: "#00ffff",
        selectionBackground: "#00ffff",

        ansiBlack: "#000814",
        ansiRed: "#ff0080",
        ansiGreen: "#00ffff",
        ansiYellow: "#ffff00",
        ansiBlue: "#0077be",
        ansiMagenta: "#ff0080",
        ansiCyan: "#00ffff",
        ansiWhite: "#ffffff",
        ansiBrightBlack: "#001d3d",
        ansiBrightRed: "#ff6bb3",
        ansiBrightGreen: "#80ffff",
        ansiBrightYellow: "#ffff80",
        ansiBrightBlue: "#40a6ff",
        ansiBrightMagenta: "#ff80c0",
        ansiBrightCyan: "#80ffff",
        ansiBrightWhite: "#ffffff",

        border: "#003566",
        tab: {
          activeForeground: "#ff0080",
          activeBackground: "#001d3d",
          inactiveForeground: "#0077be",
          inactiveBackground: "#000814",
          border: "#003566",
        },
      },

      integration: {
        applyToEditor: true,
        applyToTerminal: true,
        applyToWorkbench: true,
      },

      editorTheme: {
        editor: {
          background: "#000814",
          foreground: "#ff0080",
          selectionBackground: "#00ffff",
          selectionForeground: "#000000",
          lineHighlightBackground: "#001d3d",
          cursorColor: "#ff0080",
          indentGuideBackground: "#003566",
          indentGuideActiveBackground: "#ff0080",
        },
        activityBar: {
          background: "#000000",
          foreground: "#ff0080",
          inactiveForeground: "#0077be",
          border: "#003566",
          activeBorder: "#00ffff",
          activeBackground: "#001d3d",
        },
        sideBar: {
          background: "#000814",
          foreground: "#ff0080",
          border: "#003566",
        },
        sideBarSectionHeader: {
          background: "#003566",
          foreground: "#00ffff",
          border: "#ff0080",
        },
        panelTitle: {
          background: "#000814",
          activeForeground: "#ff0080",
          activeBorder: "#00ffff",
          inactiveForeground: "#0077be",
        },
        statusBar: {
          background: "#ff0080",
          foreground: "#000000",
          border: "#ff0080",
          debuggingBackground: "#00ffff",
          debuggingForeground: "#000000",
          noFolderBackground: "#0077be",
          noFolderForeground: "#ffffff",
        },
        titleBar: {
          activeBackground: "#000000",
          activeForeground: "#ff0080",
          inactiveBackground: "#000814",
          inactiveForeground: "#0077be",
          border: "#003566",
        },
        panel: {
          background: "#000814",
          border: "#003566",
          dropBorder: "#ff0080",
        },
        tab: {
          background: "#000411",
          activeBackground: "#000814",
          activeForeground: "#ff0080",
          activeBorder: "#00ffff",
          activeBorderTop: "#00ffff",
          inactiveBackground: "#001d3d",
          inactiveForeground: "#0077be",
          inactiveModifiedBorder: "#ffff00",
          unfocusedActiveBackground: "#000814",
          unfocusedActiveForeground: "#0077be",
          unfocusedInactiveBackground: "#000000",
          unfocusedInactiveForeground: "#003566",
          border: "#003566",
        },
        input: {
          background: "#001d3d",
          foreground: "#ff0080",
          border: "#003566",
          placeholderForeground: "#0077be",
        },
        button: {
          background: "#ff0080",
          foreground: "#000000",
          hoverBackground: "#ff6bb3",
          secondaryBackground: "#003566",
          secondaryForeground: "#ff0080",
          secondaryHoverBackground: "#0077be",
        },
        checkbox: {
          background: "#001d3d",
          foreground: "#ff0080",
          border: "#003566",
        },
        badge: {
          background: "#00ffff",
          foreground: "#000000",
        },
        progressBar: {
          background: "#ff0080",
        },
        dropdown: {
          background: "#001d3d",
          foreground: "#ff0080",
          border: "#003566",
        },
        list: {
          activeSelectionBackground: "#ff0080",
          activeSelectionForeground: "#000000",
          inactiveSelectionBackground: "#003566",
          inactiveSelectionForeground: "#ff0080",
          hoverBackground: "#001d3d",
          hoverForeground: "#ff0080",
          focusBackground: "#ff0080",
          focusForeground: "#000000",
        },
        scrollbar: {
          shadow: "#000000",
        },
        syntax: {
          comment: "#0077be",
          keyword: "#ff0080",
          string: "#00ffff",
          number: "#ffff00",
          function: "#ff6bb3",
          variable: "#ff0080",
          type: "#0077be",
          class: "#ff0080",
          interface: "#00ffff",
          namespace: "#ff6bb3",
          operator: "#ff0080",
          punctuation: "#ff0080",
          constant: "#ffff00",
          property: "#ff0080",
          tag: "#ff0080",
          attribute: "#00ffff",
        },
      },

      effects: {
        transparency: 20,
        blur: 8,
        animations: true,
        particleEffects: true,
        glowEffect: true,
        scanlines: true,
        crtEffect: true,
      },
    },
  },

  // 🌊 Vaporwave - Retro aesthetic with purple and pink vibes
  {
    id: "vaporwave",
    name: "🌊 Vaporwave",
    description: "Retro aesthetic with purple and pink vibes",
    category: "neon",
    preview: "",
    theme: {
      name: "Vaporwave",
      version: "1.0.0",
      author: "VibeStudio",
      description: "Retro aesthetic with purple and pink vibes",
      created: new Date().toISOString(),
      modified: new Date().toISOString(),

      font: {
        family: "Major Mono Display, monospace",
        size: 14,
        weight: "normal",
        ligatures: false,
        lineHeight: 1.3,
      },

      cursor: {
        style: "line",
        blinking: true,
        color: "#ff007f",
      },

      colors: {
        background: "#120458",
        foreground: "#ff007f",
        selection: "#00ffff",
        selectionBackground: "#00ffff",

        ansiBlack: "#120458",
        ansiRed: "#ff007f",
        ansiGreen: "#00ffff",
        ansiYellow: "#ffff00",
        ansiBlue: "#7209b7",
        ansiMagenta: "#ff007f",
        ansiCyan: "#00ffff",
        ansiWhite: "#ffffff",
        ansiBrightBlack: "#2d1b69",
        ansiBrightRed: "#ff69b4",
        ansiBrightGreen: "#00ffff",
        ansiBrightYellow: "#ffff80",
        ansiBrightBlue: "#9d4edd",
        ansiBrightMagenta: "#ff80bf",
        ansiBrightCyan: "#80ffff",
        ansiBrightWhite: "#ffffff",

        border: "#3c096c",
        tab: {
          activeForeground: "#ff007f",
          activeBackground: "#240090",
          inactiveForeground: "#7209b7",
          inactiveBackground: "#120458",
          border: "#3c096c",
        },
      },

      integration: {
        applyToEditor: true,
        applyToTerminal: true,
        applyToWorkbench: true,
      },

      editorTheme: {
        editor: {
          background: "#120458",
          foreground: "#ff007f",
          selectionBackground: "#00ffff",
          selectionForeground: "#000000",
          lineHighlightBackground: "#240090",
          cursorColor: "#ff007f",
          indentGuideBackground: "#3c096c",
          indentGuideActiveBackground: "#ff007f",
        },
        activityBar: {
          background: "#0f0419",
          foreground: "#ff007f",
          inactiveForeground: "#7209b7",
          border: "#3c096c",
          activeBorder: "#00ffff",
          activeBackground: "#240090",
        },
        sideBar: {
          background: "#120458",
          foreground: "#ff007f",
          border: "#3c096c",
        },
        sideBarSectionHeader: {
          background: "#240090",
          foreground: "#00ffff",
          border: "#ff007f",
        },
        panelTitle: {
          background: "#120458",
          activeForeground: "#ff007f",
          activeBorder: "#00ffff",
          inactiveForeground: "#7209b7",
        },
        statusBar: {
          background: "#ff007f",
          foreground: "#000000",
          border: "#ff007f",
          debuggingBackground: "#00ffff",
          debuggingForeground: "#000000",
          noFolderBackground: "#7209b7",
          noFolderForeground: "#ffffff",
        },
        titleBar: {
          activeBackground: "#0f0419",
          activeForeground: "#ff007f",
          inactiveBackground: "#120458",
          inactiveForeground: "#7209b7",
          border: "#3c096c",
        },
        panel: {
          background: "#120458",
          border: "#3c096c",
          dropBorder: "#ff007f",
        },
        tab: {
          background: "#0f0419",
          activeBackground: "#120458",
          activeForeground: "#ff007f",
          activeBorder: "#00ffff",
          activeBorderTop: "#00ffff",
          inactiveBackground: "#240090",
          inactiveForeground: "#7209b7",
          inactiveModifiedBorder: "#ffff00",
          unfocusedActiveBackground: "#240090",
          unfocusedActiveForeground: "#7209b7",
          unfocusedInactiveBackground: "#0f0419",
          unfocusedInactiveForeground: "#5a189a",
          border: "#3c096c",
        },
        input: {
          background: "#240090",
          foreground: "#ff007f",
          border: "#3c096c",
          placeholderForeground: "#7209b7",
        },
        button: {
          background: "#ff007f",
          foreground: "#000000",
          hoverBackground: "#ff69b4",
          secondaryBackground: "#3c096c",
          secondaryForeground: "#ff007f",
          secondaryHoverBackground: "#7209b7",
        },
        checkbox: {
          background: "#240090",
          foreground: "#ff007f",
          border: "#3c096c",
        },
        badge: {
          background: "#00ffff",
          foreground: "#000000",
        },
        progressBar: {
          background: "#ff007f",
        },
        dropdown: {
          background: "#240090",
          foreground: "#ff007f",
          border: "#3c096c",
        },
        list: {
          activeSelectionBackground: "#ff007f",
          activeSelectionForeground: "#000000",
          inactiveSelectionBackground: "#3c096c",
          inactiveSelectionForeground: "#ff007f",
          hoverBackground: "#240090",
          hoverForeground: "#ff007f",
          focusBackground: "#ff007f",
          focusForeground: "#000000",
        },
        scrollbar: {
          shadow: "#0f0419",
        },
        syntax: {
          comment: "#7209b7",
          keyword: "#ff007f",
          string: "#00ffff",
          number: "#ffff00",
          function: "#ff69b4",
          variable: "#ff007f",
          type: "#7209b7",
          class: "#ff007f",
          interface: "#00ffff",
          namespace: "#ff69b4",
          operator: "#ff007f",
          punctuation: "#ff007f",
          constant: "#ffff00",
          property: "#ff007f",
          tag: "#ff007f",
          attribute: "#00ffff",
        },
      },

      effects: {
        transparency: 15,
        blur: 6,
        animations: true,
        particleEffects: true,
        glowEffect: true,
        scanlines: true,
        crtEffect: true,
      },
    },
  },

  // ⚡ Electric Lime - High energy neon green vibes
  {
    id: "electric-lime",
    name: "⚡ Electric Lime",
    description: "High energy neon green vibes",
    category: "neon",
    preview: "",
    theme: {
      name: "Electric Lime",
      version: "1.0.0",
      author: "VibeStudio",
      description: "High energy neon green vibes",
      created: new Date().toISOString(),
      modified: new Date().toISOString(),

      font: {
        family: "Space Mono, monospace",
        size: 14,
        weight: "bold",
        ligatures: false,
        lineHeight: 1.2,
      },

      cursor: {
        style: "block",
        blinking: true,
        color: "#ccff00",
      },

      colors: {
        background: "#001100",
        foreground: "#ccff00",
        selection: "#ccff00",
        selectionBackground: "#ccff00",

        ansiBlack: "#001100",
        ansiRed: "#ff4400",
        ansiGreen: "#ccff00",
        ansiYellow: "#ffff00",
        ansiBlue: "#0088ff",
        ansiMagenta: "#ff00cc",
        ansiCyan: "#00ffcc",
        ansiWhite: "#ffffff",
        ansiBrightBlack: "#004400",
        ansiBrightRed: "#ff6600",
        ansiBrightGreen: "#ccff00",
        ansiBrightYellow: "#ffff44",
        ansiBrightBlue: "#44aaff",
        ansiBrightMagenta: "#ff44cc",
        ansiBrightCyan: "#44ffcc",
        ansiBrightWhite: "#ffffff",

        border: "#004400",
        tab: {
          activeForeground: "#ccff00",
          activeBackground: "#002200",
          inactiveForeground: "#88cc00",
          inactiveBackground: "#001100",
          border: "#004400",
        },
      },

      integration: {
        applyToEditor: true,
        applyToTerminal: true,
        applyToWorkbench: true,
      },

      editorTheme: {
        editor: {
          background: "#001100",
          foreground: "#ccff00",
          selectionBackground: "#ccff00",
          selectionForeground: "#000000",
          lineHighlightBackground: "#002200",
          cursorColor: "#ccff00",
          indentGuideBackground: "#004400",
          indentGuideActiveBackground: "#ccff00",
        },
        activityBar: {
          background: "#000000",
          foreground: "#ccff00",
          inactiveForeground: "#88cc00",
          border: "#004400",
          activeBorder: "#ffff00",
          activeBackground: "#002200",
        },
        sideBar: {
          background: "#001100",
          foreground: "#ccff00",
          border: "#004400",
        },
        sideBarSectionHeader: {
          background: "#004400",
          foreground: "#ffff00",
          border: "#ccff00",
        },
        panelTitle: {
          background: "#001100",
          activeForeground: "#ccff00",
          activeBorder: "#ffff00",
          inactiveForeground: "#88cc00",
        },
        statusBar: {
          background: "#ccff00",
          foreground: "#000000",
          border: "#ccff00",
          debuggingBackground: "#ff4400",
          debuggingForeground: "#ffffff",
          noFolderBackground: "#0088ff",
          noFolderForeground: "#ffffff",
        },
        titleBar: {
          activeBackground: "#000000",
          activeForeground: "#ccff00",
          inactiveBackground: "#001100",
          inactiveForeground: "#88cc00",
          border: "#004400",
        },
        panel: {
          background: "#001100",
          border: "#004400",
          dropBorder: "#ccff00",
        },
        tab: {
          background: "#000000",
          activeBackground: "#002200",
          activeForeground: "#ccff00",
          activeBorder: "#ffff00",
          activeBorderTop: "#ffff00",
          inactiveBackground: "#001100",
          inactiveForeground: "#88cc00",
          inactiveModifiedBorder: "#ff00cc",
          unfocusedActiveBackground: "#001100",
          unfocusedActiveForeground: "#88cc00",
          unfocusedInactiveBackground: "#000000",
          unfocusedInactiveForeground: "#559900",
          border: "#004400",
        },
        input: {
          background: "#002200",
          foreground: "#ccff00",
          border: "#004400",
          placeholderForeground: "#88cc00",
        },
        button: {
          background: "#ccff00",
          foreground: "#000000",
          hoverBackground: "#aaee00",
          secondaryBackground: "#004400",
          secondaryForeground: "#ccff00",
          secondaryHoverBackground: "#006600",
        },
        checkbox: {
          background: "#002200",
          foreground: "#ccff00",
          border: "#004400",
        },
        badge: {
          background: "#ffff00",
          foreground: "#000000",
        },
        progressBar: {
          background: "#ccff00",
        },
        dropdown: {
          background: "#002200",
          foreground: "#ccff00",
          border: "#004400",
        },
        list: {
          activeSelectionBackground: "#ccff00",
          activeSelectionForeground: "#000000",
          inactiveSelectionBackground: "#004400",
          inactiveSelectionForeground: "#ccff00",
          hoverBackground: "#002200",
          hoverForeground: "#ccff00",
          focusBackground: "#ccff00",
          focusForeground: "#000000",
        },
        scrollbar: {
          shadow: "#000000",
        },
        syntax: {
          comment: "#88cc00",
          keyword: "#ccff00",
          string: "#ffff00",
          number: "#ff00cc",
          function: "#00ffcc",
          variable: "#ccff00",
          type: "#0088ff",
          class: "#ccff00",
          interface: "#00ffcc",
          namespace: "#ff00cc",
          operator: "#ccff00",
          punctuation: "#ccff00",
          constant: "#ffff00",
          property: "#ccff00",
          tag: "#ccff00",
          attribute: "#ffff00",
        },
      },

      effects: {
        transparency: 10,
        blur: 4,
        animations: true,
        particleEffects: true,
        glowEffect: true,
        scanlines: false,
        crtEffect: false,
      },
    },
  },

  // 🤖 Robot Matrix - Green matrix code aesthetic
  {
    id: "robot-matrix",
    name: "🤖 Robot Matrix",
    description: "Classic green matrix code aesthetic with digital rain effect",
    category: "cyberpunk",
    preview: "",
    theme: {
      name: "Robot Matrix",
      version: "1.0.0",
      author: "VibeStudio",
      description: "Classic green matrix code aesthetic with digital rain effect",
      created: new Date().toISOString(),
      modified: new Date().toISOString(),

      font: {
        family: "Share Tech Mono, monospace",
        size: 14,
        weight: "normal",
        ligatures: false,
        lineHeight: 1.2,
      },

      cursor: {
        style: "block",
        blinking: true,
        color: "#00ff41",
      },

      colors: {
        background: "#000000",
        foreground: "#00ff41",
        selection: "#003300",
        selectionBackground: "#003300",

        ansiBlack: "#000000",
        ansiRed: "#ff0000",
        ansiGreen: "#00ff41",
        ansiYellow: "#33ff33",
        ansiBlue: "#00cc33",
        ansiMagenta: "#66ff66",
        ansiCyan: "#99ff99",
        ansiWhite: "#ccffcc",
        ansiBrightBlack: "#003300",
        ansiBrightRed: "#ff3333",
        ansiBrightGreen: "#66ff66",
        ansiBrightYellow: "#99ff99",
        ansiBrightBlue: "#33cc66",
        ansiBrightMagenta: "#99ff99",
        ansiBrightCyan: "#ccffcc",
        ansiBrightWhite: "#ffffff",

        border: "#003300",
        tab: {
          activeForeground: "#00ff41",
          activeBackground: "#000000",
          inactiveForeground: "#33ff33",
          inactiveBackground: "#001100",
          border: "#003300",
        },
      },

      integration: {
        applyToEditor: true,
        applyToTerminal: true,
        applyToWorkbench: true,
      },

      editorTheme: {
        editor: {
          background: "#000000",
          foreground: "#00ff41",
          selectionBackground: "#00330080",
          selectionForeground: "#ffffff",
          lineHighlightBackground: "#001100",
          cursorColor: "#00ff41",
          indentGuideBackground: "#003300",
          indentGuideActiveBackground: "#00ff41",
        },
        activityBar: {
          background: "#001100",
          foreground: "#00ff41",
          inactiveForeground: "#33ff33",
          border: "#003300",
          activeBorder: "#00ff41",
          activeBackground: "#000000",
        },
        sideBar: {
          background: "#000000",
          foreground: "#00ff41",
          border: "#003300",
        },
        sideBarSectionHeader: {
          background: "#003300",
          foreground: "#66ff66",
          border: "#00ff41",
        },
        panelTitle: {
          background: "#000000",
          activeForeground: "#00ff41",
          activeBorder: "#00ff41",
          inactiveForeground: "#33ff33",
        },
        statusBar: {
          background: "#00ff41",
          foreground: "#000000",
          border: "#00ff41",
          debuggingBackground: "#66ff66",
          debuggingForeground: "#000000",
          noFolderBackground: "#33ff33",
          noFolderForeground: "#000000",
        },
        titleBar: {
          activeBackground: "#001100",
          activeForeground: "#00ff41",
          inactiveBackground: "#000000",
          inactiveForeground: "#33ff33",
          border: "#003300",
        },
        panel: {
          background: "#000000",
          border: "#003300",
          dropBorder: "#00ff41",
        },
        tab: {
          background: "#000000",
          activeBackground: "#000000",
          activeForeground: "#00ff41",
          activeBorder: "#00ff41",
          activeBorderTop: "#00ff41",
          inactiveBackground: "#001100",
          inactiveForeground: "#33ff33",
          inactiveModifiedBorder: "#66ff66",
          unfocusedActiveBackground: "#001100",
          unfocusedActiveForeground: "#33ff33",
          unfocusedInactiveBackground: "#000000",
          unfocusedInactiveForeground: "#003300",
          border: "#003300",
        },
        input: {
          background: "#001100",
          foreground: "#00ff41",
          border: "#003300",
          placeholderForeground: "#33ff33",
        },
        button: {
          background: "#00ff41",
          foreground: "#000000",
          hoverBackground: "#33ff33",
          secondaryBackground: "#003300",
          secondaryForeground: "#00ff41",
          secondaryHoverBackground: "#006600",
        },
        checkbox: {
          background: "#001100",
          foreground: "#00ff41",
          border: "#003300",
        },
        badge: {
          background: "#00ff41",
          foreground: "#000000",
        },
        progressBar: {
          background: "#00ff41",
        },
        dropdown: {
          background: "#001100",
          foreground: "#00ff41",
          border: "#003300",
        },
        list: {
          activeSelectionBackground: "#00330080",
          activeSelectionForeground: "#ffffff",
          inactiveSelectionBackground: "#003300",
          inactiveSelectionForeground: "#00ff41",
          hoverBackground: "#001100",
          hoverForeground: "#00ff41",
          focusBackground: "#00330080",
          focusForeground: "#ffffff",
        },
        scrollbar: {
          shadow: "#003300",
        },
        syntax: {
          comment: "#33ff33",
          keyword: "#00ff41",
          string: "#66ff66",
          number: "#99ff99",
          function: "#ccffcc",
          variable: "#00ff41",
          type: "#33ff33",
          class: "#66ff66",
          interface: "#99ff99",
          namespace: "#ccffcc",
          operator: "#00ff41",
          punctuation: "#00ff41",
          constant: "#99ff99",
          property: "#00ff41",
          tag: "#66ff66",
          attribute: "#33ff33",
        },
      },

      effects: {
        transparency: 5,
        blur: 1,
        animations: true,
        particleEffects: true,
        glowEffect: true,
        scanlines: true,
        crtEffect: true,
      },
    },
  },

  // 🌈 Digital Prism - Holographic rainbow cyberpunk
  {
    id: "digital-prism",
    name: "🌈 Digital Prism",
    description: "Holographic rainbow cyberpunk with prismatic light effects",
    category: "cyberpunk",
    preview: "",
    theme: {
      name: "Digital Prism",
      version: "1.0.0",
      author: "VibeStudio",
      description: "Holographic rainbow cyberpunk with prismatic light effects",
      created: new Date().toISOString(),
      modified: new Date().toISOString(),

      font: {
        family: "Space Mono, monospace",
        size: 14,
        weight: "normal",
        ligatures: false,
        lineHeight: 1.3,
      },

      cursor: {
        style: "line",
        blinking: true,
        color: "#ff00ff",
      },

      colors: {
        background: "#0a0a0a",
        foreground: "#ffffff",
        selection: "#ff00ff",
        selectionBackground: "#ff00ff",

        ansiBlack: "#0a0a0a",
        ansiRed: "#ff0040",
        ansiGreen: "#40ff40",
        ansiYellow: "#ffff00",
        ansiBlue: "#4040ff",
        ansiMagenta: "#ff40ff",
        ansiCyan: "#40ffff",
        ansiWhite: "#ffffff",
        ansiBrightBlack: "#404040",
        ansiBrightRed: "#ff4080",
        ansiBrightGreen: "#80ff80",
        ansiBrightYellow: "#ffff80",
        ansiBrightBlue: "#8080ff",
        ansiBrightMagenta: "#ff80ff",
        ansiBrightCyan: "#80ffff",
        ansiBrightWhite: "#ffffff",

        border: "#404040",
        tab: {
          activeForeground: "#ffffff",
          activeBackground: "#0a0a0a",
          inactiveForeground: "#ff40ff",
          inactiveBackground: "#202020",
          border: "#404040",
        },
      },

      integration: {
        applyToEditor: true,
        applyToTerminal: true,
        applyToWorkbench: true,
      },

      editorTheme: {
        editor: {
          background: "#0a0a0a",
          foreground: "#ffffff",
          selectionBackground: "#ff00ff80",
          selectionForeground: "#ffffff",
          lineHighlightBackground: "#202020",
          cursorColor: "#ff00ff",
          indentGuideBackground: "#404040",
          indentGuideActiveBackground: "#ff00ff",
        },
        activityBar: {
          background: "#202020",
          foreground: "#ffffff",
          inactiveForeground: "#ff40ff",
          border: "#404040",
          activeBorder: "#ff00ff",
          activeBackground: "#0a0a0a",
        },
        sideBar: {
          background: "#0a0a0a",
          foreground: "#ffffff",
          border: "#404040",
        },
        sideBarSectionHeader: {
          background: "#404040",
          foreground: "#ff00ff",
          border: "#40ffff",
        },
        panelTitle: {
          background: "#0a0a0a",
          activeForeground: "#ffffff",
          activeBorder: "#ff00ff",
          inactiveForeground: "#ff40ff",
        },
        statusBar: {
          background: "#ff00ff",
          foreground: "#0a0a0a",
          border: "#ff00ff",
          debuggingBackground: "#4040ff",
          debuggingForeground: "#ffffff",
          noFolderBackground: "#40ffff",
          noFolderForeground: "#0a0a0a",
        },
        titleBar: {
          activeBackground: "#202020",
          activeForeground: "#ffffff",
          inactiveBackground: "#0a0a0a",
          inactiveForeground: "#ff40ff",
          border: "#404040",
        },
        panel: {
          background: "#0a0a0a",
          border: "#404040",
          dropBorder: "#ff00ff",
        },
        tab: {
          background: "#101010",
          activeBackground: "#0a0a0a",
          activeForeground: "#ffffff",
          activeBorder: "#ff00ff",
          activeBorderTop: "#ff00ff",
          inactiveBackground: "#202020",
          inactiveForeground: "#ff40ff",
          inactiveModifiedBorder: "#40ff40",
          unfocusedActiveBackground: "#202020",
          unfocusedActiveForeground: "#ff40ff",
          unfocusedInactiveBackground: "#0a0a0a",
          unfocusedInactiveForeground: "#404040",
          border: "#404040",
        },
        input: {
          background: "#202020",
          foreground: "#ffffff",
          border: "#404040",
          placeholderForeground: "#ff40ff",
        },
        button: {
          background: "#ff00ff",
          foreground: "#0a0a0a",
          hoverBackground: "#ff40ff",
          secondaryBackground: "#404040",
          secondaryForeground: "#ffffff",
          secondaryHoverBackground: "#606060",
        },
        checkbox: {
          background: "#202020",
          foreground: "#ffffff",
          border: "#404040",
        },
        badge: {
          background: "#ff00ff",
          foreground: "#0a0a0a",
        },
        progressBar: {
          background: "#ff00ff",
        },
        dropdown: {
          background: "#202020",
          foreground: "#ffffff",
          border: "#404040",
        },
        list: {
          activeSelectionBackground: "#ff00ff80",
          activeSelectionForeground: "#ffffff",
          inactiveSelectionBackground: "#404040",
          inactiveSelectionForeground: "#ffffff",
          hoverBackground: "#202020",
          hoverForeground: "#ffffff",
          focusBackground: "#ff00ff80",
          focusForeground: "#ffffff",
        },
        scrollbar: {
          shadow: "#404040",
        },
        syntax: {
          comment: "#ff40ff",
          keyword: "#ff00ff",
          string: "#40ff40",
          number: "#ffff00",
          function: "#4040ff",
          variable: "#ffffff",
          type: "#40ffff",
          class: "#ff0040",
          interface: "#80ffff",
          namespace: "#4040ff",
          operator: "#ff00ff",
          punctuation: "#ffffff",
          constant: "#ffff00",
          property: "#ffffff",
          tag: "#ff0040",
          attribute: "#40ffff",
        },
      },

      effects: {
        transparency: 8,
        blur: 3,
        animations: true,
        particleEffects: true,
        glowEffect: true,
        scanlines: false,
        crtEffect: false,
      },
    },
  },
];
