import { ThemePreset } from "../types";

export const gothicPresets: ThemePreset[] = [
  // 🖤 Gothic Dark - Dark and mysterious gothic vibes
  {
    id: "gothic-dark",
    name: "🖤 Gothic Dark",
    description: "Dark and mysterious gothic vibes",
    category: "gothic",
    preview: "",
    theme: {
      name: "Gothic Dark",
      version: "1.0.0",
      author: "VibeStudio",
      description: "Dark and mysterious gothic vibes",
      created: new Date().toISOString(),
      modified: new Date().toISOString(),

      font: {
        family: "Playfair Display, monospace",
        size: 14,
        weight: "normal",
        ligatures: false,
        lineHeight: 1.3,
      },

      cursor: {
        style: "block",
        blinking: false,
        color: "#8b0000",
      },

      colors: {
        background: "#0d0d0d",
        foreground: "#8b0000",
        selection: "#800080",
        selectionBackground: "#800080",

        ansiBlack: "#0d0d0d",
        ansiRed: "#8b0000",
        ansiGreen: "#2f4f2f",
        ansiYellow: "#daa520",
        ansiBlue: "#191970",
        ansiMagenta: "#800080",
        ansiCyan: "#2f4f4f",
        ansiWhite: "#dcdcdc",
        ansiBrightBlack: "#404040",
        ansiBrightRed: "#dc143c",
        ansiBrightGreen: "#556b2f",
        ansiBrightYellow: "#ffd700",
        ansiBrightBlue: "#4169e1",
        ansiBrightMagenta: "#9370db",
        ansiBrightCyan: "#708090",
        ansiBrightWhite: "#ffffff",

        border: "#2f2f2f",
        tab: {
          activeForeground: "#8b0000",
          activeBackground: "#1a1a1a",
          inactiveForeground: "#696969",
          inactiveBackground: "#0d0d0d",
          border: "#2f2f2f",
        },
      },

      integration: {
        applyToEditor: true,
        applyToTerminal: true,
        applyToWorkbench: true,
      },

      editorTheme: {
        editor: {
          background: "#0d0d0d",
          foreground: "#8b0000",
          selectionBackground: "#800080",
          selectionForeground: "#ffffff",
          lineHighlightBackground: "#1a1a1a",
          cursorColor: "#8b0000",
          indentGuideBackground: "#2f2f2f",
          indentGuideActiveBackground: "#8b0000",
        },
        activityBar: {
          background: "#000000",
          foreground: "#8b0000",
          inactiveForeground: "#696969",
          border: "#2f2f2f",
          activeBorder: "#daa520",
          activeBackground: "#1a1a1a",
        },
        sideBar: {
          background: "#0d0d0d",
          foreground: "#8b0000",
          border: "#2f2f2f",
        },
        sideBarSectionHeader: {
          background: "#1a1a1a",
          foreground: "#8b0000",
          border: "#daa520",
        },
        panelTitle: {
          background: "#0d0d0d",
          activeForeground: "#8b0000",
          activeBorder: "#daa520",
          inactiveForeground: "#696969",
        },
        statusBar: {
          background: "#8b0000",
          foreground: "#ffffff",
          border: "#8b0000",
          debuggingBackground: "#800080",
          debuggingForeground: "#ffffff",
          noFolderBackground: "#191970",
          noFolderForeground: "#ffffff",
        },
        titleBar: {
          activeBackground: "#000000",
          activeForeground: "#8b0000",
          inactiveBackground: "#0d0d0d",
          inactiveForeground: "#696969",
          border: "#2f2f2f",
        },
        panel: {
          background: "#0d0d0d",
          border: "#2f2f2f",
          dropBorder: "#8b0000",
        },
        tab: {
          background: "#000000",
          activeBackground: "#0d0d0d",
          activeForeground: "#8b0000",
          activeBorder: "#daa520",
          activeBorderTop: "#daa520",
          inactiveBackground: "#1a1a1a",
          inactiveForeground: "#696969",
          inactiveModifiedBorder: "#800080",
          unfocusedActiveBackground: "#1a1a1a",
          unfocusedActiveForeground: "#696969",
          unfocusedInactiveBackground: "#000000",
          unfocusedInactiveForeground: "#555555",
          border: "#2f2f2f",
        },
        input: {
          background: "#1a1a1a",
          foreground: "#8b0000",
          border: "#2f2f2f",
          placeholderForeground: "#696969",
        },
        button: {
          background: "#8b0000",
          foreground: "#ffffff",
          hoverBackground: "#dc143c",
          secondaryBackground: "#2f2f2f",
          secondaryForeground: "#8b0000",
          secondaryHoverBackground: "#555555",
        },
        checkbox: {
          background: "#1a1a1a",
          foreground: "#8b0000",
          border: "#2f2f2f",
        },
        badge: {
          background: "#daa520",
          foreground: "#0d0d0d",
        },
        progressBar: {
          background: "#8b0000",
        },
        dropdown: {
          background: "#1a1a1a",
          foreground: "#8b0000",
          border: "#2f2f2f",
        },
        list: {
          activeSelectionBackground: "#8b0000",
          activeSelectionForeground: "#ffffff",
          inactiveSelectionBackground: "#2f2f2f",
          inactiveSelectionForeground: "#8b0000",
          hoverBackground: "#1a1a1a",
          hoverForeground: "#8b0000",
          focusBackground: "#8b0000",
          focusForeground: "#ffffff",
        },
        scrollbar: {
          shadow: "#000000",
          sliderBackground: "#8b0000",
          sliderHoverBackground: "#dc143c",
          sliderActiveBackground: "#ff1744",
        },
        breadcrumb: {
          background: "#1a0000",
        },
        editorGutter: {
          background: "#1a0000",
        },
        minimap: {
          background: "#0d0000",
          sliderBackground: "#8b000060",
          sliderHoverBackground: "#8b000080",
          sliderActiveBackground: "#8b0000a0",
        },
        syntax: {
          comment: "#696969",
          keyword: "#8b0000",
          string: "#daa520",
          number: "#800080",
          function: "#191970",
          variable: "#8b0000",
          type: "#2f4f2f",
          class: "#8b0000",
          interface: "#2f4f4f",
          namespace: "#800080",
          operator: "#8b0000",
          punctuation: "#8b0000",
          constant: "#daa520",
          property: "#8b0000",
          tag: "#8b0000",
          attribute: "#daa520",
        },
      },

      effects: {
        transparency: 20,
        blur: 10,
        animations: true,
        particleEffects: false,
        glowEffect: true,
        scanlines: true,
        crtEffect: false,
      },
    },
  },

  // 🦇 Vampire's Lair - Deep reds and black vampire aesthetic
  {
    id: "vampire-lair",
    name: "🦇 Vampire's Lair",
    description: "Deep reds and black vampire aesthetic with blood-like accents",
    category: "gothic",
    preview: "",
    theme: {
      name: "Vampire's Lair",
      version: "1.0.0",
      author: "VibeStudio",
      description: "Deep reds and black vampire aesthetic with blood-like accents",
      created: new Date().toISOString(),
      modified: new Date().toISOString(),

      font: {
        family: "Crimson Text, monospace",
        size: 14,
        weight: "normal",
        ligatures: false,
        lineHeight: 1.4,
      },

      cursor: {
        style: "block",
        blinking: true,
        color: "#dc143c",
      },

      colors: {
        background: "#0d0d0d",
        foreground: "#dc143c",
        selection: "#800020",
        selectionBackground: "#800020",

        ansiBlack: "#0d0d0d",
        ansiRed: "#dc143c",
        ansiGreen: "#8b0000",
        ansiYellow: "#b22222",
        ansiBlue: "#4b0000",
        ansiMagenta: "#800020",
        ansiCyan: "#a0522d",
        ansiWhite: "#dc143c",
        ansiBrightBlack: "#1a1a1a",
        ansiBrightRed: "#ff0000",
        ansiBrightGreen: "#cd5c5c",
        ansiBrightYellow: "#ff4500",
        ansiBrightBlue: "#8b0000",
        ansiBrightMagenta: "#b22222",
        ansiBrightCyan: "#cd853f",
        ansiBrightWhite: "#ffffff",

        border: "#1a1a1a",
        tab: {
          activeForeground: "#dc143c",
          activeBackground: "#0d0d0d",
          inactiveForeground: "#800020",
          inactiveBackground: "#1a1a1a",
          border: "#1a1a1a",
        },
      },

      integration: {
        applyToEditor: true,
        applyToTerminal: true,
        applyToWorkbench: true,
      },

      editorTheme: {
        editor: {
          background: "#0d0d0d",
          foreground: "#dc143c",
          selectionBackground: "#80002080",
          selectionForeground: "#ffffff",
          lineHighlightBackground: "#1a1a1a",
          cursorColor: "#dc143c",
          indentGuideBackground: "#333333",
          indentGuideActiveBackground: "#dc143c",
        },
        activityBar: {
          background: "#1a1a1a",
          foreground: "#dc143c",
          inactiveForeground: "#800020",
          border: "#333333",
          activeBorder: "#dc143c",
          activeBackground: "#0d0d0d",
        },
        sideBar: {
          background: "#0d0d0d",
          foreground: "#dc143c",
          border: "#333333",
        },
        sideBarSectionHeader: {
          background: "#1a1a1a",
          foreground: "#dc143c",
          border: "#800020",
        },
        panelTitle: {
          background: "#0d0d0d",
          activeForeground: "#dc143c",
          activeBorder: "#dc143c",
          inactiveForeground: "#800020",
        },
        statusBar: {
          background: "#dc143c",
          foreground: "#0d0d0d",
          border: "#dc143c",
          debuggingBackground: "#800020",
          debuggingForeground: "#ffffff",
          noFolderBackground: "#8b0000",
          noFolderForeground: "#ffffff",
        },
        titleBar: {
          activeBackground: "#1a1a1a",
          activeForeground: "#dc143c",
          inactiveBackground: "#0d0d0d",
          inactiveForeground: "#800020",
          border: "#333333",
        },
        panel: {
          background: "#0d0d0d",
          border: "#333333",
          dropBorder: "#dc143c",
        },
        tab: {
          background: "#000000",
          activeBackground: "#0d0d0d",
          activeForeground: "#dc143c",
          activeBorder: "#dc143c",
          activeBorderTop: "#dc143c",
          inactiveBackground: "#1a1a1a",
          inactiveForeground: "#800020",
          inactiveModifiedBorder: "#b22222",
          unfocusedActiveBackground: "#1a1a1a",
          unfocusedActiveForeground: "#800020",
          unfocusedInactiveBackground: "#0d0d0d",
          unfocusedInactiveForeground: "#333333",
          border: "#333333",
        },
        input: {
          background: "#1a1a1a",
          foreground: "#dc143c",
          border: "#333333",
          placeholderForeground: "#800020",
        },
        button: {
          background: "#dc143c",
          foreground: "#0d0d0d",
          hoverBackground: "#ff0000",
          secondaryBackground: "#333333",
          secondaryForeground: "#dc143c",
          secondaryHoverBackground: "#4d4d4d",
        },
        checkbox: {
          background: "#1a1a1a",
          foreground: "#dc143c",
          border: "#333333",
        },
        badge: {
          background: "#dc143c",
          foreground: "#0d0d0d",
        },
        progressBar: {
          background: "#dc143c",
        },
        dropdown: {
          background: "#1a1a1a",
          foreground: "#dc143c",
          border: "#333333",
        },
        list: {
          activeSelectionBackground: "#80002080",
          activeSelectionForeground: "#ffffff",
          inactiveSelectionBackground: "#333333",
          inactiveSelectionForeground: "#dc143c",
          hoverBackground: "#1a1a1a",
          hoverForeground: "#dc143c",
          focusBackground: "#80002080",
          focusForeground: "#ffffff",
        },
        scrollbar: {
          shadow: "#333333",
          sliderBackground: "#dc143c",
          sliderHoverBackground: "#ff1744",
          sliderActiveBackground: "#ff4569",
        },
        breadcrumb: {
          background: "#0d0d0d",
        },
        editorGutter: {
          background: "#0d0d0d",
        },
        minimap: {
          background: "#1a1a1a",
          sliderBackground: "#dc143c60",
          sliderHoverBackground: "#dc143c80",
          sliderActiveBackground: "#dc143ca0",
        },
        syntax: {
          comment: "#800020",
          keyword: "#dc143c",
          string: "#b22222",
          number: "#ff4500",
          function: "#8b0000",
          variable: "#dc143c",
          type: "#cd5c5c",
          class: "#ff0000",
          interface: "#a0522d",
          namespace: "#8b0000",
          operator: "#dc143c",
          punctuation: "#dc143c",
          constant: "#ff4500",
          property: "#dc143c",
          tag: "#ff0000",
          attribute: "#cd5c5c",
        },
      },

      effects: {
        transparency: 8,
        blur: 2,
        animations: true,
        particleEffects: true,
        glowEffect: true,
        scanlines: false,
        crtEffect: false,
      },
    },
  },

  // 🌟 Witch's Potion - Mystical greens and purples
  {
    id: "witch-potion",
    name: "🌟 Witch's Potion",
    description: "Mystical greens and purples with magical potion brewing vibes",
    category: "gothic",
    preview: "",
    theme: {
      name: "Witch's Potion",
      version: "1.0.0",
      author: "VibeStudio",
      description: "Mystical greens and purples with magical potion brewing vibes",
      created: new Date().toISOString(),
      modified: new Date().toISOString(),

      font: {
        family: "Alegreya, monospace",
        size: 14,
        weight: "normal",
        ligatures: false,
        lineHeight: 1.3,
      },

      cursor: {
        style: "line",
        blinking: true,
        color: "#9acd32",
      },

      colors: {
        background: "#0f0f23",
        foreground: "#9acd32",
        selection: "#4b0082",
        selectionBackground: "#4b0082",

        ansiBlack: "#0f0f23",
        ansiRed: "#8b008b",
        ansiGreen: "#9acd32",
        ansiYellow: "#dda0dd",
        ansiBlue: "#483d8b",
        ansiMagenta: "#8b008b",
        ansiCyan: "#7fffd4",
        ansiWhite: "#9acd32",
        ansiBrightBlack: "#2e2e5a",
        ansiBrightRed: "#da70d6",
        ansiBrightGreen: "#adff2f",
        ansiBrightYellow: "#f0e68c",
        ansiBrightBlue: "#6495ed",
        ansiBrightMagenta: "#dda0dd",
        ansiBrightCyan: "#98fb98",
        ansiBrightWhite: "#ffffff",

        border: "#2e2e5a",
        tab: {
          activeForeground: "#9acd32",
          activeBackground: "#0f0f23",
          inactiveForeground: "#8b008b",
          inactiveBackground: "#2e2e5a",
          border: "#2e2e5a",
        },
      },

      integration: {
        applyToEditor: true,
        applyToTerminal: true,
        applyToWorkbench: true,
      },

      editorTheme: {
        editor: {
          background: "#0f0f23",
          foreground: "#9acd32",
          selectionBackground: "#4b008280",
          selectionForeground: "#ffffff",
          lineHighlightBackground: "#2e2e5a",
          cursorColor: "#9acd32",
          indentGuideBackground: "#483d8b",
          indentGuideActiveBackground: "#9acd32",
        },
        activityBar: {
          background: "#2e2e5a",
          foreground: "#9acd32",
          inactiveForeground: "#8b008b",
          border: "#483d8b",
          activeBorder: "#9acd32",
          activeBackground: "#0f0f23",
        },
        sideBar: {
          background: "#0f0f23",
          foreground: "#9acd32",
          border: "#483d8b",
        },
        sideBarSectionHeader: {
          background: "#2e2e5a",
          foreground: "#9acd32",
          border: "#9acd32",
        },
        panelTitle: {
          background: "#0f0f23",
          activeForeground: "#9acd32",
          activeBorder: "#9acd32",
          inactiveForeground: "#8b008b",
        },
        statusBar: {
          background: "#9acd32",
          foreground: "#0f0f23",
          border: "#9acd32",
          debuggingBackground: "#8b008b",
          debuggingForeground: "#ffffff",
          noFolderBackground: "#483d8b",
          noFolderForeground: "#ffffff",
        },
        titleBar: {
          activeBackground: "#2e2e5a",
          activeForeground: "#9acd32",
          inactiveBackground: "#0f0f23",
          inactiveForeground: "#8b008b",
          border: "#483d8b",
        },
        panel: {
          background: "#0f0f23",
          border: "#483d8b",
          dropBorder: "#9acd32",
        },
        tab: {
          background: "#000000",
          activeBackground: "#0f0f23",
          activeForeground: "#9acd32",
          activeBorder: "#9acd32",
          activeBorderTop: "#9acd32",
          inactiveBackground: "#2e2e5a",
          inactiveForeground: "#8b008b",
          inactiveModifiedBorder: "#dda0dd",
          unfocusedActiveBackground: "#2e2e5a",
          unfocusedActiveForeground: "#8b008b",
          unfocusedInactiveBackground: "#0f0f23",
          unfocusedInactiveForeground: "#483d8b",
          border: "#483d8b",
        },
        input: {
          background: "#2e2e5a",
          foreground: "#9acd32",
          border: "#483d8b",
          placeholderForeground: "#8b008b",
        },
        button: {
          background: "#9acd32",
          foreground: "#0f0f23",
          hoverBackground: "#adff2f",
          secondaryBackground: "#483d8b",
          secondaryForeground: "#9acd32",
          secondaryHoverBackground: "#6495ed",
        },
        checkbox: {
          background: "#2e2e5a",
          foreground: "#9acd32",
          border: "#483d8b",
        },
        badge: {
          background: "#9acd32",
          foreground: "#0f0f23",
        },
        progressBar: {
          background: "#9acd32",
        },
        dropdown: {
          background: "#2e2e5a",
          foreground: "#9acd32",
          border: "#483d8b",
        },
        list: {
          activeSelectionBackground: "#4b008280",
          activeSelectionForeground: "#ffffff",
          inactiveSelectionBackground: "#483d8b",
          inactiveSelectionForeground: "#9acd32",
          hoverBackground: "#2e2e5a",
          hoverForeground: "#9acd32",
          focusBackground: "#4b008280",
          focusForeground: "#ffffff",
        },
        scrollbar: {
          shadow: "#483d8b",
          sliderBackground: "#9acd32",
          sliderHoverBackground: "#adff2f",
          sliderActiveBackground: "#7fff00",
        },
        breadcrumb: {
          background: "#1a0a1a",
        },
        editorGutter: {
          background: "#1a0a1a",
        },
        minimap: {
          background: "#2e0a2e",
          sliderBackground: "#9acd3260",
          sliderHoverBackground: "#9acd3280",
          sliderActiveBackground: "#9acd32a0",
        },
        syntax: {
          comment: "#8b008b",
          keyword: "#9acd32",
          string: "#dda0dd",
          number: "#f0e68c",
          function: "#483d8b",
          variable: "#9acd32",
          type: "#7fffd4",
          class: "#da70d6",
          interface: "#98fb98",
          namespace: "#483d8b",
          operator: "#9acd32",
          punctuation: "#9acd32",
          constant: "#f0e68c",
          property: "#9acd32",
          tag: "#da70d6",
          attribute: "#7fffd4",
        },
      },

      effects: {
        transparency: 10,
        blur: 3,
        animations: true,
        particleEffects: true,
        glowEffect: true,
        scanlines: false,
        crtEffect: false,
      },
    },
  },

  // 🕷️ Spider's Web - Dark grey with silver accents
  {
    id: "spider-web",
    name: "🕷️ Spider's Web",
    description: "Dark grey with silver accents like intricate spider webs",
    category: "gothic",
    preview: "",
    theme: {
      name: "Spider's Web",
      version: "1.0.0",
      author: "VibeStudio",
      description: "Dark grey with silver accents like intricate spider webs",
      created: new Date().toISOString(),
      modified: new Date().toISOString(),

      font: {
        family: "Roboto Mono, monospace",
        size: 14,
        weight: "300",
        ligatures: false,
        lineHeight: 1.3,
      },

      cursor: {
        style: "line",
        blinking: true,
        color: "#c0c0c0",
      },

      colors: {
        background: "#1c1c1c",
        foreground: "#c0c0c0",
        selection: "#696969",
        selectionBackground: "#696969",

        ansiBlack: "#1c1c1c",
        ansiRed: "#8b7d7b",
        ansiGreen: "#a9a9a9",
        ansiYellow: "#dcdcdc",
        ansiBlue: "#708090",
        ansiMagenta: "#d3d3d3",
        ansiCyan: "#b0c4de",
        ansiWhite: "#c0c0c0",
        ansiBrightBlack: "#2f2f2f",
        ansiBrightRed: "#bc9a9a",
        ansiBrightGreen: "#d3d3d3",
        ansiBrightYellow: "#f5f5f5",
        ansiBrightBlue: "#9399b2",
        ansiBrightMagenta: "#e6e6e6",
        ansiBrightCyan: "#d8e4f0",
        ansiBrightWhite: "#ffffff",

        border: "#2f2f2f",
        tab: {
          activeForeground: "#c0c0c0",
          activeBackground: "#1c1c1c",
          inactiveForeground: "#a9a9a9",
          inactiveBackground: "#2f2f2f",
          border: "#2f2f2f",
        },
      },

      integration: {
        applyToEditor: true,
        applyToTerminal: true,
        applyToWorkbench: true,
      },

      editorTheme: {
        editor: {
          background: "#1c1c1c",
          foreground: "#c0c0c0",
          selectionBackground: "#69696980",
          selectionForeground: "#ffffff",
          lineHighlightBackground: "#2f2f2f",
          cursorColor: "#c0c0c0",
          indentGuideBackground: "#696969",
          indentGuideActiveBackground: "#c0c0c0",
        },
        activityBar: {
          background: "#2f2f2f",
          foreground: "#c0c0c0",
          inactiveForeground: "#a9a9a9",
          border: "#696969",
          activeBorder: "#c0c0c0",
          activeBackground: "#1c1c1c",
        },
        sideBar: {
          background: "#1c1c1c",
          foreground: "#c0c0c0",
          border: "#696969",
        },
        sideBarSectionHeader: {
          background: "#2f2f2f",
          foreground: "#c0c0c0",
          border: "#c0c0c0",
        },
        panelTitle: {
          background: "#1c1c1c",
          activeForeground: "#c0c0c0",
          activeBorder: "#c0c0c0",
          inactiveForeground: "#a9a9a9",
        },
        statusBar: {
          background: "#c0c0c0",
          foreground: "#1c1c1c",
          border: "#c0c0c0",
          debuggingBackground: "#708090",
          debuggingForeground: "#ffffff",
          noFolderBackground: "#a9a9a9",
          noFolderForeground: "#1c1c1c",
        },
        titleBar: {
          activeBackground: "#2f2f2f",
          activeForeground: "#c0c0c0",
          inactiveBackground: "#1c1c1c",
          inactiveForeground: "#a9a9a9",
          border: "#696969",
        },
        panel: {
          background: "#1c1c1c",
          border: "#696969",
          dropBorder: "#c0c0c0",
        },
        tab: {
          background: "#0f0f0f",
          activeBackground: "#1c1c1c",
          activeForeground: "#c0c0c0",
          activeBorder: "#c0c0c0",
          activeBorderTop: "#c0c0c0",
          inactiveBackground: "#2f2f2f",
          inactiveForeground: "#a9a9a9",
          inactiveModifiedBorder: "#dcdcdc",
          unfocusedActiveBackground: "#2f2f2f",
          unfocusedActiveForeground: "#a9a9a9",
          unfocusedInactiveBackground: "#1c1c1c",
          unfocusedInactiveForeground: "#696969",
          border: "#696969",
        },
        input: {
          background: "#2f2f2f",
          foreground: "#c0c0c0",
          border: "#696969",
          placeholderForeground: "#a9a9a9",
        },
        button: {
          background: "#c0c0c0",
          foreground: "#1c1c1c",
          hoverBackground: "#d3d3d3",
          secondaryBackground: "#696969",
          secondaryForeground: "#c0c0c0",
          secondaryHoverBackground: "#808080",
        },
        checkbox: {
          background: "#2f2f2f",
          foreground: "#c0c0c0",
          border: "#696969",
        },
        badge: {
          background: "#c0c0c0",
          foreground: "#1c1c1c",
        },
        progressBar: {
          background: "#c0c0c0",
        },
        dropdown: {
          background: "#2f2f2f",
          foreground: "#c0c0c0",
          border: "#696969",
        },
        list: {
          activeSelectionBackground: "#69696980",
          activeSelectionForeground: "#ffffff",
          inactiveSelectionBackground: "#696969",
          inactiveSelectionForeground: "#c0c0c0",
          hoverBackground: "#2f2f2f",
          hoverForeground: "#c0c0c0",
          focusBackground: "#69696980",
          focusForeground: "#ffffff",
        },
        scrollbar: {
          shadow: "#000000",
          sliderBackground: "#8b0000",
          sliderHoverBackground: "#dc143c",
          sliderActiveBackground: "#ff1744",
        },
        breadcrumb: {
          background: "#1c1c1c",
        },
        editorGutter: {
          background: "#1c1c1c",
        },
        minimap: {
          background: "#2f2f2f",
          sliderBackground: "#c0c0c060",
          sliderHoverBackground: "#c0c0c080",
          sliderActiveBackground: "#c0c0c0a0",
        },
        syntax: {
          comment: "#a9a9a9",
          keyword: "#c0c0c0",
          string: "#dcdcdc",
          number: "#f5f5f5",
          function: "#d3d3d3",
          variable: "#c0c0c0",
          type: "#b0c4de",
          class: "#e6e6e6",
          interface: "#d8e4f0",
          namespace: "#d3d3d3",
          operator: "#c0c0c0",
          punctuation: "#c0c0c0",
          constant: "#f5f5f5",
          property: "#c0c0c0",
          tag: "#e6e6e6",
          attribute: "#b0c4de",
        },
      },

      effects: {
        transparency: 5,
        blur: 1,
        animations: false,
        particleEffects: false,
        glowEffect: false,
        scanlines: false,
        crtEffect: false,
      },
    },
  },
];
