import { ThemePreset } from "../types";

export const naturePresets: ThemePreset[] = [
  // 🌲 Forest Green - Nature-inspired earth tones and forest vibes
  {
    id: "forest-green",
    name: "🌲 Forest Green",
    description: "Nature-inspired earth tones and forest vibes",
    category: "nature",
    preview: "",
    theme: {
      name: "Forest Green",
      version: "1.0.0",
      author: "VibeStudio",
      description: "Nature-inspired earth tones and forest vibes",
      created: new Date().toISOString(),
      modified: new Date().toISOString(),

      font: {
        family: "Anonymous Pro, monospace",
        size: 14,
        weight: "normal",
        ligatures: false,
        lineHeight: 1.2,
      },

      cursor: {
        style: "line",
        blinking: true,
        color: "#32cd32",
      },

      colors: {
        background: "#0f2a0f",
        foreground: "#32cd32",
        selection: "#228b22",
        selectionBackground: "#228b22",

        ansiBlack: "#0f2a0f",
        ansiRed: "#cd5c5c",
        ansiGreen: "#32cd32",
        ansiYellow: "#daa520",
        ansiBlue: "#4682b4",
        ansiMagenta: "#dda0dd",
        ansiCyan: "#20b2aa",
        ansiWhite: "#f0f8ff",
        ansiBrightBlack: "#2f4f4f",
        ansiBrightRed: "#f08080",
        ansiBrightGreen: "#90ee90",
        ansiBrightYellow: "#ffd700",
        ansiBrightBlue: "#87ceeb",
        ansiBrightMagenta: "#da70d6",
        ansiBrightCyan: "#afeeee",
        ansiBrightWhite: "#ffffff",

        border: "#228b22",
        tab: {
          activeForeground: "#32cd32",
          activeBackground: "#1e4d1e",
          inactiveForeground: "#6b8e23",
          inactiveBackground: "#0f2a0f",
          border: "#228b22",
        },
      },

      integration: {
        applyToEditor: true,
        applyToTerminal: true,
        applyToWorkbench: true,
      },

      editorTheme: {
        editor: {
          background: "#0f2a0f",
          foreground: "#32cd32",
          selectionBackground: "#228b22",
          selectionForeground: "#ffffff",
          lineHighlightBackground: "#1e4d1e",
          cursorColor: "#32cd32",
          indentGuideBackground: "#228b22",
          indentGuideActiveBackground: "#32cd32",
        },
        activityBar: {
          background: "#061b06",
          foreground: "#32cd32",
          inactiveForeground: "#6b8e23",
          border: "#228b22",
          activeBorder: "#daa520",
          activeBackground: "#1e4d1e",
        },
        sideBar: {
          background: "#0f2a0f",
          foreground: "#32cd32",
          border: "#228b22",
        },
        sideBarSectionHeader: {
          background: "#1e4d1e",
          foreground: "#32cd32",
          border: "#daa520",
        },
        panelTitle: {
          background: "#0f2a0f",
          activeForeground: "#32cd32",
          activeBorder: "#daa520",
          inactiveForeground: "#6b8e23",
        },
        statusBar: {
          background: "#32cd32",
          foreground: "#000000",
          border: "#32cd32",
          debuggingBackground: "#cd5c5c",
          debuggingForeground: "#ffffff",
          noFolderBackground: "#4682b4",
          noFolderForeground: "#ffffff",
        },
        titleBar: {
          activeBackground: "#061b06",
          activeForeground: "#32cd32",
          inactiveBackground: "#0f2a0f",
          inactiveForeground: "#6b8e23",
          border: "#228b22",
        },
        panel: {
          background: "#0f2a0f",
          border: "#228b22",
          dropBorder: "#32cd32",
        },
        tab: {
          background: "#061b06",
          activeBackground: "#0f2a0f",
          activeForeground: "#32cd32",
          activeBorder: "#daa520",
          activeBorderTop: "#daa520",
          inactiveBackground: "#1e4d1e",
          inactiveForeground: "#6b8e23",
          inactiveModifiedBorder: "#cd5c5c",
          unfocusedActiveBackground: "#1e4d1e",
          unfocusedActiveForeground: "#6b8e23",
          unfocusedInactiveBackground: "#061b06",
          unfocusedInactiveForeground: "#556b2f",
          border: "#228b22",
        },
        input: {
          background: "#1e4d1e",
          foreground: "#32cd32",
          border: "#228b22",
          placeholderForeground: "#6b8e23",
        },
        button: {
          background: "#32cd32",
          foreground: "#000000",
          hoverBackground: "#228b22",
          secondaryBackground: "#228b22",
          secondaryForeground: "#32cd32",
          secondaryHoverBackground: "#6b8e23",
        },
        checkbox: {
          background: "#1e4d1e",
          foreground: "#32cd32",
          border: "#228b22",
        },
        badge: {
          background: "#daa520",
          foreground: "#0f2a0f",
        },
        progressBar: {
          background: "#32cd32",
        },
        dropdown: {
          background: "#1e4d1e",
          foreground: "#32cd32",
          border: "#228b22",
        },
        list: {
          activeSelectionBackground: "#32cd32",
          activeSelectionForeground: "#000000",
          inactiveSelectionBackground: "#228b22",
          inactiveSelectionForeground: "#32cd32",
          hoverBackground: "#1e4d1e",
          hoverForeground: "#32cd32",
          focusBackground: "#32cd32",
          focusForeground: "#000000",
        },
        scrollbar: {
          shadow: "#1b5e20",
          sliderBackground: "#32cd32",
          sliderHoverBackground: "#7cfc00",
          sliderActiveBackground: "#90ee90",
        },
        breadcrumb: {
          background: "#0d2a0d",
        },
        editorGutter: {
          background: "#0d2a0d",
        },
        minimap: {
          background: "#1a3d1a",
          sliderBackground: "#228b2260",
          sliderHoverBackground: "#228b2280",
          sliderActiveBackground: "#228b22a0",
        },
        syntax: {
          comment: "#6b8e23",
          keyword: "#32cd32",
          string: "#daa520",
          number: "#20b2aa",
          function: "#4682b4",
          variable: "#32cd32",
          type: "#dda0dd",
          class: "#32cd32",
          interface: "#20b2aa",
          namespace: "#dda0dd",
          operator: "#32cd32",
          punctuation: "#32cd32",
          constant: "#daa520",
          property: "#32cd32",
          tag: "#32cd32",
          attribute: "#daa520",
        },
      },

      effects: {
        transparency: 0,
        blur: 0,
        animations: false,
        particleEffects: false,
        glowEffect: false,
        scanlines: false,
        crtEffect: false,
      },
    },
  },

  // 🌙 Midnight Blue - Deep blue oceanic night vibes
  {
    id: "midnight-blue",
    name: "🌙 Midnight Blue",
    description: "Deep blue oceanic night vibes",
    category: "dark",
    preview: "",
    theme: {
      name: "Midnight Blue",
      version: "1.0.0",
      author: "VibeStudio",
      description: "Deep blue oceanic night vibes",
      created: new Date().toISOString(),
      modified: new Date().toISOString(),

      font: {
        family: "Roboto Mono, monospace",
        size: 14,
        weight: "normal",
        ligatures: true,
        lineHeight: 1.2,
      },

      cursor: {
        style: "line",
        blinking: true,
        color: "#00bfff",
      },

      colors: {
        background: "#0b1426",
        foreground: "#00bfff",
        selection: "#1e90ff",
        selectionBackground: "#1e90ff",

        ansiBlack: "#0b1426",
        ansiRed: "#ff6b6b",
        ansiGreen: "#51cf66",
        ansiYellow: "#ffd43b",
        ansiBlue: "#00bfff",
        ansiMagenta: "#da77f2",
        ansiCyan: "#22b8cf",
        ansiWhite: "#e9ecef",
        ansiBrightBlack: "#495057",
        ansiBrightRed: "#ff8787",
        ansiBrightGreen: "#69db7c",
        ansiBrightYellow: "#ffda55",
        ansiBrightBlue: "#339af0",
        ansiBrightMagenta: "#e599f7",
        ansiBrightCyan: "#3bc9db",
        ansiBrightWhite: "#ffffff",

        border: "#1c2841",
        tab: {
          activeForeground: "#00bfff",
          activeBackground: "#162032",
          inactiveForeground: "#74c0fc",
          inactiveBackground: "#0b1426",
          border: "#1c2841",
        },
      },

      integration: {
        applyToEditor: true,
        applyToTerminal: true,
        applyToWorkbench: true,
      },

      editorTheme: {
        editor: {
          background: "#0b1426",
          foreground: "#00bfff",
          selectionBackground: "#1e90ff",
          selectionForeground: "#ffffff",
          lineHighlightBackground: "#162032",
          cursorColor: "#00bfff",
          indentGuideBackground: "#1c2841",
          indentGuideActiveBackground: "#00bfff",
        },
        activityBar: {
          background: "#050a14",
          foreground: "#00bfff",
          inactiveForeground: "#74c0fc",
          border: "#1c2841",
          activeBorder: "#ffd43b",
          activeBackground: "#162032",
        },
        sideBar: {
          background: "#0b1426",
          foreground: "#00bfff",
          border: "#1c2841",
        },
        sideBarSectionHeader: {
          background: "#162032",
          foreground: "#00bfff",
          border: "#ffd43b",
        },
        panelTitle: {
          background: "#0b1426",
          activeForeground: "#00bfff",
          activeBorder: "#ffd43b",
          inactiveForeground: "#74c0fc",
        },
        statusBar: {
          background: "#00bfff",
          foreground: "#000000",
          border: "#00bfff",
          debuggingBackground: "#ff6b6b",
          debuggingForeground: "#ffffff",
          noFolderBackground: "#da77f2",
          noFolderForeground: "#ffffff",
        },
        titleBar: {
          activeBackground: "#050a14",
          activeForeground: "#00bfff",
          inactiveBackground: "#0b1426",
          inactiveForeground: "#74c0fc",
          border: "#1c2841",
        },
        panel: {
          background: "#0b1426",
          border: "#1c2841",
          dropBorder: "#00bfff",
        },
        tab: {
          background: "#061b06",
          activeBackground: "#0b1426",
          activeForeground: "#00bfff",
          activeBorder: "#ffd43b",
          activeBorderTop: "#ffd43b",
          inactiveBackground: "#162032",
          inactiveForeground: "#74c0fc",
          inactiveModifiedBorder: "#ff6b6b",
          unfocusedActiveBackground: "#162032",
          unfocusedActiveForeground: "#74c0fc",
          unfocusedInactiveBackground: "#050a14",
          unfocusedInactiveForeground: "#4c6ef5",
          border: "#1c2841",
        },
        input: {
          background: "#162032",
          foreground: "#00bfff",
          border: "#1c2841",
          placeholderForeground: "#74c0fc",
        },
        button: {
          background: "#00bfff",
          foreground: "#000000",
          hoverBackground: "#1e90ff",
          secondaryBackground: "#1c2841",
          secondaryForeground: "#00bfff",
          secondaryHoverBackground: "#339af0",
        },
        checkbox: {
          background: "#162032",
          foreground: "#00bfff",
          border: "#1c2841",
        },
        badge: {
          background: "#ffd43b",
          foreground: "#0b1426",
        },
        progressBar: {
          background: "#00bfff",
        },
        dropdown: {
          background: "#162032",
          foreground: "#00bfff",
          border: "#1c2841",
        },
        list: {
          activeSelectionBackground: "#00bfff",
          activeSelectionForeground: "#000000",
          inactiveSelectionBackground: "#1c2841",
          inactiveSelectionForeground: "#00bfff",
          hoverBackground: "#162032",
          hoverForeground: "#00bfff",
          focusBackground: "#00bfff",
          focusForeground: "#000000",
        },
        scrollbar: {
          shadow: "#b0bec5",
          sliderBackground: "#191970",
          sliderHoverBackground: "#483d8b",
          sliderActiveBackground: "#6a5acd",
        },
        breadcrumb: {
          background: "#0b1426",
        },
        editorGutter: {
          background: "#0b1426",
        },
        minimap: {
          background: "#162032",
          sliderBackground: "#19197060",
          sliderHoverBackground: "#19197080",
          sliderActiveBackground: "#191970a0",
        },
        syntax: {
          comment: "#74c0fc",
          keyword: "#00bfff",
          string: "#51cf66",
          number: "#ffd43b",
          function: "#da77f2",
          variable: "#00bfff",
          type: "#22b8cf",
          class: "#00bfff",
          interface: "#da77f2",
          namespace: "#22b8cf",
          operator: "#00bfff",
          punctuation: "#00bfff",
          constant: "#ffd43b",
          property: "#00bfff",
          tag: "#00bfff",
          attribute: "#51cf66",
        },
      },

      effects: {
        transparency: 5,
        blur: 1,
        animations: false,
        particleEffects: false,
        glowEffect: true,
        scanlines: false,
        crtEffect: false,
      },
    },
  },

  // 🌊 Deep Ocean - Mysterious depths of the ocean
  {
    id: "deep-ocean",
    name: "🌊 Deep Ocean",
    description: "Mysterious depths of the ocean with bioluminescent highlights",
    category: "nature",
    preview: "",
    theme: {
      name: "Deep Ocean",
      version: "1.0.0",
      author: "VibeStudio",
      description: "Mysterious depths of the ocean with bioluminescent highlights",
      created: new Date().toISOString(),
      modified: new Date().toISOString(),

      font: {
        family: "JetBrains Mono, monospace",
        size: 14,
        weight: "normal",
        ligatures: true,
        lineHeight: 1.3,
      },

      cursor: {
        style: "line",
        blinking: true,
        color: "#00ffff",
      },

      colors: {
        background: "#0d1b2a",
        foreground: "#e0f6ff",
        selection: "#1b263b",
        selectionBackground: "#1b263b",

        ansiBlack: "#0d1b2a",
        ansiRed: "#ff5e5b",
        ansiGreen: "#00f5ff",
        ansiYellow: "#ffd23f",
        ansiBlue: "#415a77",
        ansiMagenta: "#7209b7",
        ansiCyan: "#00ffff",
        ansiWhite: "#e0f6ff",
        ansiBrightBlack: "#1b263b",
        ansiBrightRed: "#ff8a80",
        ansiBrightGreen: "#64ffda",
        ansiBrightYellow: "#ffeb3b",
        ansiBrightBlue: "#82b1ff",
        ansiBrightMagenta: "#b388ff",
        ansiBrightCyan: "#84ffff",
        ansiBrightWhite: "#ffffff",

        border: "#1b263b",
        tab: {
          activeForeground: "#e0f6ff",
          activeBackground: "#0d1b2a",
          inactiveForeground: "#778da9",
          inactiveBackground: "#1b263b",
          border: "#415a77",
        },
      },

      integration: {
        applyToEditor: true,
        applyToTerminal: true,
        applyToWorkbench: true,
      },

      editorTheme: {
        editor: {
          background: "#0d1b2a",
          foreground: "#e0f6ff",
          selectionBackground: "#1b263b80",
          selectionForeground: "#ffffff",
          lineHighlightBackground: "#1b263b",
          cursorColor: "#00ffff",
          indentGuideBackground: "#415a77",
          indentGuideActiveBackground: "#00ffff",
        },
        activityBar: {
          background: "#1b263b",
          foreground: "#e0f6ff",
          inactiveForeground: "#778da9",
          border: "#415a77",
          activeBorder: "#00ffff",
          activeBackground: "#0d1b2a",
        },
        sideBar: {
          background: "#0d1b2a",
          foreground: "#e0f6ff",
          border: "#415a77",
        },
        sideBarSectionHeader: {
          background: "#1b263b",
          foreground: "#e0f6ff",
          border: "#00ffff",
        },
        panelTitle: {
          background: "#0d1b2a",
          activeForeground: "#e0f6ff",
          activeBorder: "#00ffff",
          inactiveForeground: "#778da9",
        },
        statusBar: {
          background: "#00ffff",
          foreground: "#0d1b2a",
          border: "#00ffff",
          debuggingBackground: "#7209b7",
          debuggingForeground: "#ffffff",
          noFolderBackground: "#415a77",
          noFolderForeground: "#ffffff",
        },
        titleBar: {
          activeBackground: "#1b263b",
          activeForeground: "#e0f6ff",
          inactiveBackground: "#0d1b2a",
          inactiveForeground: "#778da9",
          border: "#415a77",
        },
        panel: {
          background: "#0d1b2a",
          border: "#415a77",
          dropBorder: "#00ffff",
        },
        tab: {
          background: "#061b06",
          activeBackground: "#0d1b2a",
          activeForeground: "#e0f6ff",
          activeBorder: "#00ffff",
          activeBorderTop: "#00ffff",
          inactiveBackground: "#1b263b",
          inactiveForeground: "#778da9",
          inactiveModifiedBorder: "#7209b7",
          unfocusedActiveBackground: "#1b263b",
          unfocusedActiveForeground: "#778da9",
          unfocusedInactiveBackground: "#0d1b2a",
          unfocusedInactiveForeground: "#415a77",
          border: "#415a77",
        },
        input: {
          background: "#1b263b",
          foreground: "#e0f6ff",
          border: "#415a77",
          placeholderForeground: "#778da9",
        },
        button: {
          background: "#00ffff",
          foreground: "#0d1b2a",
          hoverBackground: "#64ffda",
          secondaryBackground: "#415a77",
          secondaryForeground: "#e0f6ff",
          secondaryHoverBackground: "#778da9",
        },
        checkbox: {
          background: "#1b263b",
          foreground: "#e0f6ff",
          border: "#415a77",
        },
        badge: {
          background: "#00ffff",
          foreground: "#0d1b2a",
        },
        progressBar: {
          background: "#00ffff",
        },
        dropdown: {
          background: "#1b263b",
          foreground: "#e0f6ff",
          border: "#415a77",
        },
        list: {
          activeSelectionBackground: "#1b263b80",
          activeSelectionForeground: "#ffffff",
          inactiveSelectionBackground: "#415a77",
          inactiveSelectionForeground: "#e0f6ff",
          hoverBackground: "#1b263b",
          hoverForeground: "#e0f6ff",
          focusBackground: "#1b263b80",
          focusForeground: "#ffffff",
        },
        scrollbar: {
          shadow: "#01579b",
          sliderBackground: "#00bfff",
          sliderHoverBackground: "#87ceeb",
          sliderActiveBackground: "#b0e0e6",
        },
        breadcrumb: {
          background: "#0d1b2a",
        },
        editorGutter: {
          background: "#0d1b2a",
        },
        minimap: {
          background: "#1b263b",
          sliderBackground: "#00bfff60",
          sliderHoverBackground: "#00bfff80",
          sliderActiveBackground: "#00bfffa0",
        },
        syntax: {
          comment: "#778da9",
          keyword: "#00ffff",
          string: "#64ffda",
          number: "#ffd23f",
          function: "#82b1ff",
          variable: "#e0f6ff",
          type: "#b388ff",
          class: "#00f5ff",
          interface: "#84ffff",
          namespace: "#82b1ff",
          operator: "#00ffff",
          punctuation: "#e0f6ff",
          constant: "#ffd23f",
          property: "#e0f6ff",
          tag: "#00f5ff",
          attribute: "#b388ff",
        },
      },

      effects: {
        transparency: 5,
        blur: 2,
        animations: true,
        particleEffects: true,
        glowEffect: true,
        scanlines: false,
        crtEffect: false,
      },
    },
  },

  // 🌸 Cherry Blossom - Japanese spring aesthetic
  {
    id: "cherry-blossom",
    name: "🌸 Cherry Blossom",
    description: "Japanese spring aesthetic with soft pinks and whites",
    category: "nature",
    preview: "",
    theme: {
      name: "Cherry Blossom",
      version: "1.0.0",
      author: "VibeStudio",
      description: "Japanese spring aesthetic with soft pinks and whites",
      created: new Date().toISOString(),
      modified: new Date().toISOString(),

      font: {
        family: "Noto Sans Mono, monospace",
        size: 14,
        weight: "normal",
        ligatures: false,
        lineHeight: 1.4,
      },

      cursor: {
        style: "line",
        blinking: true,
        color: "#d63384",
      },

      colors: {
        background: "#fef7f7",
        foreground: "#5d4e75",
        selection: "#f8d7da",
        selectionBackground: "#f8d7da",

        ansiBlack: "#5d4e75",
        ansiRed: "#d63384",
        ansiGreen: "#20c997",
        ansiYellow: "#fd7e14",
        ansiBlue: "#0d6efd",
        ansiMagenta: "#6f42c1",
        ansiCyan: "#0dcaf0",
        ansiWhite: "#fef7f7",
        ansiBrightBlack: "#6c757d",
        ansiBrightRed: "#f1aeb5",
        ansiBrightGreen: "#75b798",
        ansiBrightYellow: "#ffab40",
        ansiBrightBlue: "#6ea8fe",
        ansiBrightMagenta: "#a98eda",
        ansiBrightCyan: "#86cfda",
        ansiBrightWhite: "#ffffff",

        border: "#f8d7da",
        tab: {
          activeForeground: "#5d4e75",
          activeBackground: "#ffffff",
          inactiveForeground: "#8e8e93",
          inactiveBackground: "#fef7f7",
          border: "#f8d7da",
        },
      },

      integration: {
        applyToEditor: true,
        applyToTerminal: true,
        applyToWorkbench: true,
      },

      editorTheme: {
        editor: {
          background: "#fef7f7",
          foreground: "#5d4e75",
          selectionBackground: "#f8d7da80",
          selectionForeground: "#5d4e75",
          lineHighlightBackground: "#f5f5f5",
          cursorColor: "#d63384",
          indentGuideBackground: "#f8d7da",
          indentGuideActiveBackground: "#d63384",
        },
        activityBar: {
          background: "#f5f5f5",
          foreground: "#5d4e75",
          inactiveForeground: "#8e8e93",
          border: "#f8d7da",
          activeBorder: "#d63384",
          activeBackground: "#ffffff",
        },
        sideBar: {
          background: "#fef7f7",
          foreground: "#5d4e75",
          border: "#f8d7da",
        },
        sideBarSectionHeader: {
          background: "#f5f5f5",
          foreground: "#d63384",
          border: "#d63384",
        },
        panelTitle: {
          background: "#fef7f7",
          activeForeground: "#5d4e75",
          activeBorder: "#d63384",
          inactiveForeground: "#8e8e93",
        },
        statusBar: {
          background: "#d63384",
          foreground: "#ffffff",
          border: "#d63384",
          debuggingBackground: "#6f42c1",
          debuggingForeground: "#ffffff",
          noFolderBackground: "#0d6efd",
          noFolderForeground: "#ffffff",
        },
        titleBar: {
          activeBackground: "#f5f5f5",
          activeForeground: "#5d4e75",
          inactiveBackground: "#fef7f7",
          inactiveForeground: "#8e8e93",
          border: "#f8d7da",
        },
        panel: {
          background: "#fef7f7",
          border: "#f8d7da",
          dropBorder: "#d63384",
        },
        tab: {
          background: "#ffffff",
          activeBackground: "#fef7f7",
          activeForeground: "#5d4e75",
          activeBorder: "#d63384",
          activeBorderTop: "#d63384",
          inactiveBackground: "#f5f5f5",
          inactiveForeground: "#8e8e93",
          inactiveModifiedBorder: "#6f42c1",
          unfocusedActiveBackground: "#f5f5f5",
          unfocusedActiveForeground: "#8e8e93",
          unfocusedInactiveBackground: "#ffffff",
          unfocusedInactiveForeground: "#ced4da",
          border: "#f8d7da",
        },
        input: {
          background: "#ffffff",
          foreground: "#5d4e75",
          border: "#f8d7da",
          placeholderForeground: "#8e8e93",
        },
        button: {
          background: "#d63384",
          foreground: "#ffffff",
          hoverBackground: "#b02a5b",
          secondaryBackground: "#f8d7da",
          secondaryForeground: "#5d4e75",
          secondaryHoverBackground: "#f1aeb5",
        },
        checkbox: {
          background: "#ffffff",
          foreground: "#5d4e75",
          border: "#f8d7da",
        },
        badge: {
          background: "#d63384",
          foreground: "#ffffff",
        },
        progressBar: {
          background: "#d63384",
        },
        dropdown: {
          background: "#ffffff",
          foreground: "#5d4e75",
          border: "#f8d7da",
        },
        list: {
          activeSelectionBackground: "#f8d7da80",
          activeSelectionForeground: "#5d4e75",
          inactiveSelectionBackground: "#f5f5f5",
          inactiveSelectionForeground: "#5d4e75",
          hoverBackground: "#f5f5f5",
          hoverForeground: "#5d4e75",
          focusBackground: "#f8d7da80",
          focusForeground: "#5d4e75",
        },
        scrollbar: {
          shadow: "#880e4f",
          sliderBackground: "#d63384",
          sliderHoverBackground: "#f06292",
          sliderActiveBackground: "#f8bbd9",
        },
        breadcrumb: {
          background: "#fef7f7",
        },
        editorGutter: {
          background: "#fef7f7",
        },
        minimap: {
          background: "#f5f5f5",
          sliderBackground: "#d6338460",
          sliderHoverBackground: "#d6338480",
          sliderActiveBackground: "#d63384a0",
        },
        syntax: {
          comment: "#8e8e93",
          keyword: "#d63384",
          string: "#20c997",
          number: "#fd7e14",
          function: "#0d6efd",
          variable: "#5d4e75",
          type: "#6f42c1",
          class: "#d63384",
          interface: "#0dcaf0",
          namespace: "#0d6efd",
          operator: "#d63384",
          punctuation: "#5d4e75",
          constant: "#fd7e14",
          property: "#5d4e75",
          tag: "#d63384",
          attribute: "#6f42c1",
        },
      },

      effects: {
        transparency: 3,
        blur: 1,
        animations: true,
        particleEffects: true,
        glowEffect: false,
        scanlines: false,
        crtEffect: false,
      },
    },
  },

  // 🍂 Autumn Leaves - Rich fall colors
  {
    id: "autumn-leaves",
    name: "🍂 Autumn Leaves",
    description: "Rich fall colors with warm oranges, reds, and golden yellows",
    category: "nature",
    preview: "",
    theme: {
      name: "Autumn Leaves",
      version: "1.0.0",
      author: "VibeStudio",
      description: "Rich fall colors with warm oranges, reds, and golden yellows",
      created: new Date().toISOString(),
      modified: new Date().toISOString(),

      font: {
        family: "Source Code Pro, monospace",
        size: 14,
        weight: "500",
        ligatures: false,
        lineHeight: 1.3,
      },

      cursor: {
        style: "block",
        blinking: false,
        color: "#d2691e",
      },

      colors: {
        background: "#2f1b14",
        foreground: "#ffa500",
        selection: "#8b4513",
        selectionBackground: "#8b4513",

        ansiBlack: "#2f1b14",
        ansiRed: "#cd853f",
        ansiGreen: "#9acd32",
        ansiYellow: "#ffd700",
        ansiBlue: "#4682b4",
        ansiMagenta: "#daa520",
        ansiCyan: "#20b2aa",
        ansiWhite: "#ffa500",
        ansiBrightBlack: "#8b4513",
        ansiBrightRed: "#ff8c00",
        ansiBrightGreen: "#adff2f",
        ansiBrightYellow: "#ffff00",
        ansiBrightBlue: "#87ceeb",
        ansiBrightMagenta: "#ffd700",
        ansiBrightCyan: "#40e0d0",
        ansiBrightWhite: "#ffffff",

        border: "#8b4513",
        tab: {
          activeForeground: "#ffa500",
          activeBackground: "#2f1b14",
          inactiveForeground: "#cd853f",
          inactiveBackground: "#8b4513",
          border: "#8b4513",
        },
      },

      integration: {
        applyToEditor: true,
        applyToTerminal: true,
        applyToWorkbench: true,
      },

      editorTheme: {
        editor: {
          background: "#2f1b14",
          foreground: "#ffa500",
          selectionBackground: "#8b451380",
          selectionForeground: "#ffffff",
          lineHighlightBackground: "#3d2317",
          cursorColor: "#d2691e",
          indentGuideBackground: "#8b4513",
          indentGuideActiveBackground: "#d2691e",
        },
        activityBar: {
          background: "#3d2317",
          foreground: "#ffa500",
          inactiveForeground: "#cd853f",
          border: "#8b4513",
          activeBorder: "#d2691e",
          activeBackground: "#2f1b14",
        },
        sideBar: {
          background: "#2f1b14",
          foreground: "#ffa500",
          border: "#8b4513",
        },
        sideBarSectionHeader: {
          background: "#3d2317",
          foreground: "#ffa500",
          border: "#d2691e",
        },
        panelTitle: {
          background: "#2f1b14",
          activeForeground: "#ffa500",
          activeBorder: "#d2691e",
          inactiveForeground: "#cd853f",
        },
        statusBar: {
          background: "#d2691e",
          foreground: "#ffffff",
          border: "#d2691e",
          debuggingBackground: "#b22222",
          debuggingForeground: "#ffffff",
          noFolderBackground: "#daa520",
          noFolderForeground: "#2f1b14",
        },
        titleBar: {
          activeBackground: "#3d2317",
          activeForeground: "#ffa500",
          inactiveBackground: "#2f1b14",
          inactiveForeground: "#cd853f",
          border: "#8b4513",
        },
        panel: {
          background: "#2f1b14",
          border: "#8b4513",
          dropBorder: "#d2691e",
        },
        tab: {
          background: "#ffffff",
          activeBackground: "#2f1b14",
          activeForeground: "#ffa500",
          activeBorder: "#d2691e",
          activeBorderTop: "#d2691e",
          inactiveBackground: "#3d2317",
          inactiveForeground: "#cd853f",
          inactiveModifiedBorder: "#daa520",
          unfocusedActiveBackground: "#3d2317",
          unfocusedActiveForeground: "#cd853f",
          unfocusedInactiveBackground: "#2f1b14",
          unfocusedInactiveForeground: "#8b4513",
          border: "#8b4513",
        },
        input: {
          background: "#3d2317",
          foreground: "#ffa500",
          border: "#8b4513",
          placeholderForeground: "#cd853f",
        },
        button: {
          background: "#d2691e",
          foreground: "#ffffff",
          hoverBackground: "#ff8c00",
          secondaryBackground: "#8b4513",
          secondaryForeground: "#ffa500",
          secondaryHoverBackground: "#cd853f",
        },
        checkbox: {
          background: "#3d2317",
          foreground: "#ffa500",
          border: "#8b4513",
        },
        badge: {
          background: "#d2691e",
          foreground: "#ffffff",
        },
        progressBar: {
          background: "#d2691e",
        },
        dropdown: {
          background: "#3d2317",
          foreground: "#ffa500",
          border: "#8b4513",
        },
        list: {
          activeSelectionBackground: "#8b451380",
          activeSelectionForeground: "#ffffff",
          inactiveSelectionBackground: "#3d2317",
          inactiveSelectionForeground: "#ffa500",
          hoverBackground: "#3d2317",
          hoverForeground: "#ffa500",
          focusBackground: "#8b451380",
          focusForeground: "#ffffff",
        },
        scrollbar: {
          shadow: "#bf360c",
          sliderBackground: "#ff8c00",
          sliderHoverBackground: "#ffa500",
          sliderActiveBackground: "#ffb74d",
        },
        breadcrumb: {
          background: "#2f1b14",
        },
        editorGutter: {
          background: "#2f1b14",
        },
        minimap: {
          background: "#3d2317",
          sliderBackground: "#ff8c0060",
          sliderHoverBackground: "#ff8c0080",
          sliderActiveBackground: "#ff8c00a0",
        },
        syntax: {
          comment: "#cd853f",
          keyword: "#d2691e",
          string: "#9acd32",
          number: "#ffd700",
          function: "#4682b4",
          variable: "#ffa500",
          type: "#daa520",
          class: "#ff8c00",
          interface: "#20b2aa",
          namespace: "#4682b4",
          operator: "#d2691e",
          punctuation: "#ffa500",
          constant: "#ffd700",
          property: "#ffa500",
          tag: "#ff8c00",
          attribute: "#daa520",
        },
      },

      effects: {
        transparency: 5,
        blur: 1,
        animations: true,
        particleEffects: true,
        glowEffect: false,
        scanlines: false,
        crtEffect: false,
      },
    },
  },
];
