import { ThemePreset } from "../types";

export const neonPresets: ThemePreset[] = [
  // ⚡ Electric Storm - Electric blue and yellow storm energy
  {
    id: "electric-storm",
    name: "⚡ Electric Storm",
    description: "Electric storm with dramatic blues, yellows, and lightning energy",
    category: "neon",
    preview: "",
    theme: {
      name: "Electric Storm",
      version: "1.0.0",
      author: "VibeStudio",
      description: "Electric storm with dramatic blues, yellows, and lightning energy",
      created: new Date().toISOString(),
      modified: new Date().toISOString(),

      font: {
        family: "Fira Code, monospace",
        size: 14,
        weight: "normal",
        ligatures: true,
        lineHeight: 1.2,
      },

      cursor: {
        style: "line",
        blinking: true,
        color: "#ffff00",
      },

      colors: {
        background: "#0a0a0a",
        foreground: "#ffffff",
        selection: "#ffff00",
        selectionBackground: "#ffff00",

        ansiBlack: "#0a0a0a",
        ansiRed: "#ff0080",
        ansiGreen: "#00ff80",
        ansiYellow: "#ffff00",
        ansiBlue: "#0080ff",
        ansiMagenta: "#8000ff",
        ansiCyan: "#00ffff",
        ansiWhite: "#ffffff",
        ansiBrightBlack: "#333333",
        ansiBrightRed: "#ff40a0",
        ansiBrightGreen: "#40ffa0",
        ansiBrightYellow: "#ffff40",
        ansiBrightBlue: "#40a0ff",
        ansiBrightMagenta: "#a040ff",
        ansiBrightCyan: "#40ffff",
        ansiBrightWhite: "#ffffff",

        border: "#333333",
        tab: {
          activeForeground: "#ffffff",
          activeBackground: "#0a0a0a",
          inactiveForeground: "#cccccc",
          inactiveBackground: "#1a1a1a",
          border: "#333333",
        },
      },

      integration: {
        applyToEditor: true,
        applyToTerminal: true,
        applyToWorkbench: true,
      },

      editorTheme: {
        editor: {
          background: "#0a0a0a",
          foreground: "#ffffff",
          selectionBackground: "#ffff0080",
          selectionForeground: "#000000",
          lineHighlightBackground: "#1a1a1a",
          cursorColor: "#ffff00",
          indentGuideBackground: "#333333",
          indentGuideActiveBackground: "#ffff00",
        },
        activityBar: {
          background: "#1a1a1a",
          foreground: "#ffffff",
          inactiveForeground: "#cccccc",
          border: "#333333",
          activeBorder: "#ffff00",
          activeBackground: "#0a0a0a",
        },
        sideBar: {
          background: "#0a0a0a",
          foreground: "#ffffff",
          border: "#333333",
        },
        statusBar: {
          background: "#ffff00",
          foreground: "#000000",
          border: "#ffff00",
          debuggingBackground: "#ff0080",
          debuggingForeground: "#ffffff",
          noFolderBackground: "#0080ff",
          noFolderForeground: "#ffffff",
        },
        titleBar: {
          activeBackground: "#1a1a1a",
          activeForeground: "#ffffff",
          inactiveBackground: "#0a0a0a",
          inactiveForeground: "#cccccc",
          border: "#333333",
        },
        panel: {
          background: "#0a0a0a",
          border: "#333333",
          dropBorder: "#ffff00",
        },
        tab: {
          activeBackground: "#0a0a0a",
          activeForeground: "#ffffff",
          activeBorder: "#ffff00",
          activeBorderTop: "#ffff00",
          inactiveBackground: "#1a1a1a",
          inactiveForeground: "#cccccc",
          inactiveModifiedBorder: "#0080ff",
          unfocusedActiveBackground: "#1a1a1a",
          unfocusedActiveForeground: "#cccccc",
          unfocusedInactiveBackground: "#0a0a0a",
          unfocusedInactiveForeground: "#666666",
          border: "#333333",
        },
        input: {
          background: "#1a1a1a",
          foreground: "#ffffff",
          border: "#333333",
          placeholderForeground: "#cccccc",
        },
        button: {
          background: "#ffff00",
          foreground: "#000000",
          hoverBackground: "#ffff40",
          secondaryBackground: "#333333",
          secondaryForeground: "#ffffff",
          secondaryHoverBackground: "#555555",
        },
        checkbox: {
          background: "#1a1a1a",
          foreground: "#ffffff",
          border: "#333333",
        },
        badge: {
          background: "#ffff00",
          foreground: "#000000",
        },
        progressBar: {
          background: "#ffff00",
        },
        dropdown: {
          background: "#1a1a1a",
          foreground: "#ffffff",
          border: "#333333",
        },
        list: {
          activeSelectionBackground: "#ffff0080",
          activeSelectionForeground: "#000000",
          inactiveSelectionBackground: "#333333",
          inactiveSelectionForeground: "#ffffff",
          hoverBackground: "#1a1a1a",
          hoverForeground: "#ffffff",
          focusBackground: "#ffff0080",
          focusForeground: "#000000",
        },
        scrollbar: {
          shadow: "#333333",
        },
        syntax: {
          comment: "#cccccc",
          keyword: "#ffff00",
          string: "#00ff80",
          number: "#ff0080",
          function: "#0080ff",
          variable: "#ffffff",
          type: "#8000ff",
          class: "#ff40a0",
          interface: "#00ffff",
          namespace: "#0080ff",
          operator: "#ffff00",
          punctuation: "#ffffff",
          constant: "#ff0080",
          property: "#ffffff",
          tag: "#ff40a0",
          attribute: "#8000ff",
        },
      },

      effects: {
        transparency: 10,
        blur: 3,
        animations: true,
        particleEffects: true,
        glowEffect: true,
        scanlines: false,
        crtEffect: false,
      },
    },
  },

  // 🌆 Neon Tokyo - Cyberpunk Japanese city vibes
  {
    id: "neon-tokyo",
    name: "🌆 Neon Tokyo",
    description: "Cyberpunk Japanese city with bright neon colors and urban energy",
    category: "neon",
    preview: "",
    theme: {
      name: "Neon Tokyo",
      version: "1.0.0",
      author: "VibeStudio",
      description: "Cyberpunk Japanese city with bright neon colors and urban energy",
      created: new Date().toISOString(),
      modified: new Date().toISOString(),

      font: {
        family: "JetBrains Mono, monospace",
        size: 14,
        weight: "normal",
        ligatures: true,
        lineHeight: 1.3,
      },

      cursor: {
        style: "block",
        blinking: true,
        color: "#ff0066",
      },

      colors: {
        background: "#0d1117",
        foreground: "#ff0066",
        selection: "#ff3366",
        selectionBackground: "#ff3366",

        ansiBlack: "#0d1117",
        ansiRed: "#ff0066",
        ansiGreen: "#00ff66",
        ansiYellow: "#ffff00",
        ansiBlue: "#0066ff",
        ansiMagenta: "#ff00ff",
        ansiCyan: "#00ffff",
        ansiWhite: "#ffffff",
        ansiBrightBlack: "#21262d",
        ansiBrightRed: "#ff3366",
        ansiBrightGreen: "#33ff66",
        ansiBrightYellow: "#ffff33",
        ansiBrightBlue: "#3366ff",
        ansiBrightMagenta: "#ff33ff",
        ansiBrightCyan: "#33ffff",
        ansiBrightWhite: "#ffffff",

        border: "#21262d",
        tab: {
          activeForeground: "#ff0066",
          activeBackground: "#0d1117",
          inactiveForeground: "#ff3366",
          inactiveBackground: "#21262d",
          border: "#21262d",
        },
      },

      integration: {
        applyToEditor: true,
        applyToTerminal: true,
        applyToWorkbench: true,
      },

      editorTheme: {
        editor: {
          background: "#0d1117",
          foreground: "#ff0066",
          selectionBackground: "#ff336680",
          selectionForeground: "#ffffff",
          lineHighlightBackground: "#21262d",
          cursorColor: "#ff0066",
          indentGuideBackground: "#30363d",
          indentGuideActiveBackground: "#ff0066",
        },
        activityBar: {
          background: "#21262d",
          foreground: "#ff0066",
          inactiveForeground: "#ff3366",
          border: "#30363d",
          activeBorder: "#ff0066",
          activeBackground: "#0d1117",
        },
        sideBar: {
          background: "#0d1117",
          foreground: "#ff0066",
          border: "#30363d",
        },
        statusBar: {
          background: "#ff0066",
          foreground: "#ffffff",
          border: "#ff0066",
          debuggingBackground: "#ff00ff",
          debuggingForeground: "#ffffff",
          noFolderBackground: "#0066ff",
          noFolderForeground: "#ffffff",
        },
        titleBar: {
          activeBackground: "#21262d",
          activeForeground: "#ff0066",
          inactiveBackground: "#0d1117",
          inactiveForeground: "#ff3366",
          border: "#30363d",
        },
        panel: {
          background: "#0d1117",
          border: "#30363d",
          dropBorder: "#ff0066",
        },
        tab: {
          activeBackground: "#0d1117",
          activeForeground: "#ff0066",
          activeBorder: "#ff0066",
          activeBorderTop: "#ff0066",
          inactiveBackground: "#21262d",
          inactiveForeground: "#ff3366",
          inactiveModifiedBorder: "#00ff66",
          unfocusedActiveBackground: "#21262d",
          unfocusedActiveForeground: "#ff3366",
          unfocusedInactiveBackground: "#0d1117",
          unfocusedInactiveForeground: "#30363d",
          border: "#30363d",
        },
        input: {
          background: "#21262d",
          foreground: "#ff0066",
          border: "#30363d",
          placeholderForeground: "#ff3366",
        },
        button: {
          background: "#ff0066",
          foreground: "#ffffff",
          hoverBackground: "#ff3366",
          secondaryBackground: "#30363d",
          secondaryForeground: "#ff0066",
          secondaryHoverBackground: "#484f58",
        },
        checkbox: {
          background: "#21262d",
          foreground: "#ff0066",
          border: "#30363d",
        },
        badge: {
          background: "#ff0066",
          foreground: "#ffffff",
        },
        progressBar: {
          background: "#ff0066",
        },
        dropdown: {
          background: "#21262d",
          foreground: "#ff0066",
          border: "#30363d",
        },
        list: {
          activeSelectionBackground: "#ff336680",
          activeSelectionForeground: "#ffffff",
          inactiveSelectionBackground: "#30363d",
          inactiveSelectionForeground: "#ff0066",
          hoverBackground: "#21262d",
          hoverForeground: "#ff0066",
          focusBackground: "#ff336680",
          focusForeground: "#ffffff",
        },
        scrollbar: {
          shadow: "#30363d",
        },
        syntax: {
          comment: "#ff3366",
          keyword: "#ff0066",
          string: "#00ff66",
          number: "#ffff00",
          function: "#0066ff",
          variable: "#ff0066",
          type: "#ff00ff",
          class: "#ff3366",
          interface: "#00ffff",
          namespace: "#0066ff",
          operator: "#ff0066",
          punctuation: "#ff0066",
          constant: "#ffff00",
          property: "#ff0066",
          tag: "#ff3366",
          attribute: "#ff00ff",
        },
      },

      effects: {
        transparency: 8,
        blur: 2,
        animations: true,
        particleEffects: true,
        glowEffect: true,
        scanlines: false,
        crtEffect: false,
      },
    },
  },

  // 🌇 Midnight Garden - Dark garden with glowing flowers
  {
    id: "midnight-garden",
    name: "🌇 Midnight Garden",
    description: "Mysterious midnight garden with glowing neon flower colors",
    category: "neon",
    preview: "",
    theme: {
      name: "Midnight Garden",
      version: "1.0.0",
      author: "VibeStudio",
      description: "Mysterious midnight garden with glowing neon flower colors",
      created: new Date().toISOString(),
      modified: new Date().toISOString(),

      font: {
        family: "Source Code Pro, monospace",
        size: 14,
        weight: "normal",
        ligatures: false,
        lineHeight: 1.3,
      },

      cursor: {
        style: "line",
        blinking: true,
        color: "#39ff14",
      },

      colors: {
        background: "#0a0f0a",
        foreground: "#39ff14",
        selection: "#ff1493",
        selectionBackground: "#ff1493",

        ansiBlack: "#0a0f0a",
        ansiRed: "#ff1493",
        ansiGreen: "#39ff14",
        ansiYellow: "#ffff00",
        ansiBlue: "#1e90ff",
        ansiMagenta: "#da70d6",
        ansiCyan: "#00ffff",
        ansiWhite: "#ffffff",
        ansiBrightBlack: "#1a2f1a",
        ansiBrightRed: "#ff69b4",
        ansiBrightGreen: "#7fff00",
        ansiBrightYellow: "#ffff80",
        ansiBrightBlue: "#87ceeb",
        ansiBrightMagenta: "#dda0dd",
        ansiBrightCyan: "#80ffff",
        ansiBrightWhite: "#ffffff",

        border: "#1a2f1a",
        tab: {
          activeForeground: "#39ff14",
          activeBackground: "#0a0f0a",
          inactiveForeground: "#7fff00",
          inactiveBackground: "#1a2f1a",
          border: "#1a2f1a",
        },
      },

      integration: {
        applyToEditor: true,
        applyToTerminal: true,
        applyToWorkbench: true,
      },

      editorTheme: {
        editor: {
          background: "#0a0f0a",
          foreground: "#39ff14",
          selectionBackground: "#ff149380",
          selectionForeground: "#ffffff",
          lineHighlightBackground: "#1a2f1a",
          cursorColor: "#39ff14",
          indentGuideBackground: "#2a4f2a",
          indentGuideActiveBackground: "#39ff14",
        },
        activityBar: {
          background: "#1a2f1a",
          foreground: "#39ff14",
          inactiveForeground: "#7fff00",
          border: "#2a4f2a",
          activeBorder: "#39ff14",
          activeBackground: "#0a0f0a",
        },
        sideBar: {
          background: "#0a0f0a",
          foreground: "#39ff14",
          border: "#2a4f2a",
        },
        statusBar: {
          background: "#39ff14",
          foreground: "#0a0f0a",
          border: "#39ff14",
          debuggingBackground: "#ff1493",
          debuggingForeground: "#ffffff",
          noFolderBackground: "#1e90ff",
          noFolderForeground: "#ffffff",
        },
        titleBar: {
          activeBackground: "#1a2f1a",
          activeForeground: "#39ff14",
          inactiveBackground: "#0a0f0a",
          inactiveForeground: "#7fff00",
          border: "#2a4f2a",
        },
        panel: {
          background: "#0a0f0a",
          border: "#2a4f2a",
          dropBorder: "#39ff14",
        },
        tab: {
          activeBackground: "#0a0f0a",
          activeForeground: "#39ff14",
          activeBorder: "#39ff14",
          activeBorderTop: "#39ff14",
          inactiveBackground: "#1a2f1a",
          inactiveForeground: "#7fff00",
          inactiveModifiedBorder: "#ff1493",
          unfocusedActiveBackground: "#1a2f1a",
          unfocusedActiveForeground: "#7fff00",
          unfocusedInactiveBackground: "#0a0f0a",
          unfocusedInactiveForeground: "#2a4f2a",
          border: "#2a4f2a",
        },
        input: {
          background: "#1a2f1a",
          foreground: "#39ff14",
          border: "#2a4f2a",
          placeholderForeground: "#7fff00",
        },
        button: {
          background: "#39ff14",
          foreground: "#0a0f0a",
          hoverBackground: "#7fff00",
          secondaryBackground: "#2a4f2a",
          secondaryForeground: "#39ff14",
          secondaryHoverBackground: "#3a6f3a",
        },
        checkbox: {
          background: "#1a2f1a",
          foreground: "#39ff14",
          border: "#2a4f2a",
        },
        badge: {
          background: "#39ff14",
          foreground: "#0a0f0a",
        },
        progressBar: {
          background: "#39ff14",
        },
        dropdown: {
          background: "#1a2f1a",
          foreground: "#39ff14",
          border: "#2a4f2a",
        },
        list: {
          activeSelectionBackground: "#ff149380",
          activeSelectionForeground: "#ffffff",
          inactiveSelectionBackground: "#2a4f2a",
          inactiveSelectionForeground: "#39ff14",
          hoverBackground: "#1a2f1a",
          hoverForeground: "#39ff14",
          focusBackground: "#ff149380",
          focusForeground: "#ffffff",
        },
        scrollbar: {
          shadow: "#2a4f2a",
        },
        syntax: {
          comment: "#7fff00",
          keyword: "#39ff14",
          string: "#ff1493",
          number: "#ffff00",
          function: "#1e90ff",
          variable: "#39ff14",
          type: "#da70d6",
          class: "#ff69b4",
          interface: "#00ffff",
          namespace: "#1e90ff",
          operator: "#39ff14",
          punctuation: "#39ff14",
          constant: "#ffff00",
          property: "#39ff14",
          tag: "#ff69b4",
          attribute: "#da70d6",
        },
      },

      effects: {
        transparency: 8,
        blur: 2,
        animations: true,
        particleEffects: true,
        glowEffect: true,
        scanlines: false,
        crtEffect: false,
      },
    },
  },

  // 🧿 Underwater Cave - Bioluminescent underwater vibes
  {
    id: "underwater-cave",
    name: "🧿 Underwater Cave",
    description: "Bioluminescent underwater cave with deep blues and glowing accents",
    category: "neon",
    preview: "",
    theme: {
      name: "Underwater Cave",
      version: "1.0.0",
      author: "VibeStudio",
      description: "Bioluminescent underwater cave with deep blues and glowing accents",
      created: new Date().toISOString(),
      modified: new Date().toISOString(),

      font: {
        family: "Cascadia Code, monospace",
        size: 14,
        weight: "normal",
        ligatures: true,
        lineHeight: 1.3,
      },

      cursor: {
        style: "line",
        blinking: true,
        color: "#00bfff",
      },

      colors: {
        background: "#001122",
        foreground: "#00bfff",
        selection: "#0080ff",
        selectionBackground: "#0080ff",

        ansiBlack: "#001122",
        ansiRed: "#ff4080",
        ansiGreen: "#40ff80",
        ansiYellow: "#ffff40",
        ansiBlue: "#4080ff",
        ansiMagenta: "#8040ff",
        ansiCyan: "#40ffff",
        ansiWhite: "#ffffff",
        ansiBrightBlack: "#002244",
        ansiBrightRed: "#ff60a0",
        ansiBrightGreen: "#60ffa0",
        ansiBrightYellow: "#ffff60",
        ansiBrightBlue: "#60a0ff",
        ansiBrightMagenta: "#a060ff",
        ansiBrightCyan: "#60ffff",
        ansiBrightWhite: "#ffffff",

        border: "#003366",
        tab: {
          activeForeground: "#00bfff",
          activeBackground: "#001122",
          inactiveForeground: "#4080ff",
          inactiveBackground: "#002244",
          border: "#003366",
        },
      },

      integration: {
        applyToEditor: true,
        applyToTerminal: true,
        applyToWorkbench: true,
      },

      editorTheme: {
        editor: {
          background: "#001122",
          foreground: "#00bfff",
          selectionBackground: "#008fff80",
          selectionForeground: "#ffffff",
          lineHighlightBackground: "#002244",
          cursorColor: "#00bfff",
          indentGuideBackground: "#003366",
          indentGuideActiveBackground: "#00bfff",
        },
        activityBar: {
          background: "#002244",
          foreground: "#00bfff",
          inactiveForeground: "#4080ff",
          border: "#003366",
          activeBorder: "#00bfff",
          activeBackground: "#001122",
        },
        sideBar: {
          background: "#001122",
          foreground: "#00bfff",
          border: "#003366",
        },
        statusBar: {
          background: "#00bfff",
          foreground: "#001122",
          border: "#00bfff",
          debuggingBackground: "#8040ff",
          debuggingForeground: "#ffffff",
          noFolderBackground: "#4080ff",
          noFolderForeground: "#ffffff",
        },
        titleBar: {
          activeBackground: "#002244",
          activeForeground: "#00bfff",
          inactiveBackground: "#001122",
          inactiveForeground: "#4080ff",
          border: "#003366",
        },
        panel: {
          background: "#001122",
          border: "#003366",
          dropBorder: "#00bfff",
        },
        tab: {
          activeBackground: "#001122",
          activeForeground: "#00bfff",
          activeBorder: "#00bfff",
          activeBorderTop: "#00bfff",
          inactiveBackground: "#002244",
          inactiveForeground: "#4080ff",
          inactiveModifiedBorder: "#40ff80",
          unfocusedActiveBackground: "#002244",
          unfocusedActiveForeground: "#4080ff",
          unfocusedInactiveBackground: "#001122",
          unfocusedInactiveForeground: "#003366",
          border: "#003366",
        },
        input: {
          background: "#002244",
          foreground: "#00bfff",
          border: "#003366",
          placeholderForeground: "#4080ff",
        },
        button: {
          background: "#00bfff",
          foreground: "#001122",
          hoverBackground: "#40cfff",
          secondaryBackground: "#003366",
          secondaryForeground: "#00bfff",
          secondaryHoverBackground: "#004488",
        },
        checkbox: {
          background: "#002244",
          foreground: "#00bfff",
          border: "#003366",
        },
        badge: {
          background: "#00bfff",
          foreground: "#001122",
        },
        progressBar: {
          background: "#00bfff",
        },
        dropdown: {
          background: "#002244",
          foreground: "#00bfff",
          border: "#003366",
        },
        list: {
          activeSelectionBackground: "#008fff80",
          activeSelectionForeground: "#ffffff",
          inactiveSelectionBackground: "#003366",
          inactiveSelectionForeground: "#00bfff",
          hoverBackground: "#002244",
          hoverForeground: "#00bfff",
          focusBackground: "#008fff80",
          focusForeground: "#ffffff",
        },
        scrollbar: {
          shadow: "#003366",
        },
        syntax: {
          comment: "#4080ff",
          keyword: "#00bfff",
          string: "#40ff80",
          number: "#ffff40",
          function: "#8040ff",
          variable: "#00bfff",
          type: "#40ffff",
          class: "#ff4080",
          interface: "#60ffff",
          namespace: "#8040ff",
          operator: "#00bfff",
          punctuation: "#00bfff",
          constant: "#ffff40",
          property: "#00bfff",
          tag: "#ff4080",
          attribute: "#40ffff",
        },
      },

      effects: {
        transparency: 10,
        blur: 3,
        animations: true,
        particleEffects: true,
        glowEffect: true,
        scanlines: false,
        crtEffect: false,
      },
    },
  },
];
