import { ThemePreset } from "../types";

export const warmPresets: ThemePreset[] = [
  // 🌅 Sunset Orange - Warm sunset vibes with orange and red tones
  {
    id: "sunset-orange",
    name: "🌅 Sunset Orange",
    description: "Warm sunset vibes with orange and red tones",
    category: "warm",
    preview: "",
    theme: {
      name: "Sunset Orange",
      version: "1.0.0",
      author: "VibeStudio",
      description: "Warm sunset vibes with orange and red tones",
      created: new Date().toISOString(),
      modified: new Date().toISOString(),

      font: {
        family: "Source Code Pro, monospace",
        size: 14,
        weight: "normal",
        ligatures: true,
        lineHeight: 1.2,
      },

      cursor: {
        style: "line",
        blinking: true,
        color: "#ff6347",
      },

      colors: {
        background: "#2b1810",
        foreground: "#ff6347",
        selection: "#ff4500",
        selectionBackground: "#ff4500",

        ansiBlack: "#2b1810",
        ansiRed: "#ff6347",
        ansiGreen: "#ffa500",
        ansiYellow: "#ffd700",
        ansiBlue: "#ff7f50",
        ansiMagenta: "#dc143c",
        ansiCyan: "#ff8c00",
        ansiWhite: "#fff8dc",
        ansiBrightBlack: "#4b2817",
        ansiBrightRed: "#ff7f7f",
        ansiBrightGreen: "#ffb347",
        ansiBrightYellow: "#ffe135",
        ansiBrightBlue: "#ff9370",
        ansiBrightMagenta: "#e55b7a",
        ansiBrightCyan: "#ffa347",
        ansiBrightWhite: "#ffffff",

        border: "#8b4513",
        tab: {
          activeForeground: "#ff6347",
          activeBackground: "#3b2414",
          inactiveForeground: "#cd853f",
          inactiveBackground: "#2b1810",
          border: "#8b4513",
        },
      },

      integration: {
        applyToEditor: true,
        applyToTerminal: true,
        applyToWorkbench: true,
      },

      editorTheme: {
        editor: {
          background: "#2b1810",
          foreground: "#ff6347",
          selectionBackground: "#ff4500",
          selectionForeground: "#ffffff",
          lineHighlightBackground: "#3b2414",
          cursorColor: "#ff6347",
          indentGuideBackground: "#8b4513",
          indentGuideActiveBackground: "#ff6347",
        },
        activityBar: {
          background: "#1a0e08",
          foreground: "#ff6347",
          inactiveForeground: "#cd853f",
          border: "#8b4513",
          activeBorder: "#ffd700",
          activeBackground: "#3b2414",
        },
        sideBar: {
          background: "#2b1810",
          foreground: "#ff6347",
          border: "#8b4513",
        },
        sideBarSectionHeader: {
          background: "#3b2414",
          foreground: "#ff6347",
          border: "#ffd700",
        },
        panelTitle: {
          background: "#2b1810",
          activeForeground: "#ff6347",
          activeBorder: "#ffd700",
          inactiveForeground: "#cd853f",
        },
        statusBar: {
          background: "#ff6347",
          foreground: "#ffffff",
          border: "#ff6347",
          debuggingBackground: "#dc143c",
          debuggingForeground: "#ffffff",
          noFolderBackground: "#ff4500",
          noFolderForeground: "#ffffff",
        },
        titleBar: {
          activeBackground: "#1a0e08",
          activeForeground: "#ff6347",
          inactiveBackground: "#2b1810",
          inactiveForeground: "#cd853f",
          border: "#8b4513",
        },
        panel: {
          background: "#2b1810",
          border: "#8b4513",
          dropBorder: "#ff6347",
        },
        tab: {
          background: "#1a0e08",
          activeBackground: "#2b1810",
          activeForeground: "#ff6347",
          activeBorder: "#ffd700",
          activeBorderTop: "#ffd700",
          inactiveBackground: "#3b2414",
          inactiveForeground: "#cd853f",
          inactiveModifiedBorder: "#dc143c",
          unfocusedActiveBackground: "#3b2414",
          unfocusedActiveForeground: "#cd853f",
          unfocusedInactiveBackground: "#1a0e08",
          unfocusedInactiveForeground: "#a0522d",
          border: "#8b4513",
        },
        input: {
          background: "#3b2414",
          foreground: "#ff6347",
          border: "#8b4513",
          placeholderForeground: "#cd853f",
        },
        button: {
          background: "#ff6347",
          foreground: "#ffffff",
          hoverBackground: "#ff4500",
          secondaryBackground: "#8b4513",
          secondaryForeground: "#ff6347",
          secondaryHoverBackground: "#cd853f",
        },
        checkbox: {
          background: "#3b2414",
          foreground: "#ff6347",
          border: "#8b4513",
        },
        badge: {
          background: "#ffd700",
          foreground: "#2b1810",
        },
        progressBar: {
          background: "#ff6347",
        },
        dropdown: {
          background: "#3b2414",
          foreground: "#ff6347",
          border: "#8b4513",
        },
        list: {
          activeSelectionBackground: "#ff6347",
          activeSelectionForeground: "#ffffff",
          inactiveSelectionBackground: "#8b4513",
          inactiveSelectionForeground: "#ff6347",
          hoverBackground: "#3b2414",
          hoverForeground: "#ff6347",
          focusBackground: "#ff6347",
          focusForeground: "#ffffff",
        },
        scrollbar: {
          shadow: "#ff6347",
          sliderBackground: "#ff6347",
          sliderHoverBackground: "#ff7f50",
          sliderActiveBackground: "#ff8c69",
        },
        breadcrumb: {
          background: "#3d1b0a",
        },
        editorGutter: {
          background: "#3d1b0a",
        },
        minimap: {
          background: "#2a1408",
          sliderBackground: "#ff634760",
          sliderHoverBackground: "#ff634780",
          sliderActiveBackground: "#ff6347a0",
        },
        syntax: {
          comment: "#cd853f",
          keyword: "#ff6347",
          string: "#ffd700",
          number: "#ffa500",
          function: "#ff7f50",
          variable: "#ff6347",
          type: "#dc143c",
          class: "#ff6347",
          interface: "#ff8c00",
          namespace: "#dc143c",
          operator: "#ff6347",
          punctuation: "#ff6347",
          constant: "#ffd700",
          property: "#ff6347",
          tag: "#ff6347",
          attribute: "#ffd700",
        },
      },

      effects: {
        transparency: 5,
        blur: 2,
        animations: true,
        particleEffects: false,
        glowEffect: true,
        scanlines: false,
        crtEffect: false,
      },
    },
  },

  // ☕ Coffee Shop - Warm browns and cozy café vibes
  {
    id: "coffee-shop",
    name: "☕ Coffee Shop",
    description: "Warm browns and cozy café vibes",
    category: "warm",
    preview: "",
    theme: {
      name: "Coffee Shop",
      version: "1.0.0",
      author: "VibeStudio",
      description: "Warm browns and cozy café vibes",
      created: new Date().toISOString(),
      modified: new Date().toISOString(),

      font: {
        family: "PT Mono, monospace",
        size: 14,
        weight: "normal",
        ligatures: false,
        lineHeight: 1.3,
      },

      cursor: {
        style: "line",
        blinking: true,
        color: "#d2691e",
      },

      colors: {
        background: "#3c2415",
        foreground: "#d2691e",
        selection: "#cd853f",
        selectionBackground: "#cd853f",

        ansiBlack: "#3c2415",
        ansiRed: "#b22222",
        ansiGreen: "#8fbc8f",
        ansiYellow: "#daa520",
        ansiBlue: "#4682b4",
        ansiMagenta: "#dda0dd",
        ansiCyan: "#5f9ea0",
        ansiWhite: "#f5deb3",
        ansiBrightBlack: "#696969",
        ansiBrightRed: "#dc143c",
        ansiBrightGreen: "#90ee90",
        ansiBrightYellow: "#ffd700",
        ansiBrightBlue: "#87ceeb",
        ansiBrightMagenta: "#da70d6",
        ansiBrightCyan: "#afeeee",
        ansiBrightWhite: "#ffffff",

        border: "#8b4513",
        tab: {
          activeForeground: "#d2691e",
          activeBackground: "#5d3a1a",
          inactiveForeground: "#a0522d",
          inactiveBackground: "#3c2415",
          border: "#8b4513",
        },
      },

      integration: {
        applyToEditor: true,
        applyToTerminal: true,
        applyToWorkbench: true,
      },

      editorTheme: {
        editor: {
          background: "#3c2415",
          foreground: "#d2691e",
          selectionBackground: "#cd853f",
          selectionForeground: "#ffffff",
          lineHighlightBackground: "#5d3a1a",
          cursorColor: "#d2691e",
          indentGuideBackground: "#8b4513",
          indentGuideActiveBackground: "#d2691e",
        },
        activityBar: {
          background: "#2e1b0e",
          foreground: "#d2691e",
          inactiveForeground: "#a0522d",
          border: "#8b4513",
          activeBorder: "#daa520",
          activeBackground: "#5d3a1a",
        },
        sideBar: {
          background: "#3c2415",
          foreground: "#d2691e",
          border: "#8b4513",
        },
        sideBarSectionHeader: {
          background: "#2e1b0e",
          foreground: "#d2691e",
          border: "#daa520",
        },
        panelTitle: {
          background: "#3c2415",
          activeForeground: "#d2691e",
          activeBorder: "#daa520",
          inactiveForeground: "#a0522d",
        },
        statusBar: {
          background: "#d2691e",
          foreground: "#ffffff",
          border: "#d2691e",
          debuggingBackground: "#b22222",
          debuggingForeground: "#ffffff",
          noFolderBackground: "#4682b4",
          noFolderForeground: "#ffffff",
        },
        titleBar: {
          activeBackground: "#2e1b0e",
          activeForeground: "#d2691e",
          inactiveBackground: "#3c2415",
          inactiveForeground: "#a0522d",
          border: "#8b4513",
        },
        panel: {
          background: "#3c2415",
          border: "#8b4513",
          dropBorder: "#d2691e",
        },
        tab: {
          background: "#252526",
          activeBackground: "#3c2415",
          activeForeground: "#d2691e",
          activeBorder: "#daa520",
          activeBorderTop: "#daa520",
          inactiveBackground: "#5d3a1a",
          inactiveForeground: "#a0522d",
          inactiveModifiedBorder: "#b22222",
          unfocusedActiveBackground: "#5d3a1a",
          unfocusedActiveForeground: "#a0522d",
          unfocusedInactiveBackground: "#2e1b0e",
          unfocusedInactiveForeground: "#8b4513",
          border: "#8b4513",
        },
        input: {
          background: "#5d3a1a",
          foreground: "#d2691e",
          border: "#8b4513",
          placeholderForeground: "#a0522d",
        },
        button: {
          background: "#d2691e",
          foreground: "#ffffff",
          hoverBackground: "#cd853f",
          secondaryBackground: "#8b4513",
          secondaryForeground: "#d2691e",
          secondaryHoverBackground: "#a0522d",
        },
        checkbox: {
          background: "#5d3a1a",
          foreground: "#d2691e",
          border: "#8b4513",
        },
        badge: {
          background: "#daa520",
          foreground: "#3c2415",
        },
        progressBar: {
          background: "#d2691e",
        },
        dropdown: {
          background: "#5d3a1a",
          foreground: "#d2691e",
          border: "#8b4513",
        },
        list: {
          activeSelectionBackground: "#d2691e",
          activeSelectionForeground: "#ffffff",
          inactiveSelectionBackground: "#8b4513",
          inactiveSelectionForeground: "#d2691e",
          hoverBackground: "#5d3a1a",
          hoverForeground: "#d2691e",
          focusBackground: "#d2691e",
          focusForeground: "#ffffff",
        },
        scrollbar: {
          shadow: "#bf360c",
          sliderBackground: "#d2691e",
          sliderHoverBackground: "#ff7f50",
          sliderActiveBackground: "#ff8c69",
        },
        breadcrumb: {
          background: "#3c2415",
        },
        editorGutter: {
          background: "#3c2415",
        },
        minimap: {
          background: "#2e1b0e",
          sliderBackground: "#d2691e60",
          sliderHoverBackground: "#d2691e80",
          sliderActiveBackground: "#d2691ea0",
        },
        syntax: {
          comment: "#a0522d",
          keyword: "#d2691e",
          string: "#8fbc8f",
          number: "#daa520",
          function: "#4682b4",
          variable: "#d2691e",
          type: "#dda0dd",
          class: "#d2691e",
          interface: "#5f9ea0",
          namespace: "#dda0dd",
          operator: "#d2691e",
          punctuation: "#d2691e",
          constant: "#daa520",
          property: "#d2691e",
          tag: "#d2691e",
          attribute: "#8fbc8f",
        },
      },

      effects: {
        transparency: 0,
        blur: 0,
        animations: false,
        particleEffects: false,
        glowEffect: false,
        scanlines: false,
        crtEffect: false,
      },
    },
  },

  // 🌅 Desert Sunset - Warm desert sunset vibes
  {
    id: "desert-sunset",
    name: "🌅 Desert Sunset",
    description: "Warm desert sunset with golden sand and fiery sky",
    category: "warm",
    preview: "",
    theme: {
      name: "Desert Sunset",
      version: "1.0.0",
      author: "VibeStudio",
      description: "Warm desert sunset with golden sand and fiery sky",
      created: new Date().toISOString(),
      modified: new Date().toISOString(),

      font: {
        family: "Ubuntu Mono, monospace",
        size: 14,
        weight: "normal",
        ligatures: false,
        lineHeight: 1.3,
      },

      cursor: {
        style: "block",
        blinking: true,
        color: "#ff6b35",
      },

      colors: {
        background: "#2f1b0c",
        foreground: "#ffc857",
        selection: "#ff8c42",
        selectionBackground: "#ff8c42",

        ansiBlack: "#2f1b0c",
        ansiRed: "#ff6b35",
        ansiGreen: "#f18f01",
        ansiYellow: "#ffc857",
        ansiBlue: "#c73e1d",
        ansiMagenta: "#db7f67",
        ansiCyan: "#ffb997",
        ansiWhite: "#ffc857",
        ansiBrightBlack: "#5a3016",
        ansiBrightRed: "#ff8c42",
        ansiBrightGreen: "#f4a261",
        ansiBrightYellow: "#ffd23f",
        ansiBrightBlue: "#e76f51",
        ansiBrightMagenta: "#e9c46a",
        ansiBrightCyan: "#f4a261",
        ansiBrightWhite: "#ffffff",

        border: "#5a3016",
        tab: {
          activeForeground: "#ffc857",
          activeBackground: "#2f1b0c",
          inactiveForeground: "#db7f67",
          inactiveBackground: "#5a3016",
          border: "#5a3016",
        },
      },

      integration: {
        applyToEditor: true,
        applyToTerminal: true,
        applyToWorkbench: true,
      },

      editorTheme: {
        editor: {
          background: "#2f1b0c",
          foreground: "#ffc857",
          selectionBackground: "#ff8c4280",
          selectionForeground: "#ffffff",
          lineHighlightBackground: "#3d240f",
          cursorColor: "#ff6b35",
          indentGuideBackground: "#5a3016",
          indentGuideActiveBackground: "#ff6b35",
        },
        activityBar: {
          background: "#3d240f",
          foreground: "#ffc857",
          inactiveForeground: "#db7f67",
          border: "#5a3016",
          activeBorder: "#ff6b35",
          activeBackground: "#2f1b0c",
        },
        sideBar: {
          background: "#2f1b0c",
          foreground: "#ffc857",
          border: "#5a3016",
        },
        sideBarSectionHeader: {
          background: "#3d2212",
          foreground: "#ffc857",
          border: "#ff6b35",
        },
        panelTitle: {
          background: "#2f1b0c",
          activeForeground: "#ffc857",
          activeBorder: "#ff6b35",
          inactiveForeground: "#db7f67",
        },
        statusBar: {
          background: "#ff6b35",
          foreground: "#ffffff",
          border: "#ff6b35",
          debuggingBackground: "#c73e1d",
          debuggingForeground: "#ffffff",
          noFolderBackground: "#f18f01",
          noFolderForeground: "#2f1b0c",
        },
        titleBar: {
          activeBackground: "#3d240f",
          activeForeground: "#ffc857",
          inactiveBackground: "#2f1b0c",
          inactiveForeground: "#db7f67",
          border: "#5a3016",
        },
        panel: {
          background: "#2f1b0c",
          border: "#5a3016",
          dropBorder: "#ff6b35",
        },
        tab: {
          background: "#252526",
          activeBackground: "#2f1b0c",
          activeForeground: "#ffc857",
          activeBorder: "#ff6b35",
          activeBorderTop: "#ff6b35",
          inactiveBackground: "#3d240f",
          inactiveForeground: "#db7f67",
          inactiveModifiedBorder: "#f18f01",
          unfocusedActiveBackground: "#3d240f",
          unfocusedActiveForeground: "#db7f67",
          unfocusedInactiveBackground: "#2f1b0c",
          unfocusedInactiveForeground: "#5a3016",
          border: "#5a3016",
        },
        input: {
          background: "#3d240f",
          foreground: "#ffc857",
          border: "#5a3016",
          placeholderForeground: "#db7f67",
        },
        button: {
          background: "#ff6b35",
          foreground: "#ffffff",
          hoverBackground: "#ff8c42",
          secondaryBackground: "#5a3016",
          secondaryForeground: "#ffc857",
          secondaryHoverBackground: "#db7f67",
        },
        checkbox: {
          background: "#3d240f",
          foreground: "#ffc857",
          border: "#5a3016",
        },
        badge: {
          background: "#ff6b35",
          foreground: "#ffffff",
        },
        progressBar: {
          background: "#ff6b35",
        },
        dropdown: {
          background: "#3d240f",
          foreground: "#ffc857",
          border: "#5a3016",
        },
        list: {
          activeSelectionBackground: "#ff8c4280",
          activeSelectionForeground: "#ffffff",
          inactiveSelectionBackground: "#3d240f",
          inactiveSelectionForeground: "#ffc857",
          hoverBackground: "#3d240f",
          hoverForeground: "#ffc857",
          focusBackground: "#ff8c4280",
          focusForeground: "#ffffff",
        },
        scrollbar: {
          shadow: "#ff6b35",
          sliderBackground: "#ff6b35",
          sliderHoverBackground: "#ff7f50",
          sliderActiveBackground: "#ff8c69",
        },
        breadcrumb: {
          background: "#4a2c17",
        },
        editorGutter: {
          background: "#4a2c17",
        },
        minimap: {
          background: "#5a3016",
          sliderBackground: "#ff6b3560",
          sliderHoverBackground: "#ff6b3580",
          sliderActiveBackground: "#ff6b35a0",
        },
        syntax: {
          comment: "#db7f67",
          keyword: "#ff6b35",
          string: "#f18f01",
          number: "#ffc857",
          function: "#c73e1d",
          variable: "#ffc857",
          type: "#e9c46a",
          class: "#ff8c42",
          interface: "#f4a261",
          namespace: "#c73e1d",
          operator: "#ff6b35",
          punctuation: "#ffc857",
          constant: "#ffc857",
          property: "#ffc857",
          tag: "#ff8c42",
          attribute: "#e9c46a",
        },
      },

      effects: {
        transparency: 3,
        blur: 1,
        animations: true,
        particleEffects: true,
        glowEffect: true,
        scanlines: false,
        crtEffect: false,
      },
    },
  },

  // 🧿 Golden Hour - Magical golden hour lighting
  {
    id: "golden-hour",
    name: "🧿 Golden Hour",
    description: "Magical golden hour lighting with warm amber tones",
    category: "warm",
    preview: "",
    theme: {
      name: "Golden Hour",
      version: "1.0.0",
      author: "VibeStudio",
      description: "Magical golden hour lighting with warm amber tones",
      created: new Date().toISOString(),
      modified: new Date().toISOString(),

      font: {
        family: "Operator Mono, monospace",
        size: 14,
        weight: "normal",
        ligatures: true,
        lineHeight: 1.4,
      },

      cursor: {
        style: "line",
        blinking: true,
        color: "#ffb700",
      },

      colors: {
        background: "#1a1309",
        foreground: "#ffd700",
        selection: "#ff8c00",
        selectionBackground: "#ff8c00",

        ansiBlack: "#1a1309",
        ansiRed: "#ff6347",
        ansiGreen: "#daa520",
        ansiYellow: "#ffd700",
        ansiBlue: "#ff8c00",
        ansiMagenta: "#ffa500",
        ansiCyan: "#ffb347",
        ansiWhite: "#ffd700",
        ansiBrightBlack: "#2d1f0a",
        ansiBrightRed: "#ff7f50",
        ansiBrightGreen: "#f0e68c",
        ansiBrightYellow: "#ffff00",
        ansiBrightBlue: "#ffb347",
        ansiBrightMagenta: "#ffb700",
        ansiBrightCyan: "#ffc125",
        ansiBrightWhite: "#ffffff",

        border: "#2d1f0a",
        tab: {
          activeForeground: "#ffd700",
          activeBackground: "#1a1309",
          inactiveForeground: "#daa520",
          inactiveBackground: "#2d1f0a",
          border: "#2d1f0a",
        },
      },

      integration: {
        applyToEditor: true,
        applyToTerminal: true,
        applyToWorkbench: true,
      },

      editorTheme: {
        editor: {
          background: "#1a1309",
          foreground: "#ffd700",
          selectionBackground: "#ff8c0080",
          selectionForeground: "#ffffff",
          lineHighlightBackground: "#2d1f0a",
          cursorColor: "#ffb700",
          indentGuideBackground: "#402e0d",
          indentGuideActiveBackground: "#ffb700",
        },
        activityBar: {
          background: "#2d1f0a",
          foreground: "#ffd700",
          inactiveForeground: "#daa520",
          border: "#402e0d",
          activeBorder: "#ffb700",
          activeBackground: "#1a1309",
        },
        sideBar: {
          background: "#1a1309",
          foreground: "#ffd700",
          border: "#402e0d",
        },
        sideBarSectionHeader: {
          background: "#2d1f0a",
          foreground: "#ffd700",
          border: "#ffb700",
        },
        panelTitle: {
          background: "#1a1309",
          activeForeground: "#ffd700",
          activeBorder: "#ffb700",
          inactiveForeground: "#daa520",
        },
        statusBar: {
          background: "#ffb700",
          foreground: "#1a1309",
          border: "#ffb700",
          debuggingBackground: "#ff8c00",
          debuggingForeground: "#1a1309",
          noFolderBackground: "#daa520",
          noFolderForeground: "#1a1309",
        },
        titleBar: {
          activeBackground: "#2d1f0a",
          activeForeground: "#ffd700",
          inactiveBackground: "#1a1309",
          inactiveForeground: "#daa520",
          border: "#402e0d",
        },
        panel: {
          background: "#1a1309",
          border: "#402e0d",
          dropBorder: "#ffb700",
        },
        tab: {
          background: "#252526",
          activeBackground: "#1a1309",
          activeForeground: "#ffd700",
          activeBorder: "#ffb700",
          activeBorderTop: "#ffb700",
          inactiveBackground: "#2d1f0a",
          inactiveForeground: "#daa520",
          inactiveModifiedBorder: "#ff8c00",
          unfocusedActiveBackground: "#2d1f0a",
          unfocusedActiveForeground: "#daa520",
          unfocusedInactiveBackground: "#1a1309",
          unfocusedInactiveForeground: "#402e0d",
          border: "#402e0d",
        },
        input: {
          background: "#2d1f0a",
          foreground: "#ffd700",
          border: "#402e0d",
          placeholderForeground: "#daa520",
        },
        button: {
          background: "#ffb700",
          foreground: "#1a1309",
          hoverBackground: "#ffc125",
          secondaryBackground: "#402e0d",
          secondaryForeground: "#ffd700",
          secondaryHoverBackground: "#daa520",
        },
        checkbox: {
          background: "#2d1f0a",
          foreground: "#ffd700",
          border: "#402e0d",
        },
        badge: {
          background: "#ffb700",
          foreground: "#1a1309",
        },
        progressBar: {
          background: "#ffb700",
        },
        dropdown: {
          background: "#2d1f0a",
          foreground: "#ffd700",
          border: "#402e0d",
        },
        list: {
          activeSelectionBackground: "#ff8c0080",
          activeSelectionForeground: "#ffffff",
          inactiveSelectionBackground: "#402e0d",
          inactiveSelectionForeground: "#ffd700",
          hoverBackground: "#2d1f0a",
          hoverForeground: "#ffd700",
          focusBackground: "#ff8c0080",
          focusForeground: "#ffffff",
        },
        scrollbar: {
          shadow: "#ffd700",
          sliderBackground: "#ffd700",
          sliderHoverBackground: "#ffdf00",
          sliderActiveBackground: "#ffed4e",
        },
        breadcrumb: {
          background: "#1a1309",
        },
        editorGutter: {
          background: "#1a1309",
        },
        minimap: {
          background: "#2d1f0a",
          sliderBackground: "#ffd70060",
          sliderHoverBackground: "#ffd70080",
          sliderActiveBackground: "#ffd700a0",
        },
        syntax: {
          comment: "#daa520",
          keyword: "#ffb700",
          string: "#f0e68c",
          number: "#ffd700",
          function: "#ff8c00",
          variable: "#ffd700",
          type: "#ffa500",
          class: "#ffb347",
          interface: "#ffc125",
          namespace: "#ff8c00",
          operator: "#ffb700",
          punctuation: "#ffd700",
          constant: "#ffd700",
          property: "#ffd700",
          tag: "#ffb347",
          attribute: "#ffa500",
        },
      },

      effects: {
        transparency: 8,
        blur: 2,
        animations: true,
        particleEffects: true,
        glowEffect: true,
        scanlines: false,
        crtEffect: false,
      },
    },
  },

  // 🔥 Lava Flow - Molten lava and volcanic energy
  {
    id: "lava-flow",
    name: "🔥 Lava Flow",
    description: "Molten lava and volcanic energy with fiery red-orange colors",
    category: "warm",
    preview: "",
    theme: {
      name: "Lava Flow",
      version: "1.0.0",
      author: "VibeStudio",
      description: "Molten lava and volcanic energy with fiery red-orange colors",
      created: new Date().toISOString(),
      modified: new Date().toISOString(),

      font: {
        family: "Hack, monospace",
        size: 14,
        weight: "bold",
        ligatures: false,
        lineHeight: 1.2,
      },

      cursor: {
        style: "block",
        blinking: true,
        color: "#ff4500",
      },

      colors: {
        background: "#1a0000",
        foreground: "#ff6600",
        selection: "#ff4500",
        selectionBackground: "#ff4500",

        ansiBlack: "#1a0000",
        ansiRed: "#ff0000",
        ansiGreen: "#ff6600",
        ansiYellow: "#ff8c00",
        ansiBlue: "#ff4500",
        ansiMagenta: "#ff1493",
        ansiCyan: "#ff7f50",
        ansiWhite: "#ff6600",
        ansiBrightBlack: "#330000",
        ansiBrightRed: "#ff3333",
        ansiBrightGreen: "#ff9933",
        ansiBrightYellow: "#ffaa00",
        ansiBrightBlue: "#ff6633",
        ansiBrightMagenta: "#ff4d6d",
        ansiBrightCyan: "#ff9966",
        ansiBrightWhite: "#ffffff",

        border: "#330000",
        tab: {
          activeForeground: "#ff6600",
          activeBackground: "#1a0000",
          inactiveForeground: "#cc3300",
          inactiveBackground: "#330000",
          border: "#330000",
        },
      },

      integration: {
        applyToEditor: true,
        applyToTerminal: true,
        applyToWorkbench: true,
      },

      editorTheme: {
        editor: {
          background: "#1a0000",
          foreground: "#ff6600",
          selectionBackground: "#ff450080",
          selectionForeground: "#ffffff",
          lineHighlightBackground: "#2d0000",
          cursorColor: "#ff4500",
          indentGuideBackground: "#330000",
          indentGuideActiveBackground: "#ff4500",
        },
        activityBar: {
          background: "#2d0000",
          foreground: "#ff6600",
          inactiveForeground: "#cc3300",
          border: "#330000",
          activeBorder: "#ff4500",
          activeBackground: "#1a0000",
        },
        sideBar: {
          background: "#1a0000",
          foreground: "#ff6600",
          border: "#330000",
        },
        sideBarSectionHeader: {
          background: "#2d0000",
          foreground: "#ff6600",
          border: "#ff4500",
        },
        panelTitle: {
          background: "#1a0000",
          activeForeground: "#ff6600",
          activeBorder: "#ff4500",
          inactiveForeground: "#cc3300",
        },
        statusBar: {
          background: "#ff4500",
          foreground: "#ffffff",
          border: "#ff4500",
          debuggingBackground: "#ff0000",
          debuggingForeground: "#ffffff",
          noFolderBackground: "#ff6600",
          noFolderForeground: "#1a0000",
        },
        titleBar: {
          activeBackground: "#2d0000",
          activeForeground: "#ff6600",
          inactiveBackground: "#1a0000",
          inactiveForeground: "#cc3300",
          border: "#330000",
        },
        panel: {
          background: "#1a0000",
          border: "#330000",
          dropBorder: "#ff4500",
        },
        tab: {
          background: "#252526",
          activeBackground: "#1a0000",
          activeForeground: "#ff6600",
          activeBorder: "#ff4500",
          activeBorderTop: "#ff4500",
          inactiveBackground: "#2d0000",
          inactiveForeground: "#cc3300",
          inactiveModifiedBorder: "#ff8c00",
          unfocusedActiveBackground: "#2d0000",
          unfocusedActiveForeground: "#cc3300",
          unfocusedInactiveBackground: "#1a0000",
          unfocusedInactiveForeground: "#330000",
          border: "#330000",
        },
        input: {
          background: "#2d0000",
          foreground: "#ff6600",
          border: "#330000",
          placeholderForeground: "#cc3300",
        },
        button: {
          background: "#ff4500",
          foreground: "#ffffff",
          hoverBackground: "#ff6600",
          secondaryBackground: "#330000",
          secondaryForeground: "#ff6600",
          secondaryHoverBackground: "#cc3300",
        },
        checkbox: {
          background: "#2d0000",
          foreground: "#ff6600",
          border: "#330000",
        },
        badge: {
          background: "#ff4500",
          foreground: "#ffffff",
        },
        progressBar: {
          background: "#ff4500",
        },
        dropdown: {
          background: "#2d0000",
          foreground: "#ff6600",
          border: "#330000",
        },
        list: {
          activeSelectionBackground: "#ff450080",
          activeSelectionForeground: "#ffffff",
          inactiveSelectionBackground: "#330000",
          inactiveSelectionForeground: "#ff6600",
          hoverBackground: "#2d0000",
          hoverForeground: "#ff6600",
          focusBackground: "#ff450080",
          focusForeground: "#ffffff",
        },
        scrollbar: {
          shadow: "#ff4500",
          sliderBackground: "#ff4500",
          sliderHoverBackground: "#ff6347",
          sliderActiveBackground: "#ff7f50",
        },
        breadcrumb: {
          background: "#1a0000",
        },
        editorGutter: {
          background: "#1a0000",
        },
        minimap: {
          background: "#2d0000",
          sliderBackground: "#ff450060",
          sliderHoverBackground: "#ff450080",
          sliderActiveBackground: "#ff4500a0",
        },
        syntax: {
          comment: "#cc3300",
          keyword: "#ff4500",
          string: "#ff8c00",
          number: "#ff6600",
          function: "#ff0000",
          variable: "#ff6600",
          type: "#ff7f50",
          class: "#ff3333",
          interface: "#ff9966",
          namespace: "#ff0000",
          operator: "#ff4500",
          punctuation: "#ff6600",
          constant: "#ff6600",
          property: "#ff6600",
          tag: "#ff3333",
          attribute: "#ff7f50",
        },
      },

      effects: {
        transparency: 10,
        blur: 3,
        animations: true,
        particleEffects: true,
        glowEffect: true,
        scanlines: false,
        crtEffect: false,
      },
    },
  },
];
